### ISSUE TITLE
What's wrong with the scroll tests?  They were removed but why?  Can they be fixed.  TLDR; not easily.

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3884] opened 2020-04-19 01:32 UTC
Thanks to #3854 we now have the CI status very prominently displayed in the homepage.

I think it is important to have those tests passing.
On my PC, the frontend scroll test keeps failing. In Travis there are many more failures. Maybe they are related to Saucelabs having problems?

@JohnMcLear, you are the test man: what's wrong here?

**Comment by JohnMcLear** [comment] 2020-04-19 06:43
I need to comment out the scroll tests for now.  That's all.  The reason they are broken is because browsers restricted simulating certain type of arrow key events.

**Comment by JohnMcLear** [comment] 2020-04-19 17:44
Awaiting merge.  That was a nightmare of a job taking far too long due to some additional tests being craftily injected by ``.travis`` and by sauce labs being inefficient (I'm being polite).

**Comment by muxator** [comment] 2020-04-26 09:54
I am baffled by the test results too.

1. I studied the latest Travis job (https://travis-ci.org/github/ether/etherpad-lite/jobs/679581560).
   The log is not informative: the tests seem to start, and at the end there is an error with no explainations.

   Travis log:
   > Remote sauce test '6cb78e5 - googlechrome latest, Linux' started! https://saucelabs.com/jobs/5c4e1febafdb43c79faf570aae9d0933
   > Remote sauce test '6cb78e5 - iexplore 10.0, Windows 8' started! https://saucelabs.com/jobs/0e4c513e6ff9443caf3c205d35d1fb25
   > Remote sauce test '6cb78e5 - firefox latest, Linux' started! https://saucelabs.com/jobs/1f4b33894ee24b879b7918b695c31c04
   > Remote sauce test '6cb78e5 - microsoftedge latest, Windows 10' started! https://saucelabs.com/jobs/4c4965e519b8429e8209d5d6339e72b2
   > Remote sauce test '6cb78e5 - safari latest, OS X 10.15' started! https://saucelabs.com/jobs/66203529d8ae47fbbc8108af6c4981fd
   >
   > [googlechrome latest] 
   >
   > Remote sauce test '6cb78e5 - googlechrome latest, Linux' finished! https://saucelabs.com/jobs/5c4e1febafdb43c79faf570aae9d0933
   >
   > [iexplore 10.0] 
   >
   > Remote sauce test '6cb78e5 - iexplore 10.0, Windows 8' finished! https://saucelabs.com/jobs/0e4c513e6ff9443caf3c205d35d1fb25
   >
   > [firefox latest] 
   >
   > Remote sauce test '6cb78e5 - firefox latest, Linux' finished! https://saucelabs.com/jobs/1f4b33894ee24b879b7918b695c31c04
   >
   > [microsoftedge latest] 
   >
   > Remote sauce test '6cb78e5 - microsoftedge latest, Windows 10' finished! https://saucelabs.com/jobs/4c4965e519b8429e8209d5d6339e72b2
   >
   > [safari latest] 
   >
   > Remote sauce test '6cb78e5 - safari latest, OS X 10.15' finished! https://saucelabs.com/jobs/66203529d8ae47fbbc8108af6c4981fd
   >
   > The command "tests/frontend/travis/runner.sh" exited with 1.  <-- inexplicable final error 

   An interesting info is that if you click on one of the saucelabs links in this log, for example https://app.saucelabs.com/tests/5c4e1febafdb43c79faf570aae9d0933#2, you can see this screenshot:

   ![image](https://user-images.githubusercontent.com/4067621/80304110-6cf3c700-87b4-11ea-947e-3115e2bed3fc.png)

   It seems that (at the moment) **saucelabs browsers are not able to connect to the Etherpad instances in Travis**, thus no test ever starts at all.

   May it be a problem in `sauce_tunnel.sh`?

2. Ok for me if we want to **disable the scroll tests**, as long as they are not informative. Is there a PR that disables them?

**Comment by JohnMcLear** [comment] 2020-04-26 10:06
https://github.com/ether/etherpad-lite/pull/3899

**Comment by JohnMcLear** [comment] 2020-07-16 10:30
Closing as duplicate of #3748

**Closed by JohnMcLear** 2020-07-16 10:30 UTC
Labels: tests
