### ISSUE TITLE
File not found (/tmp/pad name) when creating a new pad

### ISSUE THREAD

**Issue by gergelypolonkai** [ether/etherpad-lite#3347] opened 2018-03-21 05:03 UTC
Sometimes (but not always) when I create a new pad, a red error message appears under the toolbar telling me that the /tmp/padname file doesnʼt exist. If I refresh the page, even if I modified the pad text, the error disappears.

**Comment by JohnMcLear** [comment] 2018-04-03 12:55
Closing due to too vague bug report

**Closed by JohnMcLear** 2018-04-03 12:55 UTC

**Comment by gergelypolonkai** [comment] 2018-04-03 14:45
Sorry, I’m not familiar with debugging Node apps. If you give some guidance I can provide details; without that, the issue will be reported again and ogain…

**Comment by JohnMcLear** [comment] 2018-04-03 15:00
http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by gergelypolonkai** [comment] 2018-04-03 15:49
Iʼm familiar with this.

I try to add some details, although itʼs not easy given I barely know Node.js (hence my request for guidance).

**Comment by nashe** [comment] 2018-04-08 22:07
Which version of Etherpad are you using? Which database backend?
From what I see, only import and export features are likely to write things in /tmp.

**Comment by gergelypolonkai** [comment] 2018-04-09 11:14
I use 1.6.3 with PostgreSQL as a backend.

**Comment by nashe** [comment] 2018-04-09 22:13
May also be linked to `IncomingForm`, but can't reproduce for now. You instance is public?

**Comment by nashe** [comment] 2018-04-10 08:41
I get a "502 Bad Gateway".

**Comment by gergelypolonkai** [comment] 2018-04-10 11:00
Yes, the server was rebooted and I forgot to set etherpad to start automatically. It is up now.

**Comment by nashe** [comment] 2018-04-10 12:07
Is it happening without your plugins `ep_list_pads` and  `ep_codepad`?
Sorry if it sounds dumb but without any reproduction step, I can only try to guess the origin of your issue.

**Comment by nashe** [comment] 2018-04-10 12:13
OK, I accessed your `supervisord` logs (https://pad.polonkai.eu/files#/v/etherpad-stdout---supervisor-dMRLb8.log ; you may want to put them elsewhere) and found the exact error message (`ODEPAD ERR - INIT PAD FAILED to read: /tmp//Hello_World!`). This message comes from https://github.com/LaKing/ep_codepad/blob/82a7eeb8241768eb69eefed6ef0aedb333812419/index.js#L32, so I would advise you to open an issue here instead.

**Comment by nashe** [comment] 2018-04-10 13:40
Good luck with your issue, don't hesitate to open one here again if you think that an API changed and broke `ep_codepad`.
