### ISSUE TITLE
settings.json :   padOptions.lang not applied

### ISSUE THREAD

**Issue by ethyase** [ether/etherpad-lite#5105] opened 2021-07-04 14:23 UTC
Hi,

**Describe the bug**
When trying to change Etherpad language to "fr" in settings.json the lang stays to default english.

**To Reproduce**
In settings.json change lang parameters :  **"padOptions": { "lang":  "fr" }** , but always ignored

**Server:**
    Etherpad version: 1.8.14
    OS: Windows 7
    Node.js version: v12.21.0

**Additional context**

I have look in code static/js/pad.js where the user options in settings.json seems to be loaded by getParams() :

[https://github.com/ether/etherpad-lite/blob/develop/src/static/js/pad.js](url)

Line 151:

`const getParams = () => { `
` // Tries server enforced options first.. `
` for (const setting of getParameters) {`
`   const value = clientVars.padOptions[setting.name];`
`    if (value.toString() === setting.checkVal) {`      **_<-- Problem is here_**
`      setting.callback(value);`

The problem seems to come from this test :

 Line 155:    `if (value.toString() === setting.checkVal) {`

   the user values defined in settings.json are applied by callback only if equal to "setting.checkVal"
   but for lang parameter, setting.checkVal is set to null at line 143:

   `    name: 'lang',
    checkVal: null,`

so test is never successfull if lang has a normal string value like "fr", "en" etc. and callback is never called.
    

Instead, if lang is passed by url like :    [myetherpad.com/p/myPad?lang=fr](url)

then it works because the test is done in another part of the code at Line 166:

`  // Then URL applied stuff`
`  const params = getUrlVars();`

`  for (const setting of getParameters) {`
`    const value = params[setting.name];`

`    if (value && (value === setting.checkVal || setting.checkVal == null)) {`    **_<-- The condition is different_**
`      setting.callback(value);`

with the extra condition:

   **|| setting.checkVal == null**   

that allow callback to be done even if checkVal is null.

So is there a reason why getParams() (Line 151) has not the same test ? :

`const getParams = () => {`
`  // Tries server enforced options first..`
`  for (const setting of getParameters) {`
`    const value = clientVars.padOptions[setting.name];`
`    if (value.toString() === setting.checkVal || setting.checkVal == null)) {`         **_<-- Change test here_**
`      setting.callback(value);`

When i do this modification, lang chosen in settings.json is now well applied.

Thanks for reading.

**Comment by rhansen** [comment] 2021-12-05 02:54
Duplicate of #4559

**Closed by rhansen** 2021-12-05 02:54 UTC
