### ISSUE TITLE
Docker 1.8.5 and 1.8.6 images missing from Docker Hub

### ISSUE THREAD

**Issue by jaywink** [ether/etherpad-lite#4372] opened 2020-09-28 08:32 UTC
Docker 1.8.5 and 1.8.6 images seem to be missing from Docker Hub: https://hub.docker.com/r/etherpad/etherpad

**Comment by jeanfabrice** [comment] 2020-09-29 08:14
duplicates #4276

**Comment by rhansen** [comment] 2020-09-29 18:47
Duplicate of #4276

**Closed by rhansen** 2020-09-29 18:47 UTC
