### ISSUE TITLE
Bad property color attribution

### ISSUE THREAD

**Issue by Sylvain38ria** [ether/etherpad-lite#3427] opened 2018-07-18 10:18 UTC
I have a suspicious behavior and i don't think it's normal.

When a new user writes on a line with a bullet with content that does not belong to him, the whole line changes color to be assigned to him. (not only his words)

Is this normal behavior? 
I can reproduce the error on the demo version online and on my own etherpad session (1.6.6)

**Comment by slel** [comment] 2018-07-18 11:16
Possibly duplicate of #3354 which was solved very recently (09 Jul 2018).
Please check if the fix there solves it, or if your issue is after the fix there.

**Comment by muxator** [comment] 2018-07-19 21:21
The issue described by @Sylvain38ria was indeed present.
More precisely, the authorship color that changed was not always the whole line, but from the start to the point in which he made his edit.

Duplicate of #3354, fixed in 58c315476954 by @lpagliari.
Closing this.

**Closed by muxator** 2018-07-19 21:21 UTC
