### ISSUE TITLE
Error when importing a PDF file

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5184] opened 2021-09-23 08:58 UTC
**Describe the bug**
TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'offsetTop')
at https://my.domain/pad/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=382b7967 at line 65
ErrorId: Eyc9ZzwVorIyCBnXSqyB
Uncaught exception.

**To Reproduce**
1. Go to '...' Import PDF
2. Click on '....' choose and import the pdf
3. Scroll down to '....' not needed as the read box will appear
4. See error like seen above

**Expected behavior**
No error should be shown and the document should get displayed without any problems

**Server (please complete the following information):**
 Etherpad version
Version number: 1.8.14

Latest available version: 1.8.14

Git sha: 571b37b

Installed plugins
ep_auth_session
ep_embedded_hyperlinks2
ep_comments_page
ep_align
ep_etherpad-lite
ep_webrtc
ep_markdown
ep_font_color
ep_headings2
Installed parts
ep_headings2/main
ep_font_color/main
ep_markdown/markdown
ep_webrtc/ep_webrtc
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/stats
ep_etherpad-lite/express
ep_etherpad-lite/Minify
ep_etherpad-lite/DB
ep_align/main
ep_etherpad-lite/webaccess
ep_comments_page/comments_page
ep_etherpad-lite/static
ep_embedded_hyperlinks2/main
ep_auth_session/auth_session
Installed hooks
Server-side hooks
clientVars:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_webrtc:
ep_webrtc:
collectContentPost:
ep_align:
main:
ep_align/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
createServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
eejsBlock_dd_format:
ep_font_color:
main:
ep_font_color/index
eejsBlock_editbarMenuLeft:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
ep_font_color:
main:
ep_font_color/index
ep_headings2:
main:
ep_headings2/index
eejsBlock_editorContainerBox:
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
eejsBlock_exportColumn:
ep_markdown:
markdown:
ep_markdown/index
eejsBlock_mySettings:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_markdown:
markdown:
ep_markdown/index
ep_webrtc:
ep_webrtc:
eejsBlock_scripts:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_markdown:
markdown:
ep_markdown/index
eejsBlock_styles:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_webrtc:
ep_webrtc:
exportEtherpadAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/index
exportHTMLAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
exportHtmlAdditionalTagsWithData:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
expressCloseServer:
ep_etherpad-lite:
socketio:
ep_etherpad-lite/node/hooks/express/socketio
expressConfigure:
ep_etherpad-lite:
webaccess:
ep_etherpad-lite/node/hooks/express/webaccess
expressCreateServer:
ep_auth_session:
auth_session:
ep_auth_session/index:registerRoute
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
admin:
ep_etherpad-lite/node/hooks/express/admin
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
apicalls:
ep_etherpad-lite/node/hooks/express/apicalls
errorhandling:
ep_etherpad-lite/node/hooks/express/errorhandling
i18n:
ep_etherpad-lite/node/hooks/i18n
importexport:
ep_etherpad-lite/node/hooks/express/importexport
openapi:
ep_etherpad-lite/node/hooks/express/openapi
padreadonly:
ep_etherpad-lite/node/hooks/express/padreadonly
padurlsanitize:
ep_etherpad-lite/node/hooks/express/padurlsanitize
socketio:
ep_etherpad-lite/node/hooks/express/socketio
specialpages:
ep_etherpad-lite/node/hooks/express/specialpages
static:
ep_etherpad-lite/node/hooks/express/static
tests:
ep_etherpad-lite/node/hooks/express/tests
ep_markdown:
markdown:
ep_markdown/express
getLineHTMLForExport:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
ep_headings2:
main:
ep_headings2/index
handleMessage:
ep_webrtc:
ep_webrtc:
handleMessageSecurity:
ep_comments_page:
comments_page:
ep_comments_page/index
import:
ep_markdown:
markdown:
ep_markdown/index
loadSettings:
ep_webrtc:
ep_webrtc:
padCopy:
ep_comments_page:
comments_page:
ep_comments_page/index
padInitToolbar:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_font_color:
main:
ep_font_color/index
padRemove:
ep_comments_page:
comments_page:
ep_comments_page/index
restartServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
shutdown:
ep_etherpad-lite:
DB:
ep_etherpad-lite/node/db/DB
express:
ep_etherpad-lite/node/hooks/express
Minify:
ep_etherpad-lite/node/utils/Minify
stats:
ep_etherpad-lite/node/stats
socketio:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
socketio:
ep_etherpad-lite/node/handler/PadMessageHandler
ep_webrtc:
ep_webrtc:
:setSocketIO
stylesForExport:
ep_font_color:
main:
ep_font_color/exportHTML
ep_headings2:
main:
ep_headings2/index
Client-side hooks
aceAttribsToClasses:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceCreateDomLine:
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
aceDomLineProcessLineAttributes:
ep_align:
main:
ep_align/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceEditEvent:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceEditorCSS:
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_markdown:
markdown:
ep_markdown/static/js/markdown
aceInitialized:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceRegisterBlockElements:
ep_align:
main:
ep_align/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
handleClientMessage_RTC_MESSAGE:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postAceInit:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_markdown:
markdown:
ep_markdown/static/js/markdown
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postToolbarInit:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
userJoinOrUpdate:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
userLeave:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js

**Desktop (please complete the following information):**
 - OS: OSX and  iOS
 - Browser chrome, safari

**Smartphone (please complete the following information):**
 - Device: iPhone6SE 

**Additional context**

**Comment by JohnMcLear** [comment] 2021-09-23 10:50
Do you get a failure if you test without plugins?  I imagine one of the plugins is the cause.

**Comment by lisandi** [comment] 2021-09-23 10:55
Do you mean deinstalling all already installed plugins and test in an empty etherpad?
When I deinstall the plugin the error is gone but that I can't use the functionality either. I not really understand what I should do. sorry?

**Comment by JohnMcLear** [comment] 2021-09-23 11:08
Yeah that's right.

So which plugin when you install causes the problem?  If you can pin it down to a specific plugin we should make the issue on that plugins repository.

**Comment by lisandi** [comment] 2021-09-23 12:27
OK, I actually only added the AbiWord and LibreOffice links to settings.json and then import a PDF file
![Screen Shot 2021-09-23 at 19 20 36](https://user-images.githubusercontent.com/1982011/134506073-c14f22a8-855c-4349-8603-b420ca81d87d.png)

![Screen Shot 2021-09-23 at 19 20 53](https://user-images.githubusercontent.com/1982011/134506084-bdcf763d-ffb7-4f32-befa-7d9cf507bd27.png)

![Screen Shot 2021-09-23 at 19 21 18](https://user-images.githubusercontent.com/1982011/134506089-4f91aed5-bfd1-48cb-a6d7-aa7504adc40a.png)

I will deinstall step by step and see if I'll find the culprit if it is a plugin.

**Comment by lisandi** [comment] 2021-09-23 13:14
After I deinstalled the ep_convert plugin it is gone but can't also no more upload ;-)
![Screen Shot 2021-09-23 at 20 14 01](https://user-images.githubusercontent.com/1982011/134513517-deb42163-bffe-46d9-ac5e-6b4a39489a2d.png)

**Comment by JohnMcLear** [comment] 2021-09-23 13:19
Keep on de-installing, it may be multiple plugins causing a problem?

https://github.com/HedCET/ep_convert/issues would be the place to notify the ep_convert author.

**Comment by JohnMcLear** [comment] 2021-09-24 09:23
Closing as related to plugins.

**Closed by JohnMcLear** 2021-09-24 09:23 UTC
Labels: Needs confirmation

**Comment by lisandi** [comment] 2021-09-24 09:37
Interestig is the following

when importing a PDF in a complete new pad it is actually working but when importing into a pad which had been created while the plugin had been installed and all the others too - it throws that errors! For me it looks like it is NOT the plugin but rather the routine of deinstallation of plugins and that when there are leftovers - i.e. if you load a pad which had been created with an older PAD version in the same browser - than also all old plugins get loaded - even they are not even anymore there - we installed a complete new version from git to test out but still all old plugins get loaded when using an older PAD!

**Comment by JohnMcLear** [comment] 2021-09-24 09:46
Can you replicate this issue consistently without using the ``ep_convert`` plugin?  This really does sound like a plugin issue though so I still think it's correct to leave this thread closed.  Opening the issue on ep_convert repo might be more fruitful?

**Comment by lisandi** [comment] 2021-09-24 09:53
Another thing we realized - we deinstalled convert again as we had problems to get ep_embedmedia showing the popup like in teh screenshot. No way to get that working  - we than deinstalled Convert as that was the only other plugin beside those installed by the full feature set of your description

we opened up a complete new Pad because of the experience we had before with the older pad but now after deinstallation all export formats are still available  - is that normal? even we have deinstalled convert?
![Screen Shot 2021-09-24 at 16 44 30](https://user-images.githubusercontent.com/1982011/134655385-91d213b3-3fc4-408f-845e-e37c61a88bd5.png)
No convert Plugin installed but all export still showing up and the icon of embedmedia is IMHO not correct.
![Screen Shot 2021-09-24 at 16 44 39](https://user-images.githubusercontent.com/1982011/134655399-44d517b9-33c7-44dd-a62c-3a526438abba.png)

I am not sure if that behaviour is normal and I would guess it is perhaps a problem on how things get deinstalled from etherpad via the admin interface and with the caching in browsers or elsewhere perhaps.

**Comment by lisandi** [comment] 2021-09-24 09:55
https://phuket.church/pad/
Try yourself just tried in incognito window of chrome but same problem

**Comment by JohnMcLear** [comment] 2021-09-24 09:55
Again, this is really not the right place for plugin bug reports.  The creep in this issue is not constructive!  If you want to open a specific bug report on a plugin, please do so!  If you have a bug report that seems to be related to core then please create an new issue.

**Comment by lisandi** [comment] 2021-09-24 10:01
I have already opened it but as it is not only convert but also embedmedia I am not sure if it is really a plugin problem or much more a problem of how plugins get deinstalled as those problems occure after deinstalling a plugin - no matter which - we also rebuild the dependencies but does not help. In a new core issue I could only copy and paste the same I wrote already here.

**Comment by rhansen** [comment] 2021-09-25 01:12
No plugins are needed for PDF import/export. All that is needed is to set [`soffice`](https://github.com/ether/etherpad-lite/blob/fe7d223b6e7455f170e6389160e7930c977fbb8a/settings.json.template#L318-L324) to the path to your LibreOffice binary.

With a fresh install (**do NOT install any plugins!**) and an empty database please try to reproduce the problem. If you can reproduce the problem, please list the exact steps required. If you can't reproduce the problem, then the problem is caused by a plugin.

**Comment by lisandi** [comment] 2021-09-25 10:24
@rhansen when no plugin is needed why the hell are they still listed inside the plugin repository to make people believe that they will need the convert plugin and probably also other plugins - as there are several others too that seem to convert from ... to (Html/markup). I suggest checking the complete plugin repository which gets listed inside Etherpad plugins and deleting all conflicting plugins in there or at least marks them as corrupting the system. It is a point of usability and maintainability to have that corrected and solved.
![Screen Shot 2021-09-25 at 08 58 19](https://user-images.githubusercontent.com/1982011/134768119-07f2b587-6c0e-4d7b-abae-007a5c800698.png)
I would suggest to mark those at least as DO NOT USE PLUGIN

**Comment by JohnMcLear** [comment] 2021-09-25 10:37
We already have a process for this.  Authors can flag their plugin as deprecated and it is not shown.  Afaik...  If you have issues with plugins, contact the plugin authors!  We're not an app store that can charge people to vet their applications and/or apps, if you want a serene walled garden it will come at a financial, technical and liberty/freedoms cost.

**Comment by lisandi** [comment] 2021-09-25 17:31
I know it needs some kind of self-discipline and honesty to simply mark such a plugin as deprecated or already integrated into the core or no more working. On the other hand side, at least the plugins where "ether" has access could be managed and monitored - Having the author listed in a column of the admin/plugins view would make it easy for people to identify those authors who are reliable and maintaining the plugins and those who have crashing plugins. ;-) It would also help to get those "crashing and buggy" plugin authors probably to maintain/or mark as deprecated and no more maintained their plugins better.

**Comment by rhansen** [comment] 2021-09-26 00:19
> why the hell are they still listed inside the plugin repository

Anyone is allowed to publish a plugin without getting approval. The list of plugins is not moderated, except for general heuristics such as staleness (how long ago the plugin was updated).

> Having the author listed in a column of the admin/plugins view would make it easy for people to identify those authors who are reliable and maintaining the plugins and those who have crashing plugins.

I think it would be nice to mark all "official" (Etherpad foundation) and unofficial-but-known-good plugins with a checkmark icon. Others would get a warning icon. Patches or funding would be welcome.

**Comment by lisandi** [comment] 2021-09-26 03:23
> I think it would be nice to mark all "official" (Etherpad foundation) and unofficial-but-known-good plugins with a checkmark icon. Others would get a warning icon. 

Good idea. I am sure it also would motivate the plugin authors to check more regular their plugin statuses with the current stable version of etherpad-lite. Especially making those official ones - and probably asking those unofficial but known good plugins to become official ones.
