### ISSUE TITLE
Firefox warning: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2427] opened 2015-01-02 12:26 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=969671

http://xhr.spec.whatwg.org/

**Comment by YesThatAllen** [comment] 2018-06-01 13:59
Really detrimental effects in Chrome 67

https://bugs.chromium.org/p/chromium/issues/detail?id=848210

**Comment by JohnMcLear** [comment] 2020-03-30 20:44
Is this related to https://github.com/ether/etherpad-lite/issues/2892 ?

**Comment by muxator** [comment] 2020-03-30 23:10
It is.

The problem is `require-kernel`.

I have done a POC a while ago that shows that it is possible to get rid of it.

That work was based on **browserify**, and I do not advise to use it. But all the surrounding work on the frontend code is still valid, and took a long time to sort out.

Closing this issue. Let's refer to #3603 (the PR with the POC) and #2892.

**Closed by muxator** 2020-03-30 23:10 UTC
Labels: Bug, performance

**Comment by meaz** [comment] 2021-02-28 10:58
I don't know if I do well on commenting a closed issue but I have the exact same error message in Firefox 78.8.0esr

**Comment by rhansen** [comment] 2021-03-01 07:31
Yup, it's a known issue. A fix is in the works, but it will take a while because it is not trivial.

**Comment by rhansen** [comment] 2021-03-01 07:37
@webzwo0i has volunteered to fix this by removing require-kernel. See #4820.
