### ISSUE TITLE
TypeError: Cannot set property 'writingInProgress' of undefined

### ISSUE THREAD

**Issue by elijh** [ether/etherpad-lite#2673] opened 2015-05-20 18:46 UTC
Running the latest develop branch as of today results in this fatal error when using a MySQL database:

```
[2015-05-20 08:45:44.210] [ERROR] console - TypeError: Cannot set property 'writingInProgress' of undefined
at /srv/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:488:56
at /srv/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:199:13
at /srv/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:105:25
at /srv/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:196:17
at Query._callback (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/async/lib/async.js:467:34)
at Query.Sequence.end (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
at Query._handleFinalResultPacket (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
at Query.OkPacket (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
at Protocol._parsePacket (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
at Parser.write (/srv/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
```

Rolling back to an older commit revision allows etherpad-lite to run normally. Sorry, did not track down which commit causes it to fail.

**Comment by elijh** [comment] 2015-05-20 18:58
i am pretty sure it was one of the changes on May 19, because develop HEAD worked fine for us the day before.

**Comment by JohnMcLear** [comment] 2015-05-20 19:08
@elijh can you please bisect and find out?  None of the commits look like they will cause this issue.

Without a bisect or STR it's pretty much a losing battle

**Comment by elijh** [comment] 2015-05-20 23:23
OK, introduced in b662d5c61802d42ee4214799520e7c3ed95a3ef5

oddly not resolved by 818408cf4984be67e4e3955acb9b0364cb0014f9

I don't see how that commit relates to the call stack, but I confirmed several times that everything is kosher with the parent, but crashes on b662d5c61802d42ee4214799520e7c3ed95a3ef5

**Comment by JohnMcLear** [comment] 2015-05-21 13:01
@elijh this makes no sense..  Can you please provide some steps to replicate?

**Comment by shimaore** [comment] 2015-05-22 09:56
@JohnMcLear The error happens because `remove` is enumerated by `for( var i in operations )` at line 488 of `ueberDB/CacheAndBufferLayer.js`. The modification to `Array.prototype` in b662d5c61802d42ee4214799520e7c3ed95a3ef5 is what causes that issue.

To reproduce I simply installed HEAD, modified settings.json to use `sqlite` (and did the required `npm install sqlite3`), and tried to access `/p/test`. Using a dumb `console.log(i)` in `ueberDB/CacheAndBufferLayer.js` I can see the enumerated entries have index `0` and `"remove"`.

**Comment by JohnMcLear** [comment] 2015-05-22 10:06
Okay @shimaore I will try get a fix in for this now, thanks!

**Comment by JohnMcLear** [comment] 2015-05-22 10:09
https://github.com/ether/etherpad-lite/commit/757ad765d3d7fca4e94347962423cb65b1a598d4 should fix it?

**Comment by JohnMcLear** [comment] 2015-05-22 10:10
Let me know if this isn't fixed in develop :) Thanks!

**Closed by JohnMcLear** 2015-05-22 10:10 UTC

**Comment by shimaore** [comment] 2015-05-22 10:13
I suspect it'll just enumerate `removeItem` instead of `remove`, let me check ;)
