### ISSUE TITLE
Have multiple API key access and use RESTful API - Perhaps OAuth ?

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1960] opened 2013-10-21 19:44 UTC
Along with our db model, I want to critisize the way our API works.

One API key with access to everything is not very useful. Also, I'd favor a REST API over the current solution.

Instead we should employ OAuth and add anything as an endpoint, that admin would want to be able to do: An admin back end should use those endpoints at all times.

**Comment by JohnMcLear** [comment] 2015-01-03 13:47
We can help move this forward: https://www.bountysource.com/issues/1371740-api-fail

**Comment by JohnMcLear** [comment] 2020-05-06 18:16
This is a duplicate of another issue

**Closed by JohnMcLear** 2020-05-06 18:16 UTC
Labels: Black hole bug, Feature Request
