### ISSUE TITLE
sessionstorage entries don't get cleaned up

### ISSUE THREAD

**Issue by gberche-orange** [ether/etherpad-lite#3208] opened 2017-06-29 15:20 UTC
We recently experienced an outage on our etherpad-lite instance, due to a crawler/load testing agent which was repetitively hitting a pad (url of form `/p/pad-name`). After about 10 days of unmonitored crawling, this ended up filling up our mysql db storage with millions of entries similar to: 

`| sessionstorage:----O3r2X49fPKoio6vZZRR3RJgYNrIk | {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} |`

This seems similar to #3040 (created by @DanielBickley) except traffic was not hitting API endpoints in our case.

We solved the issue by incrementally cleaning up these entries (using the SQL statement `delete from  store where `key` LIKE 'sessionstorage%'   LIMIT 100000;` )

Surprisingly, the clean up of db entries did not result in users loosing their color or names prompted from [ep_prompt_for_name](https://github.com/JohnMcLear/ep_prompt_for_name.git)

2 days after the clean up (and the stopping the crawler agent), I now observe 3200 new entries.

I wonder whether we have misconfigured etherpad-lite that could explain apparent lack of expiration of the http sessions and removal of the `sessionstorage` entries in the storage. Looking at https://github.com/ether/etherpad-lite/blob/master/settings.json.template I could not spot session expiration related configs described.

More information below on initial code reading/ investigation I've done although I'm not up to speed in nodejs

Thanks in advance for hints to prevent this condition from appearing in the future.

------------

Version of etherpad-lite used is 1.6.0 and the configuration is https://github.com/cloudfoundry-community/etherpad-lite-cf/tree/3a3dce65a13dd7906139f2bf59a1f558b27e2757 

Some code logic seems to assign expiration date https://github.com/ether/etherpad-lite/blob/master/src/node/db/SessionStore.js#L22
https://www.npmjs.com/package/express-session does mention an option `cookie.expires` option

> cookie.expires
> Specifies the Date object to be the value for the Expires Set-Cookie attribute. By default, no expiration is set, and most clients will consider this a "non-persistent cookie" and will delete it on a condition like exiting a web browser application.

Looking at the cookies assigned on the browser side, the `io` cookie indeed has no expiration.

/CC @ArthurHlt

**Comment by DanielBickley** [comment] 2017-06-29 15:41
Currently, I'm using a daily cron task to remove the sessionstorage pollution in the db.

I don't necessarily think the expiration is an issue. Rather, the logic just needs to first do a conditional to check. Has an express session already been started? Yes? Okay, no need to do it again, or add the entry to the db.

```
if(!currentSession)
 db.set("sessionstorage:" + sid, sess);
```

Obviously the above conditional will not work, I'm simply putting it there to demonstrate my theory. I did take several hours and attempt to add a check. However, my efforts were unsuccessful, added my cron task, and I will return to it at a later date. I was hoping somebody with knowledge of the express session creation would be able to easily hammer that out. Doesn't seem to be on anybody's radar, so if I get it figured out at some point, I'll make sure to notify you here.

**Comment by DanielBickley** [comment] 2017-06-29 15:47
See also https://github.com/ether/etherpad-lite/issues/1659

" 
@JohnMcLear writes above in regards to "express is creating a bunch of sessions for each get request, prolly need a way to specify to create a session if one doesn't exist." Might I add, determine if the API is making the request, and suppressing any type of db record insert, particularily where the express_sid is not altered in this instance anyway.
"

src/node/hooks/webaccess.js exports.expressConfigure() - think that is where this needs to be adjusted

**Comment by gberche-orange** [comment] 2017-06-30 07:38
thanks @DanielBickley for yours updates !

**Comment by JohnMcLear** [comment] 2018-04-03 15:49
Yea this is dupe of #1659 

https://github.com/ether/etherpad-lite/issues/3208

cc @nashe as potential DoS ?

**Closed by JohnMcLear** 2018-04-03 15:49 UTC
