### ISSUE TITLE
Line number linking doesn’t work

### ISSUE THREAD

**Issue by dertuxmalwieder** [ether/etherpad-lite#4958] opened 2021-03-18 19:33 UTC
**Describe the bug**
I enabled line numbers in the pad settings and clicking a line number *links* to the anchor (e.g.) `#L156`. However, opening the pad with the `#L156` anchor does not scroll down to line 156.

**Server (please complete the following information):**
 - Etherpad version: 1.8.12 (from Git)
 - OS: FreeBSD 12
 - Node.js version (`node --version`): v15.11.0
 - npm version (`npm --version`): 6.14.8

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Safari
 - Version: 14.0.3

**Comment by JohnMcLear** [comment] 2021-03-18 19:36
This is tested in CI and was working last time I looked.  What do the ci tests show for this functionality?  Do you get a pass if you visit /tests/frontend ?

**Comment by dertuxmalwieder** [comment] 2021-03-18 19:48
No, I don’t.

It’s probably this one:

```
scrollTo.js
scrolls to line
Scrolls down to Line 4 ‣
Error: Timeout of 100ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
(https://<DOMAIN>.de/tests/frontend/lib/mocha.js:5526)
doesnt break on weird hash input
```

**Comment by JohnMcLear** [comment] 2021-03-18 20:20
That's the one thanks.  When you clone from git are you getting develop branch?  Can you tell us your git sha?

**Comment by dertuxmalwieder** [comment] 2021-03-18 20:22
Yes, it’s develop. I’m running  5c9514f926c1dbdf6a9ed82e81961c655bf48deb.

**Comment by JohnMcLear** [comment] 2021-03-18 20:24
Oh wow thanks for quick feedback..  so it passes in CI, is frontend code yet you have bugs...  Is this a public instance??

**Comment by dertuxmalwieder** [comment] 2021-03-18 20:27
It is. It’s piraten-bs-pad.de (officially provided by the local chapter of the Pirate Party).

**Comment by JohnMcLear** [comment] 2021-03-18 20:30
Okay thanks and can you replicate this issue on https://dark.etherpad.com ?

**Comment by dertuxmalwieder** [comment] 2021-03-18 20:33
Yup:
https://dark.etherpad.com/p/Test#L102

**Comment by JohnMcLear** [comment] 2021-03-18 20:35
Seems to be confirmed...  So test is failing and logic where logic was working...   Test needs fixing asap to show failure.

**Comment by JohnMcLear** [comment] 2021-03-18 20:35
Thanks btw...  This is awkward one so a good catch

**Comment by dertuxmalwieder** [comment] 2021-03-18 20:38
Happy to help! :-) Please keep me updated when I can test that!

**Comment by webzwo0i** [comment] 2021-03-19 14:06
This should be fixed in https://github.com/ether/etherpad-lite/pull/4954 
I saw @rhansen did another [PR](https://github.com/ether/etherpad-lite/pull/4960) with the main patch from 4954. Will look into this and merge today, but in the mean time if you want to test any of the two mentioned PRs it would be awesome.

So the problem is why the test is passing

**Comment by rhansen** [comment] 2021-03-20 22:02
Fixed by #4960

**Comment by dertuxmalwieder** [comment] 2021-03-21 11:02
Sorry. :-) Confirmed (late)!

**Comment by dertuxmalwieder** [comment] 2021-07-21 15:00
It stopped working after that.

**Comment by webzwo0i** [comment] 2021-07-21 16:15
reopening as we might need to revert the srcdoc commit due to CSP issues, so this bug might come up again.

@dertuxmalwieder Can you clarify what you mean with "It stopped working after that."? Is the issue here resolved?

**Comment by dertuxmalwieder** [comment] 2021-07-21 18:04
Sorry for confusion: It was fixed once and we noticed that current versions have the problem again. Not sure which revision killed it.

**Comment by JohnMcLear** [comment] 2021-09-09 14:23
I just double checked this and it's working fine

**Closed by JohnMcLear** 2021-09-09 14:23 UTC
Labels: Needs confirmation
