### ISSUE TITLE
Error: Timeout: Did not receive an init message from worker threads

### ISSUE THREAD

**Issue by rfc2119** [ether/etherpad-lite#4326] opened 2020-09-20 07:44 UTC
**Description**
I have installed a vanillia etherpad for the first time. I did not have node installed so I went to install it first (as per your instructions). Upon running `./bin/run.sh` and accessing the instance via any broswer, it crashes. Here is the log output: 
```
git clone --branch master https://github.com/ether/etherpad-lite.git && cd etherpad-lite && bin/run.sh
Cloning into 'etherpad-lite'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 38657 (delta 16), reused 33 (delta 9), pack-reused 38602
Receiving objects: 100% (38657/38657), 26.98 MiB | 6.15 MiB/s, done.
Resolving deltas: 100% (27366/27366), done.
Copy the settings template to settings.json...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> wd@1.12.1 install /home/etherpad/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts

added 1127 packages in 33.718s
Clearing minified cache...
Starting Etherpad...
All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad/etherpad-lite
Random string used for versioning assets: 396a527f
[2020-09-20 09:18:35.878] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/etherpad/etherpad-lite/settings.json"
[2020-09-20 09:18:35.881] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/etherpad/etherpad-lite/credentials.json"
settings loaded from: /home/etherpad/etherpad-lite/settings.json
No credentials file found in /home/etherpad/etherpad-lite/credentials.json. Ignoring.
[2020-09-20 09:18:35.900] [INFO] console - Using skin "colibris" in dir: /home/etherpad/etherpad-lite/src/static/skins/colibris
[2020-09-20 09:18:35.901] [INFO] console - Session key file "/home/etherpad/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
[2020-09-20 09:18:35.902] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /home/etherpad/etherpad-lite/var/dirty.db
[2020-09-20 09:18:37.631] [INFO] APIHandler - Api key file "/home/etherpad/etherpad-lite/APIKEY.txt" not found. Creating with random contents.
[2020-09-20 09:18:37.953] [INFO] console - Installed plugins: 
[2020-09-20 09:18:37.955] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2020-09-20 09:18:37.961] [INFO] console - Your Etherpad version is 1.8.6 (299bd96)
[2020-09-20 09:18:38.639] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2020-09-20 09:18:38.639] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2020-09-20 09:18:38.639] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
[2020-09-20 09:19:19.995] [ERROR] console - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout.setTimeout [as _onTimeout] (/home/etherpad/etherpad-lite/src/node_modules/threads/dist/master/spawn.js:34:53)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2020-09-20 09:19:19.998] [INFO] console - graceful shutdown...
[2020-09-20 09:19:19.999] [INFO] console - db sucessfully closed.
```

I have tried to run it into prod mode. It also crashed
**Desktop Information**
 - OS: Debian 10 (buster). Kernel version: 4.19.98-1
 - Browser: any browser
 - Etherpad version: 1.8.6 (299bd96)

**Comment by JohnMcLear** [comment] 2020-09-20 09:49
What version of node?

**Comment by rfc2119** [comment] 2020-09-20 10:04
Version `v10.22.1`. Nodejs was installed as per your instructions:
```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install -y nodejs
```

**Comment by JohnMcLear** [comment] 2020-09-20 11:46
Try node 12...  10 should work but could be distro / node version weirdness...  Fwiw builds pass so this isn't a major issue...  Has to be an edge case.

**Comment by rfc2119** [comment] 2020-09-22 17:12
It is indeed recommended elsewhere (for some other software) that one should stay away from debian's node 10 builds (and should instead use the node apt repository).
I'll try node 12. If I haven't replied back you can close this issue.

**Comment by JohnMcLear** [comment] 2020-09-22 17:16
Please confirm either way.  We support node 10 so it should work.

**Comment by iuriguilherme** [comment] 2020-10-02 00:17
I have nodejs v10.21.0 from debian buster package and getting the same error.

**Comment by iuriguilherme** [comment] 2020-10-02 00:23
Reinstalling using current LTS (v12) has solved it: https://github.com/nodesource/distributions#installation-instructions

```
# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_lts.x | bash -
apt-get install -y node
```js

**Comment by rhansen** [comment] 2020-10-02 05:55
Duplicate of #4335

**Closed by rhansen** 2020-10-02 05:55 UTC
