### ISSUE TITLE
Can't import ordered lists

### ISSUE THREAD

**Issue by zorrikon** [ether/etherpad-lite#3447] opened 2018-08-10 04:13 UTC
Hi, I've been trying to import a document with ordered lists by calling the HTTP API setHTML, but the resulting document has bullets like:
"1.
1.
1.
1."

That is, all of the bullets are the first element. I've tried multiple different formats for the imported text, but none of them work. For example,
```
<ol class='list-number1' start='1'><li>a</li></ol>
<ol class='list-number1' start='2'><li>b</li></ol>
<ol class='list-number1' start='3'><li>c</li></ol>
<ol class='list-number1' start='4'><li>d</li></ol>
```

and

```
<ol class='list-number1' start='1'><li>a</li>
<li>b</li>
<li>c</li>
<li>d</li></ol>
```

Both lead to bullets of all "1."s.

**Comment by muxator** [comment] 2018-08-10 08:54
Hi @zorrikon, what version are you using?

Could you give an example of the html document you are trying to import (redacting sensitive informations, if any)?

The current development version has a fix for a similar problem:

https://github.com/ether/etherpad-lite/blob/718b17552421da911b6f29ce427e3a5e84286778/tests/backend/specs/api/pad.js#L18-L22

Looking at your problematic html could help identifying if the issue is indeed the same.

**Comment by zorrikon** [comment] 2018-08-10 16:00
An example HTML is:
`<html><body><ol class='list-number1' start='1'><li>a</li></ol><ol class='list-number1' start='2'><li>b</li></ol><ol class='list-number1' start='3'><li>c</li></ol><ol class='list-number1' start='4'><li>d</li></ol></body></html>`

I'm on the develop branch.

**Comment by muxator** [comment] 2018-08-11 00:33
The bug is present.

Replicated in Etherpad **1.6.5**, **1.6.6** and in current develop (no time for testing other versions).
Since there is not yet a test that replicates it, at the end there is a quick bash script to trigger the bug.

- launch Etherpad
- run the bash script
- open `http://localhost:9001/p/bug-3447`. It will give this output:
![bug-3447](https://user-images.githubusercontent.com/4067621/43986230-a7c1d864-9d0e-11e8-96ab-0c77b251b10c.png)
- the text export will be bad
   ```
   1. a
   1. b
   1. c
   1. d
   ```
- the HTML output will look good when viewed in a browser (probably only because the html markup of a simple `<ol>` is very easy)
   ```html
   <ol class="number"><li>a</li><li>b</li><li>c</li><li>d</li></ol>
   ```

```bash
#!/usr/bin/env bash

set -eu

HOST_PORT="localhost:9001"
APIKEY="<your-api-key>"
PAD_ID="bug-3447"

curl "http://${HOST_PORT}/api/1/createPad" \
    --get \
    --data-urlencode "apikey=${APIKEY}" \
    --data-urlencode "padID=${PAD_ID}"

curl "http://${HOST_PORT}/api/1/setHTML" \
    --get \
    --data-urlencode "apikey=${APIKEY}" \
    --data-urlencode "padID=${PAD_ID}" \
    --data-urlencode "html=<html><body><ol class='list-number1' start='1'><li>a</li></ol><ol class='list-number1' start='2'><li>b</li></ol><ol class='list-number1' start='3'><li>c</li></ol><ol class='list-number1' start='4'><li>d</li></ol></body></html>"

echo -e "\n=====\nEXPORT - ETHERPAD FORMAT"
curl "http://${HOST_PORT}/p/${PAD_ID}/export/etherpad"

echo -e "\n=====\nEXPORT - HTML FORMAT"
curl "http://${HOST_PORT}/p/${PAD_ID}/export/html"

echo -e "\n=====\nEXPORT - TEXT FORMAT"
curl "http://${HOST_PORT}/p/${PAD_ID}/export/txt"
```

**Comment by JohnMcLear** [comment] 2020-03-31 18:46
Test coverage in for this

**Comment by JohnMcLear** [comment] 2020-04-07 13:59
Looks like a cheerio bug, investigating now.

**Comment by JohnMcLear** [comment] 2020-04-07 14:26
Okay so it's ``contentcollector.js`` again and this is related to the work I'm doing in other areas, I'm kinda blocked by other merge requests.  If you look at results

Note: I slightly modified the script so ignore the changes..

```
  lines: [ '*a', '*b', '*c', '*d', '', 'test' ],
  lineAttribs: [ '*0*1*2+1+1', '*0*1*2+1+1', '*0*1*2+1+1', '*0*1*2+1+1', '', '+4' ]
```

Note that the attributes for OL items appears to be present but note that the numbers don't increment.  You would expect to see something like..
```
  lines: [ '*a', '*b', '*c', '*d', '', 'test' ],
  lineAttribs: [ '*0*1*1+1+1', '*0*1*2+1+1', '*0*1*3+1+1', '*0*1*4+1+1', '', '+4' ]
```

Or so, I'm 99% sure this is ``contentcollector.js`` not doing one of these things

1. Properly closing the list
1. Properly numbering the list
1. Properly applying the line attribute

I doubt it's due to the attribute pool because the attributes themselves are wrong.

I will rule them out one by one.

**Comment by JohnMcLear** [comment] 2020-04-07 14:29
Well interesting, it's actually creating a new list for each item, which is obviously not desirable.  So yeah, ``_exitList`` is outdenting and subsequently removing list because it ?doesn't know? that the previous item was also a list item..  Is my guess..  Will look at what ace2_inner gets this right but cc doesn't.

**Comment by JohnMcLear** [comment] 2020-04-07 15:04
Right, fsk this, I'm gonna built a contentcollector test engine or something..

**Comment by JohnMcLear** [comment] 2020-04-08 08:12
Okay contentcollector test engine built and I'm re-familiar with ``contenteditor.js``..  

1. ``contentcollector.js`` does not have logic in for numbered lists start number or number within a list.  It has logic for indentation(level).
1. ``ace2_inner.js`` processes numbered lists.  https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L5220 - With the numbers you see in pad added by CSS.
1. The ``ace2_inner`` so the client processes the changesets required to add numbers to lists..  https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L5244

So the task is to bring that logic into ``contentcollector.js``.

**Closed** 2020-06-06 13:30 UTC
Labels: Bug, Export/Import, Waiting on Testing, http api
