### ISSUE TITLE
Cannot install plugins using npom

### ISSUE THREAD

**Issue by alexfrench** [ether/etherpad-lite#5080] opened 2021-06-17 00:19 UTC
**Describe the bug**
When installing a plugin using npm it creates a new package.json and package-lock.json in the Etherpad root folder (containing only the new plugin information).
Previously installed plugins are deleted from node_modules
_Etherpad will not start._

**To Reproduce**
1. Go to etherpad-lite root folder
2. npm install ep_stats (for example)

Workaround: If I delete package.json and package-lock.json from the root folder Etherpad will start.  However, I am unsure if this is causing other things to break. 

**Expected behavior**
Etherpad should restart correctly

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: MACOS Catalina 10.15.7 (but also happens on AWS Linux 2
 - Node.js version 15.11.0
 - npm version 7.6.3

**Comment by rhansen** [comment] 2021-06-17 05:10
This is a known incompatibility with npm v7.x and Etherpad. Fixing it will take a considerable amount of effort; for progress updates you can subscribe to bug #4714.

The workaround you discovered is the proper workaround. Alternatively you can install plugins from the `/admin/plugins` interface.

Duplicate of #4714

**Closed by rhansen** 2021-06-17 05:10 UTC
