### ISSUE TITLE
Invalid changeset: number of newlines in insert op does not match the charBank

### ISSUE THREAD

**Issue by fab-kaz** [ether/etherpad-lite#5612] opened 2022-09-28 19:03 UTC
Hello,

Some pads can't be loaded anymore. With the message:

`
An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:
Error: Failed assertion: Invalid changeset: number of newlines in insert op does not match the charBank
at https://pad.kaz.bzh/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=b6e6046e at line 9
ErrorId: kMf8DYVKUFzPOK9UxqWn
Unhandled Promise rejection
URL: https://pad.kaz.bzh/p/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
`

SRC_PAD=https://github.com/ether/etherpad-lite.git
PAD_VER="1.8.16"

MariaDB [etherpad_lite_db]> SHOW VARIABLES LIKE 'character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.022 sec)

MariaDB [etherpad_lite_db]> SHOW VARIABLES LIKE 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | latin1_swedish_ci  |
| collation_database   | utf8_bin           |
| collation_server     | utf8mb4_general_ci |
+----------------------+--------------------+
3 rows in set (0.001 sec)

MariaDB [etherpad_lite_db]> SHOW FULL COLUMNS FROM store;
+-------+--------------+-----------+------+-----+---------+-------+---------------------------------+---------+
| Field | Type         | Collation | Null | Key | Default | Extra | Privileges                      | Comment |
+-------+--------------+-----------+------+-----+---------+-------+---------------------------------+---------+
| key   | varchar(100) | utf8_bin  | NO   | PRI | NULL    |       | select,insert,update,references |         |
| value | longtext     | utf8_bin  | NO   |     | NULL    |       | select,insert,update,references |         |
+-------+--------------+-----------+------+-----+---------+-------+---------------------------------+---------+
2 rows in set (0.013 sec)

Should i use utf8mb4 or utf8 instead of latin1 ?

regards,

f.

**Comment by webzwo0i** [comment] 2022-09-28 19:59
Only utf8mb4 is save against encoding issues. In fact I think that ueberdb should warn you on startup if there is a configuration error.
There is a script `bin/checkPad.js` that you can use to further diagnose the problem.

**Comment by webzwo0i** [comment] 2022-09-28 20:09
Fixing the encoding after the problematic strings are introduced in the db won't fix the problem. If the problem is really caused by encoding issues, you problem see strings that contain `????` in the problematic revisions. In the past it helped if we replace `????` with `??`. But to be sure, please post the problematic revision. If it's like `Z:a>4|4+2$\\n????\\n` (insert four characters, two of them are newlines) we see that it tries to insert 6 characters, 2 of them are newlines. The code will look for two newlines in the string `\n???` which fails.

**Comment by fab-kaz** [comment] 2022-12-09 08:25
thank you for the advice webzwo0i ;)

**Closed** 2023-06-21 11:02 UTC
