### ISSUE TITLE
Cursor jumping around when typing

### ISSUE THREAD

**Issue by bertpareyn** [ether/etherpad-lite#2224] opened 2014-08-13 11:18 UTC
From time to time when typing the cursor jumps up a couple of lines. If you continue to type the text isn't actually added where the cursor jumped to, but where the cursor was before it jumped.

A second, possibly related, issue is that on a mobile device, when the etherpad is being edited (or scrolled), the cursor consistently jumps all the way to the top.

**Comment by JohnMcLear** [comment] 2015-01-19 00:04
This is probably an upstream bug.  Apple made a huge mess of contentEditable in iOS8, we have some open upstream bugs so let's wait to see if they are resolved then things should be fixed.

**Comment by sathomas** [comment] 2015-06-09 15:13
FWIW, Just checked the iOS 9 beta and the problem is still present.

**Comment by sathomas** [comment] 2015-06-09 16:53
BTW, CKEditor has also flagged this as an [issue](http://dev.ckeditor.com/ticket/12457)

**Comment by sathomas** [comment] 2015-06-10 14:26
@JohnMcLear Have you filed a bug/issue with webkit or Apple Radar?

**Comment by JohnMcLear** [comment] 2015-06-10 15:25
Afaik there was an ios bug filed in December 2015 but I didn't file it personally and don't have a reference.

**Comment by alexzautke** [comment] 2015-06-10 15:52
I've filed a bug with Apple regarding the issue #2293, but contentEditable divs are still broken :/

**Comment by sathomas** [comment] 2015-06-10 16:47
Since Apple bug reports aren't public (and duplicates help increase the priority), I went ahead and created a simple (no dependencies, no JavaScript) [test case](https://jsfiddle.net/sathomas/rv6ktgL0/8/embedded/result/) and filed a bug report with Apple. It's number 21321546

**Comment by ebarry** [comment] 2016-07-18 13:10
I also experienced this on the etherpad-lite installation on publiclab.org. I've seen the occasional hiccup on our installation over the years, but what happened yesterday was notable. 
i started working on a new pad, and it was fine for about half an hour until i pasted in a link. 
Then the cursor started losing its position. As i typed new letters, the characters would insert several characters to the left of the cursor location. This effect worsened until i stopped typing completely. Then, without touching the keyboard at all, I watched the blinking cursor move itself backwards in a line of text, one character for every blink.
Example http://pad.publiclab.org/p/test

**Comment by lpagliari** [comment] 2016-07-18 13:46
@ebarry This behavior usually happens when a plugin adds a line attribute but doesn't register it using [`aceRegisterBlockElements `](http://etherpad.org/doc/v1.6.0/#index_aceregisterblockelements). Do you have any plugin installed?

I've tried to reproduce the behavior accessing your link on Chrome, but I didn't see the caret moving on any line. Which browser and OS are you using?

**Comment by ebarry** [comment] 2016-07-18 13:52
Thanks @lpagliari !!! I am using Chrome on OSX 10.11.3. It is hard to replicate because the behavior doesn't show up right away, but rather after some sustained typing/editing over some minutes. To answer the plugin question, i'm cc-ing @jywarren

**Comment by jywarren** [comment] 2016-07-18 14:06
No plugins, sorry! I have seen this behavior too after a long period of typing, also in Chrome, but it was a while ago so I don't know if that's helpful except that it's not just Liz's settings.

**Closed** 2020-05-06 19:32 UTC
Labels: Bug, Needs confirmation, Upstream bug
