### ISSUE TITLE
import from OO document

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#3019] opened 2016-07-04 12:15 UTC
When I import a document from OO into etherpad, I have some format issues : 
-I get some empty bullets for a reason I do not understand.
-at random places, 8 spaces are inserted.
-I loose font size.

In the opposite way, after importing a document into etherpad, and then exporting it to a doc, it creates a tab which was not in the initial document.

It is probably an issue since refactoring the imported document needs a lot of time.
Is there any trick to avoid this ? Does this depend on the used format? I actually tried with doc, docx, odt and html, all with the same behaviour.

**Comment by ldidry** [comment] 2019-02-11 19:32
>  -I get some empty bullets for a reason I do not understand.

I think I do understand: when importing an OO file (or whatever format that is not .html or .txt), the file is first converted to HTML, using Abiword or LibreOffice.

Unfortunately, with Libreoffice (Abiword not tested) bullets points are converted to
```
<ul><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 1</p>
	<li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 2</p>
</ul>
```
You can see two new lines, that are unfortunately interpreted by Etherpad as `Enter key`… that creates an empty bullet

Manually converting the OO file with
```
soffice --headless --convert-to html pad.odt
```

Then changing the list to
```
<ul><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 1</p><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 2</p></ul>
```
makes the import working as expected.

I don't know how to deal with this problem:
- removing all new lines in the html file before calling `importHtml.setPadHTML` in `src/node/handler/ImportHandler.js`?
- modifying `importHtml.setPadHTML` to deal with that?

**Comment by PhilLAL** [comment] 2019-02-12 15:07
Thank you @ldidry for investiging this point, and for the suggestions. Hope this will help the developers to solve this issue. :)
Regards.

**Comment by JohnMcLear** [comment] 2020-03-29 11:53
I have made some progress.

``"c:\Program Files\LibreOffice\program\soffice.exe" --headless --convert-to "html:XHTML Writer File:UTF8" testList.odt``

--convert-to "html:XHTML Writer File:UTF8" is doing some stuff, things are better, but not right.  weird bullet formatting..  

It's defo part of the fix but the other part is working contentcollector to drop spans with specific classes.

``Bullet_20_Symbols`` and ``Numbering_20_Symbols`` should be entirely discarded.

**Comment by JohnMcLear** [comment] 2020-03-29 12:11
Fix ready for testing / review.

**Comment by PhilLAL** [comment] 2020-03-29 14:40
I'm not sure to understand: 

## HTML formating

the difference between 
```
<ul><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 1</p>
	<li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 2</p>
</ul>
```
and 
`<ul><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 1</p><li><p style="margin-bottom: 0.28cm; line-height: 108%">Bullet 2</p></ul>`
seems only the breaklines so the rendering should be exactly the same.

## import document into etherpad

I did not succeed converting document using soffice command.
However, when importing a document containing a list with two bullets, in the result, each bullet was preceeded and followed by a bullet, resulting in a five bullets list.

Then it means the etherpad adds additional bullets which should not be there. I am not sure how the HTML breaklines could help.

**Comment by JohnMcLear** [comment] 2020-03-29 15:19
Try my pr

**Comment by JohnMcLear** [comment] 2020-03-29 15:24
sorry about that fast quick response and so the changes uses a different rendering engine plant smell and then also he's popped those the pruning of the name Al Fondo hay smell so you should be good try it please let me know how down

**Comment by PhilLAL** [comment] 2020-03-29 21:22
I used a private instance of framapad.org in which I imported an ODT containing
```
test
- bullet1
- bullet2
```
The result is the following
```
test
- 
- bullet1
- 
- bullet2
- 
```
Is this the information you need? If not, which one do you need?

**Comment by JohnMcLear** [comment] 2020-03-29 21:24
@PhilLAL No.  It's okay, I think I have the issue resolved.

**Comment by muxator** [comment] 2020-03-30 00:49
I was able to replicate @PhilLAL's bug on a recent development version (6fd2bf4472e2), from 5 days ago.

> The result is a pad containing the following
> 
>```
> test
> - 
> - bullet1
> - 
> - bullet2
> - 
>```

Applying #3783 did not solve the issue for me, as the import crashed with no logs.

![Screenshot_20200330_024810](https://user-images.githubusercontent.com/4067621/77865913-015c1f80-7231-11ea-85f8-01e3ab0d15ac.png)

The ODT file is small (9 KB). I can paste it here if needed.

**Comment by JohnMcLear** [comment] 2020-03-30 08:15
I'm able to replicate failure, will fix.  Should be done this am.

**Comment by JohnMcLear** [comment] 2020-04-01 16:20
Note to self: Waiting on help from @muxator for passing the params to CLI.

**Comment by muxator** [comment] 2020-04-08 20:52
#3783 has been merged.

If the problem is fully resolved, close this issue.

**Comment by JohnMcLear** [comment] 2020-04-08 20:57
woop, I'm gonna test edge cases

**Comment by JohnMcLear** [comment] 2020-04-14 09:37
This is fixed.

**Closed by JohnMcLear** 2020-04-14 09:37 UTC
Labels: Bug, Export/Import
