### ISSUE TITLE
Small release update to make Etherpad-Lite runable again

### ISSUE THREAD

**Issue by RubenKelevra** [ether/etherpad-lite#3100] opened 2016-12-19 04:31 UTC
Currently etherpad-lite is just crashing like this if all dependencys are up to date, please release a 1.6.1 as soon as possible because etherpad-lite is not useable at all at the moment:

```
systemd[1]: Started Etherpad-Lite server.
run.sh[14552]: Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
run.sh[14552]: Ensure jQuery is downloaded and up to date...
run.sh[14552]: Clearing minified cache...
run.sh[14552]: Ensure custom css/js files are created...
run.sh[14552]: Started Etherpad...
run.sh[14552]: module.js:472
run.sh[14552]:     throw err;
run.sh[14552]:     ^
run.sh[14552]: Error: Cannot find module 'internal/fs'
run.sh[14552]:     at Function.Module._resolveFilename (module.js:470:15)
run.sh[14552]:     at Function.Module._load (module.js:418:25)
run.sh[14552]:     at Module.require (module.js:498:17)
run.sh[14552]:     at require (internal/module.js:20:19)
run.sh[14552]:     at evalmachine.<anonymous>:17:20
run.sh[14552]:     at Object.<anonymous> (/usr/share/webapps/etherpad-lite/src/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
run.sh[14552]:     at Module._compile (module.js:571:32)
run.sh[14552]:     at Object.Module._extensions..js (module.js:580:10)
run.sh[14552]:     at Module.load (module.js:488:32)
run.sh[14552]:     at tryModuleLoad (module.js:447:12)
systemd[1]: etherpad-lite.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: etherpad-lite.service: Unit entered failed state.

```

**Comment by Gared** [comment] 2016-12-19 23:04
You're right. I'll do a release the next days, but this is a duplicate of #3074

**Closed by Gared** 2016-12-19 23:04 UTC
