### ISSUE TITLE
Etherpad saving constantly, History useless

### ISSUE THREAD

**Issue by desertrold** [ether/etherpad-lite#5099] opened 2021-07-02 16:35 UTC
Hey guys,

we are running Etherpad on debian and have the issue that our pads are constantly saving themselves, about 30.000x each day, every pad, even when there are no changes whatsoever, which as a result renders the history function absolutely useless. I will gladly give more info on our install, just wondered if anyone came across that problem before as it seems pretty arbitrary.

Thank you for your time.

**Comment by webzwo0i** [comment] 2021-07-02 17:13
Afaik no one has reported this, so more information (database, plugins and version) would be helpful.

**Comment by webzwo0i** [comment] 2021-07-02 17:15
If we can't reproduce than it'll be helpful to start node with enabled profiling, so we can identify who's causing this. Which keys are saved repeatedly? (ie when you run with loglevel DEBUG, what are the write queries)

**Comment by zevenom** [comment] 2021-07-06 18:38
Hey webzwo0i,
I'm the admin of this installation desertrold was asking for.
I just wanted to make sure that i will test this issue with a fresh install, and now i have. (we've used an older etherpad version)

So its a fresh installation on Debian10 with mysql. And i can precise the problem furthermore: The pad saves itself after each entry, like every 0.5 seconds. What i can't confirm is that the pad saves itself when nothing is being changed, but i will keep this on the radar. 

Is it possible that i just misconfigured something in the settings.json?

Best regards,

**Comment by webzwo0i** [comment] 2021-07-06 18:46
Under normal activity, ie people are typing in a pad, then the pad state and the changeset is saved, so at least two writes. (Additionally, globalAuthor is also updated and maybe more depending on plugins.)

0.5 seconds is approx. the time clients send changeset when typing. In case you want to be sure, set loglevel to `DEBUG` in settings.json, restart and watch for ueberdb's debug logs. It should log every database query. Then compare two consecutive writes with the same key (ie `pad:a_random_padid` would be the key). They should differ.

**Comment by zevenom** [comment] 2021-07-06 18:49
But is it intended, when you look in the pad history, that a new version is saved every 0.5 seconds? I'll look into the debug logs though, i just can't right now because our pad is being actively used right now :)

**Comment by webzwo0i** [comment] 2021-07-06 19:11
Only when there is activity, then yes, because every changeset/revision is saved.
In case it happens without activity and the interval is 0.5 I'd assume someone has a opened pad and Etherpad is constantly sending a changeset due to misbehaving plugin or some other bug. That's why more information is needed regarding your installation (plugins) and the specific data that is saved in the database.

**Comment by JohnMcLear** [comment] 2021-09-09 10:45
I think it's safe to close this one as I imagine it was a rogue plugin doing something weird.

**Closed by JohnMcLear** 2021-09-09 10:45 UTC
Labels: Needs confirmation, wontfix
