### ISSUE TITLE
How to import/export Word .doc(x) to/from etherpad-lite on Sandstorm

### ISSUE THREAD

**Issue by Reneeeee** [ether/etherpad-lite#3221] opened 2017-07-12 13:15 UTC
Anyone?

**Comment by lpagliari** [comment] 2017-07-12 13:18
@kentonv?

**Comment by kentonv** [comment] 2017-07-12 17:13
The Sandstorm build of Etherpad does not include any docx converter plugins. I did look at enabling the abiword integration some years ago but found that the conversion quality was unacceptably poor. If there's a better plugin these days that people recommend I'd be happy to integrate it.

(Unfortunately Sandstorm's architecture currently doesn't provide any way to install plugins without rebuilding the whole Etherpad package, but as this is a very valuable feature I'm happy to update the official build... if it works.)

**Comment by Reneeeee** [comment] 2017-07-12 17:31
Hi Kentonv (thanks for the CC Ipagliari!),

This indeed would be a valuable feature. But if there's a different editor available offering these options, it'll also work for the Sandstorm fans.

**Comment by kentonv** [comment] 2017-07-12 22:12
Yeah, it's clearly valuable, the problem is that it's hard. :)

**Comment by lpagliari** [comment] 2017-07-13 00:33
Guys, I'll close this issue here, as this is not a feature for etherpad-lite, but for the Sandstorm version of it. Let me know if it needs to be re-opened.

**Closed by lpagliari** 2017-07-13 00:33 UTC

**Comment by kentonv** [comment] 2017-07-13 00:36
Well, I would assume an exporter would be developed as a plugin independently of Sandstorm, and then I'll throw it into the Sandstorm build.

Is there an existing importer/exporter plugin you recommend?

If there isn't a good one currently available then there's nothing I can do on the Sandstorm side.

**Comment by lpagliari** [comment] 2017-07-13 00:54
Oh, sorry, now I got what you mean. On the [plugin list](https://static.etherpad.org/plugins.html) there are some plugins to import .doc(x) files, but I don't see any to export using that format. I've never worked with that feature, so I don't have any recommendations for Sandstorm, sorry.

**Comment by Reneeeee** [comment] 2017-07-13 07:02
Thanks for the feedback @kentonv & @lpagliari !

Is there anyone else aware of an existing/working/suitable plug-in for import/export .doc(x) files? If so, please share.

Thanks!

**Comment by wakerman** [comment] 2017-08-05 08:54
Express hope to provide this import export Word.Doc (x), in addition, can you provide picture upload API?
