### ISSUE TITLE
install on a webserver / hosting server

### ISSUE THREAD

**Issue by learningcentrum** [ether/etherpad-lite#4412] opened 2020-10-13 07:49 UTC
Hoi, a want to install it on a webhosting server with vesta cp

greetings
Martin Doornbos

**Comment by JohnMcLear** [comment] 2020-10-13 13:37
I'm gonna close this because it's not a bug report or issue but more of a question about a specific third party we don't want to spend any time caring about.

**Closed by JohnMcLear** 2020-10-13 13:37 UTC
