### ISSUE TITLE
Error: socket.io connection error: {"type":"TransportError","description":0}

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4424] opened 2020-10-21 12:44 UTC
Introduction of a2554fff2204586c61c9bc33f638ccdf562e0eb8 made a problem in the tests appear.

https://travis-ci.org/github/ether/etherpad-lite/jobs/737680722#L3586
`[2020-10-21 10:58:18.145] [WARN] client - Error: socket.io connection error: {"type":"TransportError","description":0} -- {
  errorId: 'y5bvv2vRcJP3P2OhF2M3',
  msg: 'Error: socket.io connection error: {"type":"TransportError","description":0}',
  url: 'http://localhost:9001/p/FRONTEND_TEST_whfdzDgZSWTDON78O2hH',
  source: 'http://localhost:9001/javascripts/lib/ep_[secure]/static/js/pad.js?callback=require.define&v=89e63f2c',
  linenumber: 225,
  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0'
}`

This seems to happen only on Windows and Firefox before navigating to the timeslider with:

`    var iframe = $('#iframe-container iframe');
    iframe.attr('src', iframe.attr('src')+'/timeslider' + revision);
`

I am not sure if the error goes away, if we go to the timeslider via button, if it's related to https://github.com/socketio/engine.io/pull/601/files because we are closing the socket.io connection or if we have a bug in our code.

It does not seem to have an impact on the reliability of the tests.

**Comment by dcht00** [comment] 2020-10-27 19:09
After updating to the new version yesterday (previous pull ~May), this pops up for a moment when I F5 on any pad.

> An error occurred
> 
> Please press and hold Ctrl and press F5 to reload this page
> 
> If the problem persists, please send this error message to your webmaster:
> ErrorId: xVYcSO7GexJuBT4kTGEt
> URL: https://pad.totalism.org/p/testpad
> UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
> Error: socket.io connection error: {"type":"TransportError","description":400}
> at https://pad.totalism.org/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=8d57b9c2 at line 225
> 

Server log has a WARN showing the same thing.

**Comment by JohnMcLear** [comment] 2020-10-27 19:11
Please follow the issue guidelines.

**Comment by dcht00** [comment] 2020-10-27 19:33
Amended comment, please let me know if there's something else I was missing.

**Comment by JohnMcLear** [comment] 2020-10-27 19:34
So no plugins?

**Comment by dcht00** [comment] 2020-10-27 19:48
None - had ep_cursortrace, but removed due to #4340 .
(btw, CONTRIBUTING.md does not mention listing plugins).

**Comment by JohnMcLear** [comment] 2020-10-27 20:12
@dcht00 sorry our community engagement / new issue stuff afaik does.  It's mostly because a lot of issues are caused by plugins and we don't cater for them here :)  

After updating did you do npm install?  it looks like maybe socketio has gone weird, that or your reverse proxy (if you have one) is doing something weird..

``Uncaught Error: socket.io connection error: {"type":"TransportError","description":0}``

``wss://pad.totalism.org/socket.io/?EIO=3&transport=websocket&sid=UeCwURZgLUxfdhQ4AAAW`` 500 error codes which is 99% of the time a reverse proxy issue.

**Comment by dcht00** [comment] 2020-10-28 00:05
You're right.
The **proxy_wstunnel** apache module needed to be enabled.

```
sudo a2enmod proxy_wstunnel
#besides the more obvious
sudo a2enmod proxy  
sudo a2enmod proxy_http

```
Sorry to hijack this issue :)

It does all oddly seem weirdly browser specific, as Firefox for example sends slightly different WebSockets headers ("Connection" and "Upgrade") than Chrom*.

**Comment by rhansen** [comment] 2020-11-03 19:11
The socket.io errors in the test runs are benign. They have always been there, we just didn't see them until #4420 was merged. I'll see what I can do to eliminate the noise.

**Comment by JohnMcLear** [comment] 2020-11-08 12:34
I can replicate this bug with the following nginx config

```

server {
  listen 80;
  server_name _;
  location /p/one {
    proxy_pass http://127.0.0.1:9001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
  location /p/two {
    proxy_pass http://127.0.0.1:9002;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
  location / {
    proxy_pass http://127.0.0.1:9001;
  }
  location /static/* {
    proxy_pass http://127.0.0.1:9001;
  }

}

```
I get it if I visit ``/p/one``.

Everything seems to be working fine tho..  :?

**Comment by rasos** [comment] 2021-02-04 20:54
We also have nearly every second on a high traffic pad instance socket.io errors since an update to 1.8.7: 

```
[2021-02-04 21:48:16.117] [WARN] client - Uncaught Error: socket.io connection error: {"type":"TransportError","description":400} -- {
  errorId: 'BjZn9AcKJ1ncAXnw6vly',
  type: 'Uncaught exception',
  msg: 'Uncaught Error: socket.io connection error: {"type":"TransportError","description":400}',
  url: 'https://board.net/p/soc414-2',
  source: 'https://paddomain.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=524e9ad3',
  linenumber: 3,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36',
  stack: 'Error: socket.io connection error: {"type":"TransportError","description":400}\n' +
    '    at r.<anonymous> (https://paddomain.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=524e9ad3:3:3889)\n'
 +
    '    at r.emit (https://board.net/socket.io/socket.io.js?v=524e9ad3:6:19839)\n' +
    '    at r.emit (https://board.net/socket.io/socket.io.js?v=524e9ad3:8:9134)\n' +
    '    at r.emitAll (https://board.net/socket.io/socket.io.js?v=524e9ad3:6:22871)\n' +
    '    at r.onerror (https://board.net/socket.io/socket.io.js?v=524e9ad3:6:25651)\n' +
    '    at r.<anonymous> (https://board.net/socket.io/socket.io.js?v=524e9ad3:8:12354)\n' +
    '    at r.emit (https://board.net/socket.io/socket.io.js?v=524e9ad3:6:19839)\n' +
    '    at r.onError (https://board.net/socket.io/socket.io.js?v=524e9ad3:7:5421)\n' +
    '    at o.<anonymous> (https://board.net/socket.io/socket.io.js?v=524e9ad3:7:599)\n' +
    '    at o.r.emit (https://board.net/socket.io/socket.io.js?v=524e9ad3:6:19839)'
}
```

**Closed** 2021-02-11 17:25 UTC
Labels: Minor Bug, tests
