### ISSUE TITLE
IE 11: An error occurred while loading the pad  (Syntax error: static/js/require-kernel.js (line 1))

### ISSUE THREAD

**Issue by m0urs** [ether/etherpad-lite#3500] opened 2018-10-19 14:56 UTC
I am no longer able to open pads with Internet Explorer 11. I get the following error

An error occurred while loading the pad
Syntax error in https://server.acme.com/static/js/require-kernel.js (line 1)

I am running
 
Version number: 1.7.0
Git sha: 20be994I

I see the same issue not only on my installation but also with https://beta.etherpad.org. But with a real line number:

Syntax error in https://beta.etherpad.org/static/js/require-kernel.js (line 226)

Any idea?

P.S. If I am using the official 1.7 version (Git sha: 07bc163), it does work : https://github.com/ether/etherpad-lite/archive/1.7.0.zip

**Comment by kostaspa** [comment] 2018-10-19 18:20
Do you have set the minify option in settings to true? If yes, then set it to false, restart your etherpad from the server and then try again. Maybe this is the cause of the problem.

**Comment by m0urs** [comment] 2018-10-19 20:33
Yes, I have set that to true. Just tried to set it to false, but with the same error. With the official 1.7 version everything works even with minify set to true.

**Comment by muxator** [comment] 2018-10-19 20:47
@m0urs, on monday I will have access to an IE 11 and I will try to reproduce the problem opening a random pad in https://beta.etherpad.org (which is a 4121add1b8b2babfb71363b3deeb254c5aa3f05f, practically the current dev 1.7+ with PR #3496 on top to test the new skin).

Let me check if I understood correctly: can we say we are tackling a regression introduced between 1.7 and current develop (20be994d9b6d) that affects minification on IE 11?

**Comment by m0urs** [comment] 2018-10-20 12:48
Not sure if it is about minification as I think on beta.etherpad.org minification is not enabled, right? At least there I get a real line number for the error whereas I get line 1 on my own site as all seems to be packed in one long line.

On the beta.etherpad.org I get:

An error occurred while loading the pad
Syntax error in https://beta.etherpad.org/static/js/require-kernel.js (line 226)

**Comment by muxator** [comment] 2018-11-28 16:59
Thanks for the ping, did not have time to try it.

**Comment by muxator** [comment] 2018-11-28 18:31
I had to steal a Windows notebook from someone to have a look at it now.

The bug is there, and was introduced in 23eab79946e4 while working for #3488. The reason is that the following snippet uses modern js syntax, not supported by ie11:

https://github.com/ether/etherpad-lite/blob/fe20ffa2029f3ec4687ca015c3bad7b19eba4ea6/src/static/js/pluginfw/hooks.js#L146-L150

Namely, [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) and the [`new Set()` construct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).

At some point ie11 compatibility will be dropped, but ditching it now - for such a small gain - is not wise.

Thanks for the report.

**Comment by ndum** [comment] 2018-11-29 12:38
Thanks for the quick answer and reaction. Is there an ETA when the bug will be fixed?

**Closed** 2018-11-29 22:13 UTC
Labels: Bug, Needs special equipment to test

**Comment by muxator** [comment] 2018-11-29 22:21
Should be fixed now (as of 0ad8291ae778b80da49bc6ea263927c67e53d23d), please have a look and thanks again for finding the regression.

Friendly reminder: it is not guaranteed that ie11 compatibility will continue to be a priority in the following releases, unless there is explicit sponsorship.

**Comment by m0urs** [comment] 2018-11-30 19:57
Does work for me now on https://beta.etherpad.org/ 
Unfortunately cannot test it currently by upgrading my local installation. Need some time but I guess it will then work also, als https://beta.etherpad.org/ did not work before.
