### ISSUE TITLE
New lines in copy/pasted text not preserved. (Observed in Google Chrome)

### ISSUE THREAD

**Issue by aultuser** [ether/etherpad-lite#2625] opened 2015-04-19 18:59 UTC
Hi,

With current revisions of etherpad-lite, the pasting of text which contains new-lines into etherpad, seems to cause those new lines to disappear a few moments after the paste operation is done.

The issue occurs in recent versions of Chrome, on Windows and Mac OS X.  Firefox appears to work correctly.

The issue appears to have been occurring for at least several months, and also still occurs with the latest etherpad github version (obtained and updated using the instructions on the etherpad github readme file, e.g. "git pull origin").

I have not had a chance to check the technical cause, however here are steps for consistently reproducing the issue:

- Open Google Chrome, and navigate to an etherpad.

- Type a few lines of text into the etherpad, separated by empty lines:

```
Lorem Ipsum, sit dolor amet.

Lorem Ipsum, sit dolor amet.

Lorem Ipsum, sit dolor amet.
```

- Select all three lines of text, Copy to the clipboard, Paste in to another text editor (Such as Sublime Text).

- Copy the lines from that editor, and Paste back into etherpad.

The result is that all three lines appear for just a few moments as they should in etherpad, and then all new line characters are removed from between those pasted lines, and the pasted text is then on one single line.

Conversely, if the lines are copied from etherpad, and pasted directly into another or the same etherpad, the new lines are preserved.

The above steps have been tested on both Windows 7 and Mac OS X.

For Windows, the tested environments are these:

- OS:
Windows 7

- Web Browser:
Chrome 42

- A few text editors which work for reproducing the issue:
Notepad
Notepad++ v6.7.5
Sublime Text 3 (3084)

Interestingly, the issue does not occur if Microsoft Word 2007 or 2010 is used as the text editor, instead of Sublime Text or the others in the list above.

For Mac, the tested environments are these:

- OS:
Mac OS X 10.9.x

- Web Browser:
Chrome 42

- A text editor tried which reproduces the issue is:
Sublime Text 3 (3084)

Also interestingly, if the "Notes" application in Mac OS X is used as the intermediate copy/paste target, the new lines are correctly preserved when the text is pasted back into etherpad.

It seems a possible common capability of the editors which work vs. those that do not, is that Microsoft Word and Mac OS X Notes are both capable of copying and pasting HTML, where as Notepad, Sublime Text, etc, only copy and paste plain HTML.

Let me know if any additional details would be helpful.

**Comment by JohnMcLear** [comment] 2015-04-19 19:15
Yeah this is a clipboard compat issue probably related to the white space pre wrap css change I did..  try disable it in dev tools and see if you can replicate the issue?  I'm here to help either way..
----- Reply message -----

**Comment by aultuser** [comment] 2015-04-19 19:22
Hi,

Yes your guess seems correct, disabling the style below appears to correct the issue in Chrome:

```
body.doesWrap>div {
  white-space: pre-wrap;
}
```

e.g. When the style is enabled, the pasting issue is observed, and when it is disabled (unchecked in Dev tools), the paste works correctly.

**Comment by JohnMcLear** [comment] 2015-04-20 10:43
https://github.com/ether/etherpad-lite/blob/develop/src/static/css/iframe_editor.css#L106 -- Looks like we probably need some javascript to enable it for chrome, I thought that was already done tbh but https://github.com/ether/etherpad-lite/blob/develop/src/static/css/iframe_editor.css#L118 probably overrides it.  It's a simple fix in 

https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L614

just target the body.doesWrap > div too in that jQuery select.

**Comment by JohnMcLear** [comment] 2015-04-22 09:43
@aultuser ?

**Comment by JohnMcLear** [comment] 2015-04-23 16:49
Fix is in develop, please test.

**Comment by aultuser** [comment] 2015-04-27 16:24
Hi,

I've just had the chance to check-in on things here at Github, it looks like I owe you one for adding in the update already!  I'd be glad to try it out and make any revisions that might help, as I should have more opportunities to check-in over the next few days.

I should be able to try out your latest changes this afternoon, and write back how things look so you can close this ticket out.

Thanks again.

**Comment by meetshawn** [comment] 2015-04-28 15:23
Fix doesn't work for me, result is still the same.

**Comment by m0urs** [comment] 2015-04-30 08:20
Same here. Still not working in Chome unfortunately :-(

**Comment by JohnMcLear** [comment] 2015-04-30 13:47
Will take a look ASAP

**Comment by JohnMcLear** [comment] 2015-05-01 19:44
Please test.

**Comment by m0urs** [comment] 2015-05-01 19:53
That looks very good to me. Tested both with Chrome and Firefox and both seem to work correctly now. Thanks a lot for that!

**Comment by JohnMcLear** [comment] 2015-05-02 09:46
np

**Closed by JohnMcLear** 2015-05-02 09:46 UTC
Labels: Bug, Waiting on Testing

**Comment by laowantong** [comment] 2016-09-04 11:39
Same problem with Safari on Mac OS X.

**Comment by andreidiaconescu** [comment] 2017-10-05 13:55
hello,

Similar problem reproduces in latest skype for linux:
 - when i copy a text from skype for linux and paste anywhere, in a text file, the new lines are not displayed, braking the formatting of the text;

Any idea what i could about it ?

Thank you.

**Comment by arunbasillal** [comment] 2017-12-04 13:05
Firefox 57.01 still has this issue.

**Comment by Protected** [comment] 2017-12-04 21:33
I just experienced this as well.

**Comment by JohnMcLear** [comment] 2017-12-04 21:35
If someone else can take a look and dig a bit deeper to find the cause of this bug I'd appreciate it.  I'm swamped w/ life right now.
