### ISSUE TITLE
Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by platu** [ether/etherpad-lite#3261] opened 2017-10-07 13:33 UTC
Hello,

On my Debian/testing server Etherpad crashes on startup with the following message 
~~~~~~~~~~
$ ./bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
up to date in 2.643s
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
/usr/local/src/etherpad-lite/src/static/js/pluginfw/plugins.js:127
    flatten(tmp[undefined].dependencies);
                          ^

TypeError: Cannot read property 'dependencies' of undefined
~~~~~~~~~~~

The context is etherpad-lite from git and ->
$ node -v
v8.6.0
$ npm -v
5.4.2

Any hint ?

**Comment by lpagliari** [comment] 2017-10-09 10:58
Hi, @platu , this looks like a duplicate of #3117 . Could you try to run Etherpad version 1.6.0, please? That might fix your issue.

**Comment by platu** [comment] 2017-10-15 15:19
Hello, thanks for this tip but this was not an option for me as I was unable to issue 'npm install ep_etherpad-lite@1.6.0' with success due to missing dependencies.

I can run ./bin/run.sh after moving away the package.json file from the etherpad-lite directory.

I'm not sure to understand where dependencies should stand.
When I run 'npm -g list' the result looks correct but when I run 'npm list' from the etherpad-lite directory I get many many 'npm ERR! extraneous' messages.

**Closed** 2018-04-03 15:06 UTC
