### ISSUE TITLE
fast growing database since update 1.8.0 -> 1.8.7

### ISSUE THREAD

**Issue by rasos** [ether/etherpad-lite#4642] opened 2021-01-10 17:54 UTC
We run a large etherpad instance since many years. After updating from ep 1.8.0 to 1.8.7 the size of the database has nearly doubled the last 12 days. Usage was even less during holiday season (as seen in traffic monitoring). 

3 days ago:

```
# ls -lh /var/lib/mysql/etherpadlite
total 44G
-rw-rw---- 1 mysql mysql   65 Feb 20  2013 db.opt
-rw-rw---- 1 mysql mysql 1.4K Jul 30  2018 store.frm
-rw-rw---- 1 mysql mysql  42G Jan  7 14:28 store.MYD
-rw-rw---- 1 mysql mysql 1.6G Jan  7 14:28 store.MYI
```

today:
 
```
# ls -lh /var/lib/mysql/etherpadlite
total 53G
-rw-rw---- 1 mysql mysql   65 Feb 20  2013 db.opt
-rw-rw---- 1 mysql mysql 1,4K Jul 30  2018 store.frm
-rw-rw---- 1 mysql mysql  51G Jän 10 18:34 store.MYD
-rw-rw---- 1 mysql mysql 1,7G Jän 10 18:34 store.MYI
```

File upload plugin is enabled, but that loads files into the files system (checked).

List of installed plugins

```
tables4
ep_image_upload
ep_toc
headings
slideshow
scrolltoanchor
code_formatting 
message_all
print
loading_message
```

Anybody observing similar grow of database size? Is there any ep tool to observe what is really going on in the database?

**Comment by JohnMcLear** [comment] 2021-01-10 18:01
I'm not seeing it on other instances but that doesn't mean it isn't happening.  Is there any way I can share a call with you to debug?

**Comment by JohnMcLear** [comment] 2021-01-10 18:03
The trick to debugging is getting previous dB entries and looking to see what's new/changed.

I did make one change months ago that stored more atext on every 100 revs instead of 1000 afaik.  It shouldn't have the level of impact you have experienced though....

**Comment by JohnMcLear** [comment] 2021-01-12 14:33
I put a proposed patch in for this which is currently being tested.

**Comment by rasos** [comment] 2021-01-13 04:53
The proposed patch was successful. DB storage usage and traffic is again normal.

    -rw-rw---- 1 mysql mysql 57998901380 Jan 11 20:45 store.MYD
    -rw-rw---- 1 mysql mysql 58046926616 Jan 13 02:27 store.MYD

DB growth was 48025236 MB in 30 hours -> 38 MB per day (and not 1 GB).

**Comment by JohnMcLear** [comment] 2021-01-13 07:08
Can you please uncomment the patched code and see if the growth comes and see how long the growth remains.  

**I think the growth will only be experienced on first time a pad is stored then you shop stop seeing the growth.**

Let's monitor it for 7 days with the code back in please.  If we still keep seeing exponetential growth we can patch else this is expected behavior as your pads were moving to a more stable storage format.

**Comment by rasos** [comment] 2021-01-17 08:00
Uncommented the patch only for one day due to the rapid growth of the DB: nearly 2 GB on a Saturday, which is usually a low traffic day.

```
-rw-rw---- 1 mysql mysql 58167704672 Jan 16 10:35 store.MYD
-rw-rw---- 1 mysql mysql 59844015700 Jan 17 08:48 store.MYD
```

Re-applied the patch by commenting in `Pad.js` line 93

        // newRevData.meta.pool = this.pool;

**Comment by JohnMcLear** [comment] 2021-01-17 09:38
Please leave the code in.  It is important.  I expect to see signific growth for at least a few days but then it should settle down.

**Comment by rasos** [comment] 2021-01-17 10:28
Okay. Re-applied patch. Let's hope that the situation stabilizes in some days.

**Comment by JohnMcLear** [comment] 2021-01-22 20:48
How goes it @rasos  ?

**Comment by rasos** [comment] 2021-01-22 21:05
No end of the growth in sight.

    -rw-rw---- 1 mysql mysql 70855520056 Jan 22 21:56 store.MYD

The DB was growing again 11 GB the last 5 days (20% of its total size). My infrastructure colleagues will kill me tomorrow when hitting again 90% of available LVM space ;-/

![df-pinpoint=1608498024,1611349224](https://user-images.githubusercontent.com/485723/105546341-869f4c00-5cfd-11eb-8e0b-5e73f5b26697.png)

Disc usages shown in percent of available disc space. Applied upgrade on Dec 28th, applied patch on Jan 11, removed patch on Jan 16th. The steps down are increases of the LVM volume.

**Comment by JohnMcLear** [comment] 2021-01-22 21:12
I think give it another 4-5 days and it will have leveled off to it's new point.

**Comment by rasos** [comment] 2021-01-31 15:59
9 days later our instanced consumed another 6,7 GB or 9.5% more space

         -rw-rw---- 1 mysql mysql 77573075324 Jan 31 16:48 store.MYD

However, growth seemed to have stopped 3 days ago after we had to increase disc space once again (which you see as the step down as graphs are percentage)

![df-pinpoint=1609257023,1612108223](https://user-images.githubusercontent.com/485723/106389753-5b93b700-63e5-11eb-922f-5b58af1faef3.png)

So let's hope that the etherpad storage situation now has been consolidated exactly  one month after the update.

**Comment by JohnMcLear** [comment] 2021-01-31 16:02
Yep this is about the behavior we expected from that change :)  This matches our public test instance so **all good** here.

Thanks for reporting and sending graphs and updates etc :)

**Comment by rasos** [comment] 2021-03-26 18:17
Within 2 months our etherpad database was growing further from 77GB to 117GB, that is 52% or 5GB per week. 

```
# df -h /var/lib/mysql/
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        128G  117G  6.2G  95% /var/lib/mysql
```

This is getting really tricky from a hosting POV and causes high costs when backing up the data off site. 

We consider to change the variable backing up the pool every 100 revisions https://github.com/ether/etherpad-lite/commit/d4fcc23fb382aba7c65bc7e5376d2ab9fc6e2f8a to 500. Ideally this parameter becomes a setting.

**Comment by rasos** [comment] 2021-03-29 07:27
We had to comment out again the commit https://github.com/ether/etherpad-lite/commit/d4fcc23fb382aba7c65bc7e5376d2ab9fc6e2f8a as the DB is growing like Corona cases: 4GB in three days.

**Comment by webzwo0i** [comment] 2021-03-29 16:48
I will reopen this for some time, so others see it better.

Can you elaborate which patch you were talking about? (You wrote 
> The proposed patch was successful.
on Jan 13)

Was it https://github.com/ether/etherpad-lite/commit/d4fcc23fb382aba7c65bc7e5376d2ab9fc6e2f8a ? If you are certain that your backup strategy works and you did not mess up encoding than you can revert it. However, before changing the value how often it should store the atext/apool, we would need to check if timeslider still works. (I'm not sure if it's relying on the atext to be present on every 100th revision)

I think it can still be related to either ep_image_upload or ep_tables. Both make use of the pool and can store significant amount of data in it. Please verify in the database, that they don't store significant amount of data. This can happen if you used ep_image_upload for some time with it's default of storing images in the pool, then switched the config to store images on file system. Later, if people on your instance reuse the same pad, they will still have the whole image in the attribute pool.

I would iterate over all the rev%100 entries between a specific time frame (most of the entries have a timestamp), say a day when you experienced the growth) and print their length.

**Comment by rasos** [comment] 2021-03-30 06:56
Yes on Jan 13 we also removed the line of https://github.com/ether/etherpad-lite/commit/d4fcc23fb382aba7c65bc7e5376d2ab9fc6e2f8a and the DB stopped growing. After re-applying the change it stopped again after 3 weeks, but is growing again since one week. Some years ago we had `ep_image_upload` storing images in the database, now they are saved in the local file system. And yes we use `ep_tables`. 

How do I best iterate? I see there is a [Changeset.opIterator(ops)](https://etherpad.org/doc/v1.8.3/#index_changeset_opiterator_ops)  server side hook. Is there a script available that makes use of that?

**Comment by webzwo0i** [comment] 2021-03-30 15:02
probably best to do it directly in the database. Not sure if recent mysql versions are better at json parsing (ideally we would only count the length of the pool key), but maybe the following is enough. It will (hopefully) select revs%100 with a timestamp matching 16104* which is between Jan 11 and Jan 13 2021. In case it does not work I would try to use something like 1610* or even 161*.

```
select store.key, length(store.value) from store 
where store.key like '%:revs:%00' and store.value like '%"timestamp":16104%'
order by length(store.value)+0 desc limit 100 ;
```

FYI: the largest value of all times on my instance is about 350kB. As written above, it includes the pad text, so very large pads impact the result. If you extract the results into a file you could extract the pool with `jq '.meta.pool' filename` and inspect it manually for very large values.

**Comment by rasos** [comment] 2021-04-02 13:41
Such a query on a 120 GB DB is without result after many hours. Furthermore it is blocking the etherpad instance from normal operations as it seems to make the database too busy. I would need to set up some staging environment unless there is an easier way to analyze the situation or delete large images which still reside in the DB.

**Comment by webzwo0i** [comment] 2021-04-02 15:02
OK. I assume your backup cannot be searched with grep etc. either?
Do you have access.logs or info logs from etherpad, that might contain pad ids that were used? We could use them to limit the revs that need to be searched...

**Comment by rasos** [comment] 2021-04-02 18:28
Which backup? Well, I have a daily sql dump. We only have logs of two days due to the high traffic, this may not be sufficient for identifying recently used large pads.

**Comment by webzwo0i** [comment] 2021-04-02 20:49
On 4/2/21 8:29 PM, Roland wrote:
> Which backup? Well, I have a daily sql dump. We only have logs of two 
> days due to the high traffic, this may not be sufficient for identifying 
> recently used large pads.

works for single line inserts (--skip-extended-insert during mysqldump):

```
awk 'match($0,"pad:([^:]+:revs:[0-9]+00).,.*\"pool\\\\\"",result) {print 
result[1]" "length()  }' your-mysqldump-file >revs-and-size.txt
sort -k2n revs-and-size.txt|tail
```

or with timestamps, however not sure if the "timestamp" key always 
preceeds the "pool" key and it might be slower due to multiple .* ...
replace 15995 with a better timestamp

```
awk 
'match($0,"pad:([^:]+:revs:[0-9]+00).,.*\"timestamp\\\\\":15995.*\"pool\\\\\"",result) 
{print result[1]" "length()  }'
```

it will include atext, so there might be false positives, but it should 
be enough to know if we are dealing with huge pools or not

**Closed** 2021-06-09 01:43 UTC
Labels: Needs confirmation, wontfix

**Comment by q2apro** [comment] 2024-03-08 11:41
Maybe related: https://github.com/ether/etherpad-lite/issues/6194
