### ISSUE TITLE
can't ctrl+v (paste) when text cursor is on hyperlink

### ISSUE THREAD

**Issue by dcht00** [ether/etherpad-lite#2775] opened 2015-09-05 14:54 UTC
If your text cursor touches a hyperlink, ctrl+v paste won't work.
(Most often this will be an attempt to paste something in front of a line that is a link.)

Fully updated installs on Centos and Ubuntu show same behaviour.
Checked clients: Firefox on Ubuntu, Chrome on Mac.

**Comment by Gared** [comment] 2015-09-05 19:00
@dcht00 You're right. I can confirm this weird behaviour. Maybe this was included to prevent a bug or something else. Will have a look on it.

**Comment by JohnMcLear** [comment] 2020-03-30 20:29
Confirmed this is still a thing.

**Comment by JohnMcLear** [comment] 2020-03-31 12:07
This is intentional behavior.

```
      // TODO: this breaks pasting strings into URLS when using
      // Control C and Control V -- the Event is never available
      // here.. :(
      if(e.target.a || e.target.localName === "a"){
        e.preventDefault();
      }
```

**Comment by JohnMcLear** [comment] 2020-03-31 12:29
I submitted a PR that fixes/removes this behavior.  I have a feeling it was due to right clicking on link doing something weird where if you right clicked it pasted or something..  Anyway, will let @muxator decide if it's going in or not.

**Comment by muxator** [comment] 2020-04-09 02:18
An historical note: this bug report is from September 2015.

The "buggy" behaviour was introduced on purpose just some months before, on [january](0bd7914c3b40) and [april](14fab9f441bb).

See https://github.com/ether/etherpad-lite/pull/3802#issuecomment-611287982 for a tentative reconstruction of the rationale (basically allowing to open a link via middle click).

Thanks [TortoiseHg](https://tortoisehg.bitbucket.io/) for being so powerful. :)

**Comment by JohnMcLear** [comment] 2020-04-09 07:29
Well done discovering the rationale.

**Comment by muxator** [comment] 2020-04-22 01:37
I've just tested everything from scratch.

Recap:

| Action | Current behaviour<br>(c6cb253f7632, 1.8.3 pre-release) | If #3802 is merged |
| --- | --- | --- |
| **Middle click** on hyperlinks | opens the link in a new tab | **does nothing** |
| **CTRL+V** inside hyperlinks | **does nothing** | pastes the text |

Basically it's a trade off.

Personally I do not use **middle click**, and would prefer CTRL+V to work, so I am ok with merging #3802.

But, since pasting with CTRL+V in hyperlinks was disabled by in 2015 by @JohnMcLear (0bd7914, 14fab9f), I wanted to have his opinion beforehand.

**Comment by JohnMcLear** [comment] 2020-04-22 10:36
We could always make this a user setting?

**Closed** 2020-10-24 15:59 UTC
Labels: Bug, Waiting on Testing
