### ISSUE TITLE
Uncaught Error: Failed assertion: Invalid changeset (checkRep failed) 

### ISSUE THREAD

**Issue by SkoricIT** [ether/etherpad-lite#2107] opened 2014-03-14 11:39 UTC
Hey guys. We are using stable and have the problem that some pads randomly stop working and throw an uncaught error in the console.

```
Uncaught Error: Failed assertion: Invalid changeset (checkRep failed) 
```

Example:

```
https://etherpad.tugraz.at/p/l3tsbet
```

When this happens, the "loading" overlay blocks any action. It's unlikely to be a copy&paste issue because it sometimes happens to entirely handwritten pads. 

An interesting thing is, that the timeslider (opened by appending /timeslider to the url) always works without problems.

```
https://etherpad.tugraz.at/p/l3tsbet/timeslider
```

Right now we are manually fixing the pads by exporting+importing with HTML (losing all changesets). Any idea whats wrong?

**Comment by akosiaris** [comment] 2016-02-17 09:24
Hello, we 've just had this occur. We run 1.5.7, that is the last released version. Backend is a MySQL database. I have no indications as to user actions that might have caused this. 

Pad in question: https://etherpad.wikimedia.org/p/iOS-iteration-planning

Getting the pad data out via the timeslider trick works fine. The pad however will never load. 

Anything in the database can be dumped and provided for debugging if it helps.

**Comment by webzwo0i** [comment] 2016-02-17 09:43
hi, I had this discussion in the morning. 
08:47 < webzwo0i> mutante: i debugged the pad. you normally should not do this, but if you have a database backup (and after making export/etherpad to have a backup of 
                  the pad) you can change three database entries and the pad should be working fine again. the three mysql commands are
08:47 < webzwo0i> mysql> update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS-iteration-planning";
08:47 < webzwo0i> mysql> update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS-iteration-planning:revs:7200";
08:48 < webzwo0i> mysql> update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS-iteration-planning:revs:7300";
08:49 < webzwo0i> can you check if your database is running utf8mb4 charset or utf8?
08:51 < webzwo0i> oha ups please dont apply the mysql-commands. maybe i was a little bit to fast :-) need to check something first
09:08 < webzwo0i> mh nope should be fine, please test... it would be good to know if you ran latest release or something else and which plugins you have enabled
09:47 < webzwo0i> I don't know if you ppl at wikimedia know each other but if you can find out who the user "Brian" is could you ask him what browser he is using? the 
                  reason is I can see what the bug is, but I cannot trigger it in my browser (only manually, but because you ppl are not hostile it was probably not on 
                  purpose)
09:49 < webzwo0i> (so we probably have two bugs, one server-side and one client-side)

**Comment by webzwo0i** [comment] 2016-02-17 09:47
the info I need is if your database is utf8 or utf8mb4
I have extracted the offending changeset, the timeslider will not work around these revisions if you don't also apply ```
mysql> update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS-iteration-planning:revs:7105";
```

**Comment by akosiaris** [comment] 2016-02-17 10:08
@webzwo0i 

Yeah, I noticed that mutante talked to you. I just decided to follow up on the github issue as well. I 'll track down who "Brian" is and what browser they are using for you.

So, the store table is utf8mb4 for quite some time now. It was utf8 but we converted to utf8mb4 due to a different set of problems back in Jun. Specifically on Jun 23, 2015 

https://github.com/ether/etherpad-lite/issues/2522#issuecomment-114441189 ;-)

**Comment by webzwo0i** [comment] 2016-02-17 15:00
no need to find out the user/browser, I can reproduce the bug now. thank you!

Because you are on latest release you need to insert "charset":"utf8mb4" into settings.json inside dbSettings. This is now in settings.json.template. You can check if this is necessary with
```
SHOW VARIABLES LIKE 'character_set%';
SHOW VARIABLES LIKE 'collation%';
```
client (and maybe connection?) should indicate utf8mb4, if not your database-tables itself are capable of storing 4 byte utf8 but the connection between the mysql-client and the database cannot encode them.
This does not repair your old pads. You can however iterate over all your pads and use bin/checkPad.js to get an idea how many and which pads might have similar problems. Depending on the circumstances it can be very easy to repair (although some characters will be broken) like in the above case. If there are lots of broken pads it might make sense to automate this.

The reason these problems are not seen when people actually are writing is that most sites use ueberDB's internal cache for performance. This pure-javascript cache is totally aware of Unicode. As soon as the cache is flushed or etherpad is restarted it needs to get the entries from the database.

**Comment by akosiaris** [comment] 2016-02-17 18:33
I 've repaired the pad as you 've instructed. Interesting to find out that 4 question marks in a row would corrupt a PAD in such a way. And that the corrupting changeset would be so old compared to the tip of the pad. But your explanation makes sense, thanks for that.

I 've updated the configuration with "charset": "utf8mb4" as well.

**Comment by webzwo0i** [comment] 2016-02-18 03:06
I am following the phabricator ticket at wikimedia but don't have an account there so I post it here.

Your second broken pad can also be repaired using:
```
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1120";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1254";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1216";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1108";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1106";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1200";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1300";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1400";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1500";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1600";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1700";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1800";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:1900";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:2000";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:2100";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:2200";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:2300";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives:revs:2400";
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:iOS_Retrospectives";
```
The 4 question marks are the symptom because, iirc, the single bytes in four-byte UTF8 are not valid UTF8. (In UTF8 only the first 127 chars are represented as single bytes, multibyte UTF8 probably uses bytes above 0x7f). So 4 question marks actually represent one 4byte encoded UTF8 string, which represents an code point outside the Basic Multilingual Plane (most probably an emoji :-D). In Javascript those code points would be encoded using UTF16's surrogate pairs, which are 2 16bit-values. 

The checkRep-problem is that in changesets we not only store the characters but also the length of the change. Javascript's length() function, however, counts surrogate pairs as 2, so e.g. an emoji has length 2. When mysql decodes the string of a changeset to question marks than our representation of a changeset is not valid anymore.

Replacing it with two question marks is a hack not a real solution because we have no idea which code point the user entered in the first place (but as long as the value is in ueberDB's cache we could get it out from there).

**Comment by webzwo0i** [comment] 2016-02-18 03:12
it would produce wrong results if someone actually uses four question marks (our length value would indicate 4, if we replace it with 2 question marks we would get a checkRep error in return) so if we would automate a repair script we would need to check if the string length after applying our change is conforming to the "how many chars are added"-value of the changeset.

to circument the problem if someone actually used four question marks and additionally code points like emoji we also need to track the position inside the document where we replace the question marks.

also note that not every checkRep-error is caused by broken encoding

**Comment by akosiaris** [comment] 2016-02-18 13:58
And of course the above worked. AWESOME! I can not thank you enough. I am hoping that with the configuration fix in place this wont happen again. 

I was wondering if the debugging you are doing is manually btw. Getting and comparing the changesets and their lengths one by one manually or if you have some more automated way of doing that. I suppose I can create one of my own anyway, just being curious

**Comment by JohnMcLear** [comment] 2016-02-18 13:58
<3 @webzwo0i Thanks man you are awesome

**Comment by caugner** [comment] 2018-03-09 12:04
The error can easily be reproduced by creating a new pad with a single emoji (e.g. 🐼) and restarting etherpad, see also #3340.

**Comment by caugner** [comment] 2018-03-09 13:04
I wanted to check all pads, so I added a `checkAllPads` tool (see PR #3342).

**Comment by akosiaris** [comment] 2018-03-14 10:35
> The error can easily be reproduced by creating a new pad with a single emoji (e.g. panda_face) and restarting etherpad, see also #3340.

I can not reproduce this, doing exactly what described above. See https://etherpad.wikimedia.org/p/ohmy for an example (yes I 've restarted etherpad multiple times already)

**Comment by RalfJung** [comment] 2018-04-15 12:10
We just had a pad break with this error as well. Curiously, `checkPad,js` does not find any problem, and `repairPad.js` runs to completion without fixing it. Is there any way to determine which revision is at fault?

**Comment by RalfJung** [comment] 2018-04-15 12:38
Indeed doing the "replace `????` by `??`" helped here as well. :) Seems like the last changeset was someone inserting an emoji (it ended in `$????`).

However, I do not understand why this is classified as a "minor bug". This bug leads to total loss of a pad (until someone notices the `/timeslider` thing, which took a week in our case, and even then history is lost).

**Comment by marcelklehr** [comment] 2018-04-15 13:49
Unassigned myself, as it's unlikely I'll get to fixing this. FWIW, this bug appears to be due a limitations of the easysync library, which seems not to support all of utf-8. (UTF-8 may encode one character as multiple bytes, which each add to the length of a string in javascript, even though it's just one character.)

**Comment by marcelklehr** [comment] 2018-04-15 13:51
A possible short-term fix could be to try applying a changeset on the server and testing whether checkRep fails afterwards. If it does, the changeset should be rejected in order to not corrupt the pad.

**Comment by RalfJung** [comment] 2018-04-15 14:12
> FWIW, this bug appears to be due a limitation of the easysync library, which I'm speculating does not to support all of utf-8. (UTF-8 may encode one character as multiple bytes, which each add to the length of a string in javascript, even though it's just one character.)

Actually we have umlauts (äöü) in out pads all the time, which are also multi-byte in UTF-8. Based on what has been said above, I think the issue is actually about UTF-16 -- which, when originally designed, was intended to have exactly 2 bytes per character (codepoint, really), but now that we have more than 2^16 codepoints there are some that need 4 bytes, like emojis. And now `length()` no longer matches the number of codepoints, and everything gets confused.

So maybe a better fix is to outright reject any surrogate pairs (4-byte codepoints)? That would make it impossible to use etherpad with characters from the [supplementary plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Multilingual_Plane), but that's likely broken anyways it seems?

**Comment by RalfJung** [comment] 2019-04-09 11:03
Why did this get closed? To my knowledge, Etherpad still chokes on characters outside the BMP. I recently again had to manually repair a pad that got broken this way.

**Comment by SkoricIT** [comment] 2019-04-09 11:04
I closed it because I opened the Issue 2014 and was not interested in it anymore.

**Comment by RalfJung** [comment] 2019-04-09 11:07
Well, it is still an open problem for others, so I'd appreciate if you could reopen.

**Comment by RalfJung** [comment] 2019-04-09 11:19
Thanks! :)

**Comment by muxator** [comment] 2019-04-09 22:14
The Easysync library describes text (and its legth) in terms of "characters", but it was a minimum viable product from 10 years ago. Nowadays we should probably think in terms of NFC-normalized UTF-8 code points.

**Comment by caugner** [comment] 2019-04-10 00:33
Just wondering, might we be able to solve the problem by storing the ueberdb values as binary blobs rather than in a collated text column?

Currently, if we try to put a byte sequence that is not valid utf8mb4 (think: a changeset that contains part of a multibyte character) into a `utf8mb4` column, there are only two possible outcomes: either the database refuses the input, or client (or server) replace the invalid "characters" or bytes before (e.g. with "?").

By using a binary blob column, the database would no longer care about the byte sequence being invalid utf8mb4, so we might avoid the character replacement. If easysync is as encoding agnostic as I understand, this could work (as long as two users don't insert multibyte characters AB and CD at the same position concurrently and these end up as individual changeset A, C, B, D - in this order -, rendering the merged result invalid utf8mb4).

**Comment by chronikum** [comment] 2019-06-30 21:27
Hi, we are also experiencing this problem on a lot of pads.

**Comment by JohnMcLear** [comment] 2020-03-15 16:40
I'm trying everything and just can't replace this with 🍰, I tried restarts, different database backends (that are properly configured)..

Can anyone provide steps to replicate with our more modern code base?

**Comment by RalfJung** [comment] 2020-03-15 18:53
For me, `replace(`value`,'????','??')` has always worked so far. Hasn't happened for a few months though.

**Comment by JohnMcLear** [comment] 2020-03-15 20:37
I included an updated version of Check Pad Deltas that works, if people can give that a try to see if it helps when experiencing this problem I'd appreciate it.

**Comment by muxator** [comment] 2020-03-21 22:39
I still think the basic problem is that Etherpad data model thinks in terms of "characters" and not normalized UTF-8 code points.

Unless we rework the core library this will never be really solved. Obviously, any mitigation is useful. Just saying that there are no _easy_ solutions that are guaranteed to be 100% correct in my opinion.

**Comment by JohnMcLear** [comment] 2020-03-21 22:49
You'd be surprised  just how many editors (and very popular ones with developers) have a similar experience to Etherpad tho.  Playing around today I had some crazy experiences.

**Comment by muxator** [comment] 2020-03-27 00:52
> I included an updated version of Check Pad Deltas that works, if people can give that a try to see if it helps when experiencing this problem I'd appreciate it.

Pulled in in the master branch with #3717 (14ae2ee95094).

**Comment by gnd** [comment] 2020-05-04 21:26
Hi, we are having a similar issue with one of our Pads. 
@JohnMcLear unfortunately the latest version of checkPadDeltas did not help :/

**Comment by JohnMcLear** [comment] 2020-05-05 05:37
@gnd do you have a public instance?

Can you hit the padId/export/etherpad url and get the .etherpad file?

Are you running latest develop?

What's your database backend?

So many questions, please provide as much details as possible

**Comment by gnd** [comment] 2020-05-05 08:51
@JohnMcLear 
Yes, its a public instance: https://pad.xpub.nl/p/CareCircle
Unfortunately i get a 502 Bad Gateway error trying to get the .etherpad file
We are running latest develop (git pull origin) on nodejs 12.16.3-1nodesource1, with the db backend being 10.3.22-MariaDB-0+deb10u1.

Im available today to help you with any sort of debugging you might want to do. I have already tried the last version of checkPadDeltas, however it just hangs for hours after start. This is the only output it gives: 

`node checkPadDeltas2.js CareCircle
All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad
[2020-05-05 00:04:12.330] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad/settings.json"
[2020-05-05 00:04:12.346] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad/credentials.json"
settings loaded from: /opt/etherpad/settings.json
No credentials file found in /opt/etherpad/credentials.json. Ignoring.
[2020-05-05 00:04:12.369] [INFO] console - Using skin "no-skin" in dir: /opt/etherpad/src/static/skins/no-skin
[2020-05-05 00:04:12.371] [INFO] console - Session key loaded from: /opt/etherpad/SESSIONKEY.txt
[2020-05-05 00:04:12.541] [ERROR] console - table is not configured with charset utf8 -- This may lead to crashes when certain characters are pasted in pads
[2020-05-05 00:04:12.543] [INFO] console - RowDataPacket { character_set_name: 'utf8mb4' } utf8
`

**Comment by JohnMcLear** [comment] 2020-05-05 09:14
Dude, the error is in your log! 
```
[2020-05-05 00:04:12.541] [ERROR] console - table is not configured with charset utf8 -- This may lead to crashes when certain characters are pasted in pads
[2020-05-05 00:04:12.543] [INFO] console - RowDataPacket { character_set_name: 'utf8mb4' } utf8
```

See: https://github.com/ether/etherpad-lite/issues/3959

**Comment by gnd** [comment] 2020-05-05 09:24
@JohnMcLear 
our db has 

> +----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| utf8                       | utf8_general_ci        |
+----------------------------+------------------------+

While the store table has 

> +--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+

So should i convert using 
`ALTER DATABASE `etherpad_lite_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;`

?

**Comment by gnd** [comment] 2020-05-05 11:26
@JohnMcLear 

The misconfiguration was twofold, the database was using utf8 and utf8_general_ci, but also in the settings.json the charset for the database was set as "utf8". Having fixed that all to utf8mb4 still didnt help, and the pad in question doesnt load, and the checkPadDeltas still hangs:

> All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad
> [2020-05-05 13:17:43.443] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad/settings.json"
> [2020-05-05 13:17:43.444] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad/credentials.json"
> settings loaded from: /opt/etherpad/settings.json
> No credentials file found in /opt/etherpad/credentials.json. Ignoring.
> [2020-05-05 13:17:43.463] [INFO] console - Using skin "no-skin" in dir: /opt/etherpad/src/static/skins/no-skin
> [2020-05-05 13:17:43.464] [INFO] console - Session key loaded from: /opt/etherpad/SESSIONKEY.txt

**Comment by JohnMcLear** [comment] 2020-05-05 11:42
@gnd It's a GiGo problem.  Once you have garbage in, it can't be changed.  Now all you know is the problem wont appear in the future!

**Comment by caugner** [comment] 2020-05-05 12:01
> @gnd It's a GiGo problem. Once you have garbage in, it can't be changed. Now all you know is the problem wont appear in the future!

Wouldn't `repairPad.js` be able fix these broken pads?

**Comment by JohnMcLear** [comment] 2020-05-05 12:31
Oh hi @caugner - sadly no, repairPad.js generally sucks and doesn't really work.  https://github.com/ether/etherpad-lite/blob/develop/bin/repairPad.js#L48

The best thing I can suggest is to pull the atext/text out of the pad and bring it into a new pad.  

@gnd I can write you a script to test to try and get the text if you want?  

``bin/extractPadData.js`` with a change to output to stdout might be sufficient here..   2mins I will create an extractPadText.js

**Comment by gnd** [comment] 2020-05-05 12:35
@JohnMcLear  that would be quite helpful indeed )

**Comment by JohnMcLear** [comment] 2020-05-05 12:44
Use ``node bin/extractPadData.js $padid``
Then ``cat test.db | grep \"text\" | grep revNum | tail -1``

The text is the ``val.atext.text`` item, you could json parse this at cli..  I will do that next if you need it..  For now do these commands making sure you replace $padid with your PadID

**Comment by gnd** [comment] 2020-05-05 13:08
The extraction is running, however it is quite slow. In the file CareCicle.db I see the latest line at revs:80, while the script already runs for 20m, and the pad in questions has over 12k revisions..

**Comment by JohnMcLear** [comment] 2020-05-05 16:31
Oh man, that sucks..  I guess it can't build the ``pad`` object after  80 revisions..  It should only take 30 seconds or so for the script to run.

**Comment by JohnMcLear** [comment] 2020-05-06 10:35
the last suggestion would be a big one, to dump the entire db and send it to me and then I can write a script to parse out what you need.  Alternatively I can try to write a script here but there might be some back & forth to get it working that way.

**Comment by gnd** [comment] 2020-05-07 09:13
Hi @JohnMcLear, the script has finally finished. I have no idea why it took so long (almost 40 hrs). Anyway, when looking into it, it seems to me, the whole exercise can be done by selecting the highest revision which is divisible by 100 from the store table and extracting the text from it ? In the future ill do this by hand :) Thanks a lot for your help

**Comment by JohnMcLear** [comment] 2020-05-07 09:43
Exactly this, but I often get told off by our users when I make the assumption they can perform database queries  so I try to avoid it.  I think I know why it took so long btw, are you using MySQL @ Etherpad 1.8.3 ?

**Comment by gnd** [comment] 2020-05-07 09:52
I'm using the latest master from git (not sure which version that is)

**Comment by JohnMcLear** [comment] 2020-05-07 10:00
Assuming MySQL it's a known bug that we're due to have the patch land today.

**Comment by gnd** [comment] 2020-05-07 10:07
yes sorry, its latest MariaDB - 10.3.22-MariaDB

**Comment by gnd** [comment] 2020-05-11 13:34
@JohnMcLear im sorry to spam this ticket, but do you have an issue open for the MySQL patch you mentioned ? I want to see if our performance troubles with etherpad might be resolved by it.. thanks

**Comment by JohnMcLear** [comment] 2020-05-11 14:38
No but just do npm install ueberdb@0.4.9 to fix

**Comment by JohnMcLear** [comment] 2020-07-16 09:55
Btw the new logic for storing additional atext is in so this should be closed but if people experience an issue please do create a new issue and refer to this one.  I want to deal with each individual cause of problem case-by-case with the main goal to create automated logic to restore a pad upon detected corruption in real time.   That's the dream as corruption is inevitable.

**Closed by JohnMcLear** 2020-07-16 09:55 UTC
Labels: Serious Bug, Waiting on Testing

**Comment by pedro-nonfree** [comment] 2020-09-22 00:50
This is a message for people getting to this recently (when upgrading from older versions of etherpad).

Today I upgraded an etherpad service from `1.6.3` to `1.8.6` (what a change!!!!! congratulations to all developers)

I had problems with one pad, the checkers (checkPad, checkAllPads, etc.) failed to detect it (or I don't know how to run node fine, anyway).

I verified the `charset` is `utf8mb4` in my settings.json (saw last version in `settings.json.template`).

```
  "dbType" : "mysql",
  "dbSettings" : {
    "user":     "etherpaduser",
    "host":     "localhost",
    "port":     3306,
    "password": "PASSWORD",
    "database": "etherpad_lite_db",
    "charset":  "utf8mb4"
  },
```

for case https://pad.example.com/p/my-broken-pad I did:

```
mysql
update `store` set `value` = replace(`value`,'????','??') where `key` like "pad:my-broken-pad"
```

restarted etherpad service and it worked again

this solution was above (I put a +1 on previous messages with the solution to help find it), but I wanted to have it more clear

**Comment by JohnMcLear** [comment] 2020-09-22 10:16
I guess one thing we could do here is check for ???? in pad contents and provide a warning that includes a suggested solution.  @pedro-nonfree please could you submit a patch to checkPad.js or something then I'd happily merge that :)

**Comment by InterFelix** [comment] 2021-01-13 14:48
This error occured with one single pad on an instance that was never upgraded and has been pinned to version 1.8.6 since initial deployment today. I fixed the issue, however I don't know what actually helped. First I tried the SQL query, that seemed not to help. Then I set the charset as an env variable on my kubernetes deployment, which redeployed the pod. I can't say if it was the charset or the SQL query in combination with the redeploy, but it's fixed now.
