### ISSUE TITLE
Editing pads in mobile Firefox (Android) is not possible

### ISSUE THREAD

**Issue by sedrubal** [ether/etherpad-lite#2776] opened 2015-09-07 10:57 UTC
#### steps to **reproduce**:

Open an existing pad with Firefox Mobile (on Android) and try to
- add a word in a phrase
- add a headword in a listing
- delete single chars 
#### what you expected to happen:
- I can edit the pad as in a desktop firefox
#### **what actually happened**:
- **The cursor jumps random**
- sometimes, when I type: `hello world` you can see `dlrow olleh`
- sometimes there are **random line breaks**
#### **client OS** and versions:

`Android 5.1`, `Android 4.4.?`
#### **browsers** and versions:

`Firefox 40` and older
#### host os and version:

`Debian Jessie`
- npm and nodejs version: `?`

**Comment by Gared** [comment] 2015-10-22 17:34
Tested it with Firefox 41.0.2 on Cyanogendmod 12.1 (Android 5.1.1) and I can't reproduce your problem. Can someone please retest this bug with Firefox 41.0.2?

**Comment by sedrubal** [comment] 2015-10-22 21:28
Did you try to edit or create a list? Then immediately everything breaks. I tried many versions of fireforx and many android configurations and ROMs and many etherpad versions and I never experienced that this would work... so I'm somehow surprised that it is working for you...

**Comment by JohnMcLear** [comment] 2020-03-26 21:13
This has been fixed for a long time.  Closing.

**Closed by JohnMcLear** 2020-03-26 21:13 UTC
Labels: Minor Bug, editor
