### ISSUE TITLE
 [ERROR] AbsolutePaths - Could not identity Etherpad base path in this linux installation in "/opt/etherpad/etherpad-lite/src/node_modules/ep_etherpad-lite"

### ISSUE THREAD

**Issue by longtaosha** [ether/etherpad-lite#5828] opened 2023-07-14 04:55 UTC
After installed Etherpad, I used "./src/bin/run.sh" to run it. 
********************************************************************************
Starting Etherpad...
[2023-07-14 12:13:24.275] [INFO] settings - All relative paths will be interpreted relative to thbase dir: /opt/etherpad/etherpad-lite
[2023-07-14 12:13:24.293] [INFO] settings - settings loaded from: /opt/etherpad/etherpad-lite/set
[2023-07-14 12:13:24.294] [INFO] settings - No credentials file found in /opt/etherpad/etherpad-lIgnoring.
[2023-07-14 12:13:24.295] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad/etherpad-colibris
[2023-07-14 12:13:24.295] [INFO] settings - Session key loaded from: /opt/etherpad/etherpad-lite/
[2023-07-14 12:13:24.295] [WARN] settings - DirtyDB is used. This is not recommended for productit/etherpad/etherpad-lite/var/dirty.db
[2023-07-14 12:13:24.296] [INFO] settings - Random string used for versioning assets: fcc44d76
[2023-07-14 12:13:24.543] [INFO] server - Starting Etherpad...
[2023-07-14 12:13:24.625] [INFO] plugins - Running npm to get a list of installed plugins...
[2023-07-14 12:13:24.808] [INFO] plugins - npm --version: 6.14.18
[2023-07-14 12:13:28.625] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2023-07-14 12:13:28.627] [INFO] plugins - Loaded 1 plugins
[2023-07-14 12:13:29.240] [INFO] APIHandler - Api key file read from: "/opt/etherpad/etherpad-lit
[2023-07-14 12:13:29.306] [INFO] server - Installed plugins:
[2023-07-14 12:13:29.327] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/
[2023-07-14 12:13:29.328] [INFO] console - Your Etherpad version is 1.9.1 (50c3803)
[2023-07-14 12:13:31.785] [INFO] http - HTTP server listening for connections
[2023-07-14 12:13:31.785] [INFO] console - You can access your Etherpad instance at http://0.0.0.
[2023-07-14 12:13:31.785] [WARN] console - Admin username and password not set in settings.json.  uncomment and edit "users" in settings.json
[2023-07-14 12:13:31.785] [WARN] console - Etherpad is running in Development mode. This mode is ess secure than production mode. You should set the NODE_ENV environment variable to production bNV=production
[2023-07-14 12:13:31.785] [INFO] server - Etherpad is running
less secure than production mode. You should set the NODE_ENV environment variable to production ENV=production
[2023-07-14 12:13:31.785] [INFO] server - Etherpad is running
**************************************************************************
_It seems running okay._ 

But when I visit http:127.0.0.1:9001, I got this error:
**********************************************************************
[2023-07-14 12:13:31.785] [INFO] server - Etherpad is running
[2023-07-14 12:15:05.622] [ERROR] AbsolutePaths - Could not identity Etherpad base path in this linux installation in "/opt/etherpad/etherpad-lite/src/node_modules/ep_etherpad-lite"
[etherpad@winteam-tech-host etherpad-lite]$ less secure than production mode. You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
secure: No such file or directory
than: No such file or directory
production: No such file or directory
mode.: No such file or directory
You: No such file or directory
should: No such file or directory
set: No such file or directory
the: No such file or directory
NODE_ENV: No such file or directory
environment: No such file or directory
variable: No such file or directory
to: No such file or directory
by: No such file or directory
using:: No such file or directory
export: No such file or directory
NODE_ENV=production: No such file or directory
****************************************
I have used older version before in my server, I didn't encounter this kind of error. (The version I'm trying now is 1.9.1 (50c3803))

I've looked at the AbsolutePaths.js, but it seems it's only related to Windows, so any help?

Adam

**Comment by webzwo0i** [comment] 2023-07-14 11:23
Thanks for the report!
We received the same bug report in https://github.com/ether/etherpad-lite/issues/5827 which contains steps to work around the issue in the mean time until it is finally resolved. (e.g. running with ETHERPAD_PRODUCTION=true will probably fix the issue or maybe using the fix-admintests branch, but the branch is probably not ready)

Closing as duplicate. In case you think the problem is different from the one described in #5827 please re-open. In case the problem cannot be fixed with the steps in #5827 please comment in the linked issue.

**Closed by webzwo0i** 2023-07-14 11:23 UTC
