### ISSUE TITLE
Load more messages hangs on a wheel turning

### ISSUE THREAD

**Issue by elpraga** [ether/etherpad-lite#3731] opened 2020-03-18 22:57 UTC
1.8.0 does not show old chat messages. What can I do? I'm using mariadb

**Comment by muxator** [comment] 2020-03-18 23:09
Hi.

Could you give some logs?

**Comment by muxator** [comment] 2020-03-18 23:12
Also, please describe better what you are trying to do, because otherwise it is impossible to replicate your problem.

**Comment by elpraga** [comment] 2020-03-18 23:25
![Screenshot_2020-03-19-00-23-14-540_com android chrome~2](https://user-images.githubusercontent.com/13814570/77016503-18208d80-6978-11ea-8f60-47ff0d8f5ca6.jpg)

**Comment by elpraga** [comment] 2020-03-18 23:25
![Screenshot_2020-03-19-00-23-14-540_com android chrome~2](https://user-images.githubusercontent.com/13814570/77016518-25d61300-6978-11ea-9a56-91ea9c096fe4.jpg)

**Comment by elpraga** [comment] 2020-03-18 23:26
![Screenshot_2020-03-19-00-23-06-173_com android chrome~2](https://user-images.githubusercontent.com/13814570/77016530-34bcc580-6978-11ea-8858-9ad8c7169ae5.jpg)

**Comment by elpraga** [comment] 2020-03-18 23:26
I'll need to find logs first

**Comment by elpraga** [comment] 2020-03-19 09:43
Hello, @muxator !

I'm sorry for yesterday's not-ver-clear start I was just on my phone. 

I've enabled logging now:

```
[2020-03-19 10:38:58.063] [WARN] client - Uncaught TypeError: Cannot read property 'replace' of undefined -- { errorId: 'Z97RLLbGB2blnicWuMzy',
  msg:
   'Uncaught TypeError: Cannot read property \'replace\' of undefined',
  url: 'http://etherpad.tomaskaluza.net/p/madisonhomework',
  linenumber: 44,
  userAgent:
   'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36' }
[2020-03-19 10:38:58.077] [INFO] ueberDB - Flushed 1 values
[2020-03-19 10:38:58.277] [INFO] ueberDB - Flushed 1 values
[2020-03-19 10:38:58.378] [INFO] ueberDB - Flushed 1 values
[2020-03-19 10:39:49.408] [WARN] message - Dropped message, GetChatMessages Message has no start!
[2020-03-19 10:39:49.452] [INFO] ueberDB - Flushed 1 values

```
That is what I get

Could you, please, help me now?  Is there any other information I might provide?

**Comment by elpraga** [comment] 2020-03-19 09:53
This is what happens right after clicking on **Load more messages** 

```
[2020-03-19 10:52:29.576] [WARN] message - Dropped message, GetChatMessages Message has no start!
[2020-03-19 10:52:29.652] [INFO] ueberDB - Flushed 1 values
```

**Comment by elpraga** [comment] 2020-03-19 11:31
@muxator would clearing the chat messages help? Is there a way of doing that? Maybe some MYSQL comman?

**Comment by JohnMcLear** [comment] 2020-03-19 14:43
@elpraga Can you provide exact steps to replicate?   Is this a new problem in 1.8 that was fine in 1.7*?

**Comment by JohnMcLear** [comment] 2020-03-19 14:49
I tried to replicate and can't, the button works fine for me.

the formatting of the button doesn't look great tho

![image](https://user-images.githubusercontent.com/220864/77080115-d54ecc00-69f0-11ea-8931-c8a189889f5c.png)

**Comment by Nicosss** [comment] 2020-03-25 19:36
I confirm the problem with no plugin install and MariaDB database.

When I refresh the tab I've got some logs:
`[INFO] ueberDB - Flushed 2 values`
`[WARN] client - TypeError: t.userId is undefined -- {`
`   errorId: 'rsDg7VZpSbQWmlSxbWEQ',`
`   msg: 'TypeError: t.userId is undefined',`
`   url: 'http://etherpad.xxxx',`
`   linenumber: 44,`
`   userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0'`
` }`
`[INFO] ueberDB - Flushed 1 values
`

`TypeError: t.userId is undefined in http://etherpad.xxxx/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 44`

And if I click on Load more messages button:
`[WARN] message - Dropped message, GetChatMessages Message has no start!`
`[INFO] ueberDB - Flushed 1 values`

After a fresh install there is no error message, only after some use.

**Comment by JohnMcLear** [comment] 2020-03-25 21:53
"After a fresh install there is no error message, only after some use."

So you can create a new database and install and get the same problem?  Or on the same database?

**Comment by Nicosss** [comment] 2020-03-26 12:15
Etherpad Version number: 1.8.0 Git sha: c1c58fa

Yes, a fresh install includes the drop of existing database.

`$ grep -rni "t.userid"`
`src/static/js/collab_client.js:55:  userSet[userId] = initialUserInfo;`
`src/static/js/collab_client.js:507:    userSet[userId] = userInfo;`
`src/static/js/collab_client.js:648:    obj.userInfo = userSet[userId];`
`src/static/js/pad_userlist.js:707:        self.removeGuestPrompt(userId);`
`src/node_modules/npm/node_modules/socks/build/client/socksclient.js:375:        const userId = this._options.proxy.userId || '';`
`src/node_modules/npm/node_modules/socks/build/client/socksclient.js:383:            buff.writeStringNT(userId);`
`src/node_modules/npm/node_modules/socks/build/client/socksclient.js:391:            buff.writeStringNT(userId);`
`src/node_modules/npm/node_modules/socks/build/client/socksclient.js:506:        const userId = this._options.proxy.userId || '';`

Line 44 of pad.js is
`var padutils = require('./pad_utils').padutils;`

**Comment by JohnMcLear** [comment] 2020-03-26 15:09
Is your minify set to ``false`` and ``maxAge`` to ``0`` on this new instance?

Can you replicate the problem if you use DirtyDB instead of MySQL/Maria?

**Comment by Nicosss** [comment] 2020-03-26 19:40
`minify` is set to `true` and `maxAge` to `21600` (Values from original file **settings.json.template**).

I set `minify` to `false` and restart etherpad service:

```
 [WARN] client - TypeError: msg.userId is undefined -- {
    errorId: 'HrQzA2QMTWivLgQl1HYs',
    msg: 'TypeError: msg.userId is undefined',
    url: 'http://etherpad.xxxx',
    linenumber: 5244,
    userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0'
  }
```
```
TypeError: msg.userId is undefined in http://etherpad.xxxx/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 5244
```
Line **5244** of pad.js???

With the previous change I set `maxAge` to `0` and restart etherpad service but I've got the same warning.

If I click on Load more message button I've got the same warning
```
[WARN] message - Dropped message, GetChatMessages Message has no start!
```
I will try with DirtyDB.

**Comment by JohnMcLear** [comment] 2020-03-26 19:47
Try clear your browser cache or use a different browser.

**Comment by muxator** [comment] 2020-03-27 02:03
That error is weird!

I tried on a fresh install, dirtyDB, no plugins, Firefox 74, and when I clicked on "Load more messages" everything worked. :(

**Comment by JohnMcLear** [comment] 2020-03-28 20:55
Closing until we can either 

a) Get access to instance
b) Get Database dump of instance or .etherpad file for pad
c) Get more logs.

Happy to re-open if others have same problem!

**Closed by JohnMcLear** 2020-03-28 20:55 UTC
Labels: Needs confirmation

**Comment by Nicosss** [comment] 2020-03-29 18:04
We are already 2 with a problem using a Mariadb database. Thank you for not closing this issue too quickly. Same problem with dirtydb database in fact.

I tried on a fresh install, dirtyDB, no plugins, Firefox 74. `minify` set to `true` and `maxAge` to `21600`.
`settings.json` is a copy of `settings.json.template`.

```
[2020-03-29 10:00:49.428] [INFO] access - [ENTER] Pad "_JnGETjjJluiDJjfqxXl": Client IYHcOljyrZr04LuVAAAD with IP "192.168.1.254" entered the pad
[2020-03-29 10:00:49.434] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
     at /opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
     at async Promise.all (index 0)
     at async handleClientReady (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
[2020-03-29 10:00:49.434] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `->
[2020-03-29 10:00:49.434] [ERROR] console - (node:315993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-03-29 10:01:44.553] [INFO] access - [LEAVE] Pad "_JnGETjjJluiDJjfqxXl": Author "a.XYeF5Pnt9mQCwVJ1" on client IYHcOljyrZr04LuVAAAD with IP "192.168.1.254" left the pad
[2020-03-29 10:14:14.306] [INFO] access - [ENTER] Pad "_JnGETjjJluiDJjfqxXl": Client 9O1KXLV4N7waoaueAAAE with IP "192.168.1.254" entered the pad
[2020-03-29 11:00:59.381] [INFO] access - [ENTER] Pad "_JnGETjjJluiDJjfqxXl": Client dl9JaSKUauOZdB4rAAAF with IP "192.168.1.254" entered the pad
[2020-03-29 11:00:59.384] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
     at /opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
     at async Promise.all (index 0)
     at async handleClientReady (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
[2020-03-29 11:00:59.384] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `->
[2020-03-29 11:01:55.636] [INFO] access - [LEAVE] Pad "_JnGETjjJluiDJjfqxXl": Author "a.XYeF5Pnt9mQCwVJ1" on client dl9JaSKUauOZdB4rAAAF with IP "192.168.1.254" left the pad
```

Problem occur again with dirtydb database:
```
[2020-03-29 18:07:14.696] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client 9c7lJhmw_I2-Q4qXAAAX with IP "192.168.1.254" entered the pad
[2020-03-29 18:07:14.700] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
     at /opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
     at async Promise.all (index 0)
     at async handleClientReady (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
[2020-03-29 18:07:14.700] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[2020-03-29 18:08:03.461] [WARN] client - TypeError: undefined is not an object (evaluating 't.userId.replace') -- {
   errorId: 'yq4GS7zrGdUbvI8unWRb',
   msg: "TypeError: undefined is not an object (evaluating 't.userId.replace')",
   url: 'https://etherpad.xxxx/p/qhrnDnzlfJIhLjohaXte',
   linenumber: 44,
   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15'
 }
[2020-03-29 18:08:03.533] [WARN] client - TypeError: t.userId is undefined -- {
   errorId: 'aScuAqVhJod9gT0b5Rv5',
   msg: 'TypeError: t.userId is undefined',
   url: 'https://etherpad.xxxx/p/qhrnDnzlfJIhLjohaXte',
   linenumber: 44,
   userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0'
 }
[2020-03-29 18:08:09.753] [INFO] access - [LEAVE] Pad "qhrnDnzlfJIhLjohaXte": Author "a.XYeF5Pnt9mQCwVJ1" on client 9c7lJhmw_I2-Q4qXAAAX with IP "192.168.1.254" left the pad
[2020-03-29 18:08:10.463] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client lgVX9lpywFrDVvswAAAY with IP "192.168.1.254" entered the pad
[2020-03-29 18:08:23.953] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client 333FQod2aMkMyuZqAAAZ with IP "192.168.1.254" entered the pad
[2020-03-29 18:08:23.954] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
     at /opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
     at async Promise.all (index 0)
     at async handleClientReady (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
[2020-03-29 18:08:23.954] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[2020-03-29 18:08:24.257] [WARN] client - TypeError: t.userId is undefined -- {
   errorId: '4ZWoPRYCQB853jfe7rLl',
   msg: 'TypeError: t.userId is undefined',
   url: 'https://etherpad.xxxx/p/qhrnDnzlfJIhLjohaXte',
   linenumber: 44,
   userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0'
 }
[2020-03-29 18:08:54.147] [INFO] access - [LEAVE] Pad "qhrnDnzlfJIhLjohaXte": Author "a.bVyFUhj12RNbu42O" on client 333FQod2aMkMyuZqAAAZ with IP "192.168.1.254" left the pad
[2020-03-29 18:08:55.075] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client TWkOo9S1V58QF0ZTAAAa with IP "192.168.1.254" entered the pad
[2020-03-29 18:09:21.479] [INFO] access - [ENTER] Pad "_JnGETjjJluiDJjfqxXl": Client sI7agGUiSmVnMleAAAAb with IP "192.168.1.254" entered the pad
[2020-03-29 18:09:31.431] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client CsU7R9Qz_bJ_CtbZAAAc with IP "192.168.1.254" entered the pad
[2020-03-29 18:09:31.432] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
     at /opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
     at async Promise.all (index 0)
     at async handleClientReady (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
[2020-03-29 18:09:31.433] [ERROR] console - (node:315993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[2020-03-29 18:09:31.777] [WARN] client - TypeError: t.userId is undefined -- {
   errorId: 'njulw7H4xSHluAVvdPpp',
   msg: 'TypeError: t.userId is undefined',
   url: 'https://etherpad.xxxx/p/qhrnDnzlfJIhLjohaXte',
   linenumber: 44,
   userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0'
 }
[2020-03-29 18:10:01.607] [INFO] access - [LEAVE] Pad "qhrnDnzlfJIhLjohaXte": Author "a.bVyFUhj12RNbu42O" on client CsU7R9Qz_bJ_CtbZAAAc with IP "192.168.1.254" left the pad
[2020-03-29 18:10:02.612] [INFO] access - [ENTER] Pad "qhrnDnzlfJIhLjohaXte": Client GqtMcgsO8OeYW9-EAAAd with IP "192.168.1.254" entered the pad
```
You can find 2 etherpad files with dirtydb database and 1 with MariaDB database.

[etherpad_files.zip](https://github.com/ether/etherpad-lite/files/4399323/etherpad_files.zip)
[etherpad_MariaDB.zip](https://github.com/ether/etherpad-lite/files/4399400/etherpad_MariaDB.zip)
[etherpad_dirty.zip](https://github.com/ether/etherpad-lite/files/4399423/etherpad_dirty.zip)

Be patient because I cannot necessarily respond quickly to requests.

**Comment by JohnMcLear** [comment] 2020-03-29 18:16
I will look into this tonight.

**Comment by JohnMcLear** [comment] 2020-03-29 18:24
I put the dirty.db file in and I can replicate the fault.  So something in your database is not right.

**Comment by JohnMcLear** [comment] 2020-03-29 18:28
On the pad I'm testing that userId is set for every msg

```
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:0","val":{"text":"La base de test dirty.db est créée avec les paramètres de base pour minify et maxAge.","userId":"a.wSPNGJmblc3u2v1u","time":1585375152826}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:1","val":{"text":"Bonjour","userId":"a.XYeF5Pnt9mQCwVJ1","time":1585393023898}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:2","val":{"text":"Bonjour Lilou.","userId":"a.wSPNGJmblc3u2v1u","time":1585393032330}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:3","val":{"text":"Bonjour","userId":"a.SANyl3CI4qoIelaa","time":1585393034272}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:4","val":{"text":"Bonjour Isis.","userId":"a.wSPNGJmblc3u2v1u","time":1585393044529}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:5","val":{"text":"Lilou tu as appris ton emploi du temps par coeur ?","userId":"a.wSPNGJmblc3u2v1u","time":1585393170762}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:6","val":{"text":"Oui","userId":"a.XYeF5Pnt9mQCwVJ1","time":1585393216857}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:7","val":{"text":"Bon allez pause miam-miam !","userId":"a.wSPNGJmblc3u2v1u","time":1585393232372}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:8","val":{"text":"Il faudra tester avec Clara aussi.","userId":"a.wSPNGJmblc3u2v1u","time":1585418747268}}
{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:9","val":{"text":"Je suis là.","userId":"a.XYeF5Pnt9mQCwVJ1","time":1585498056966}}
```

Are you using something for Auth on your set?  I see ``userName`` in a msg...

**Comment by JohnMcLear** [comment] 2020-03-29 18:31
``{"key":"pad:qhrnDnzlfJIhLjohaXte:chat:10","val":{"text":"Tu veux essayer quoi ?","time":1585498083410}}
``
Found this in teh database..  Note the lack of userId...  How did that msg get into the database?  Etherpads logic is: 
```
Pad.prototype.appendChatMessage = function appendChatMessage(text, userId, time) {
  this.chatHead++;
  // save the chat entry in the database
  db.set("pad:" + this.id + ":chat:" + this.chatHead, { "text": text, "userId": userId, "time": time });
  this.saveToDatabase();
};
```

**Comment by Nicosss** [comment] 2020-03-29 18:34
It's a fresh install on a new directory.
Access is via an Apache reverse proxy with authentication. (https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy).
That message come from the chat. Nothing was manually change in the database.

**Comment by JohnMcLear** [comment] 2020-03-29 18:38
This diff solves your problem but I want to know HOW bad data is getting into your Instance..

```
diff --git a/src/static/js/chat.js b/src/static/js/chat.js
index 8cc1d76c..2d046d41 100755
--- a/src/static/js/chat.js
+++ b/src/static/js/chat.js
@@ -132,6 +132,7 @@ var chat = (function()
       var timeStr = hours + ":" + minutes;

       //create the authorclass
+      if(!msg.userId) msg.userId = "Unknown";
       var authorClass = "author-" + msg.userId.replace(/[^a-y0-9]/g, function(c)
       {
         if (c == ".") return "-";

```

It could be that historically a bad plugin has inserted bad data into the database.

**Comment by JohnMcLear** [comment] 2020-03-29 18:39
If etherpad wrote that data to your database it would include ``userId:`` (either populated or ``false``) but never non existent...

**Comment by JohnMcLear** [comment] 2020-03-29 18:43
I sent a PR with a patch that can go into develop but I'm 99% sure Etherpad isn't the cause of the problem but there is some other code making a mess.  Either way, feel free to checkout my branch and let me know if it's working :)

**Comment by Nicosss** [comment] 2020-03-29 18:46
In my last attempts with dirytydb and MariaDB databases I did not install any plugin. Only text was paste in the Pad.
I will try your patch with a new fresh install  and keep you informed. Thank you for your time.

**Comment by JohnMcLear** [comment] 2020-03-29 18:59
Remember to checkout my branch when you test.

**Comment by JohnMcLear** [comment] 2020-03-29 18:59
Remember to checkout my branch when you test.

**Comment by Nicosss** [comment] 2020-03-29 19:09
Oka, all entries with no `userId` are now identified with anonyme user with my latest databases. But I can't explain why some `userId` were lost.
I'm now waiting for the "Load more messages" button" to appear.

**Comment by Nicosss** [comment] 2020-03-29 19:15
I’m wondering if this isn’t related to the iPad connection. I’m waiting for an iPad user to log in.

**Comment by JohnMcLear** [comment] 2020-03-29 19:19
Etherpad always stores the userId, afaik it's impossible for it not to..  But if you can find the cause I'm 100% keen to hear your story :D



-----Original message-----

**Comment by muxator** [comment] 2020-03-30 20:20
Merged John's patch (#3785), that makes the front end code more tolerant of malformed messages coming from the server.

Since @Nicosss problem happens with a fresh DB and no plugins, this can well be a bug in Etherpad. Hopefully the main usability issue is sidestepped, and we can fix the underlying problem when we find it.

**Comment by lesion** [comment] 2020-04-01 13:23
I think I have a related issue here:

![Screenshot from 2020-04-01 15-17-04](https://user-images.githubusercontent.com/504700/78141523-e5709d80-742b-11ea-95e2-858905f049d5.

only in few pads i see this screen for few milliseconds before the page loads.

I've messages in console coming from server of type `COLLABROOM` > `CHAT_MESSAGES` with some messages without any userId property:

```
7: Object { text: "redacted", time: 1585502611034, userName: null }
8: Object { text: "redacted", time: 1585503125296, userName: null }
```

I think the patch fix it but I cannot try in production. hope it helps

**Comment by mrtopf** [comment] 2020-04-21 15:43
just fyi: We have this now too on a 1 week old install at https://yopad.eu in some pads. It's a heavily used instance though and we have some plugins installed. 

It seems to be the same error message when loading a pad: 

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.addMessage (pad.js?callback=require.define:44)
    at Object.u [as handleMessageFromServer] (pad.js?callback=require.define:29)
    at r.<anonymous> (pad.js?callback=require.define:3)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
```

Some messages have a userId, others do not and the userName is `null` in this case:

```
4: {text: ".....", time: 1587121249936, userName: null}
```

If there is anything I can help to solve the underlying issue please let me know! 
(for this server I will wait until the next release though).

**Comment by JohnMcLear** [comment] 2020-04-21 16:59
@mrtopf can I get a link to some pads w/ teh problem please?  Also this is an old version of etherpad, please pull latest develop branch :)  Thanks!

**Comment by yorickreum** [comment] 2020-05-09 14:06
Any news here? We also ran into this issue. We are investigating it at the moment…

**Comment by JohnMcLear** [comment] 2020-05-09 14:47
No news from me I didn't have enough info to work with

**Comment by yorickreum** [comment] 2020-05-09 14:50
We encountered this issue while using Etherpads included into a Moodle installation. Is anyone else using Moodle here?
