### ISSUE TITLE
Plugin incompatibilities since ep 1.8.0

### ISSUE THREAD

**Issue by fnetX** [ether/etherpad-lite#3696] opened 2020-02-12 17:08 UTC
Hey there, by the end of December I installed Etherpad 1.8.0 on my production server. By then, some of my plugins stopped working. I thought it might be some config or installation issue with the instance.
Now I got the time to install a plain ep 1.8.0, but still these plugins seem broken:
- ep_activepads
- ep_adminpads
- ep_set_title_on_pad
... there might be more. Some users also reported the server more frequently forgetting about their author names and colours - and I think I noticed that as well.

I know that these plugins are most likely no longer maintained by anyone, but it'd be very nice to prevent breaking changes since the Etherpad ecosystem is close to frozen.  

Are you interested in hunting these issues down? I'm not a node developer, I don't have any experience with this software (apart from knowing that I find it awful to maintain ...), but I'd gladly assist you in finding as many information as possible. 

My setup is: 
Etherpad 1.8.0 from git
Debian Linux 9 / Stretch
port 9001 with lighttpd proxy (reproducible without it)
MySQL (MariaDB) database

On production server: 
Node version: v10.18.1
git branch: master
Installed plugins: `ep_activepads ep_adminpads ep_better_pdf_export ep_chatdate ep_cursortrace ep_delete_empty_pads ep_etherpad-lite ep_footer ep_headings2 ep_message_all ep_set_title_on_pad`

On development server:
Node version: v8.11.1
git branch: develop
Installed plugins: `ep_activepads  ep_adminpads`

Please let me know if I can help you with any further information. Thank you!

**Comment by JohnMcLear** [comment] 2020-02-15 00:11
ep_real_time_chat was broken at some point, I'm working on debug.

**Comment by JohnMcLear** [comment] 2020-02-15 10:49
authorManager.getAuthorName is broken.  Causes failures for me.

**Comment by JohnMcLear** [comment] 2020-02-15 11:01
Okay the problem is caused by a change to async without handling non async functions.

https://github.com/ether/etherpad-lite/commit/6d1b6b2796a90911a3ed3ec28a70bbb2cd91b814#diff-fd5248dbd5a8ffe260b41a91d245c48e is to blame.

@raybellis being the author

I will leave for @muxator to handle, I can fix ep_real_time_chat but I doubt I can find time to fix all plugins this breaks.

**Comment by JohnMcLear** [comment] 2020-02-15 11:04
https://github.com/JohnMcLear/ep_real_time_chat/commit/4e1ccd906e717dd654b6884af60d78b6a5d98e84 is the fix I put into ep_real_time_chat

**Comment by muxator** [comment] 2020-02-18 22:51
> [JohnMcLear/ep_real_time_chat@4e1ccd9](https://github.com/JohnMcLear/ep_real_time_chat/commit/4e1ccd906e717dd654b6884af60d78b6a5d98e84) is the fix I put into ep_real_time_chat

@JohnMcLear, apart from the possible backward incompatibility introduced by https://github.com/ether/etherpad-lite/commit/6d1b6b2796a90911a3ed3ec28a70bbb2cd91b814#diff-fd5248dbd5a8ffe260b41a91d245c48e, (landed in **1.8.0**), does https://github.com/JohnMcLear/ep_real_time_chat/commit/4e1ccd906e717dd654b6884af60d78b6a5d98e84 make the plugin work again?

**Comment by FredMa01** [comment] 2020-03-08 19:51
And for ep_adminpads, is there an issue ?

Fred

**Comment by FredMa01** [comment] 2020-03-28 14:19
To delete pads, I try : node bin/deletePad.js test (cf https://github.com/ether/etherpad-lite/wiki/Getting-to-know-the-tools-in-bin) but it doesn't work, I have this error  
DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

I don't find solution to delete revisions of a pad except delete and reinstall Mysql base ;(

Fred

**Comment by JohnMcLear** [comment] 2020-03-28 14:23
Try pull latest develop and test again, pretty sure you are a few commits behind :)



If it still errors lemme know as I can prolly fix it.







-----Original message-----

**Comment by JohnMcLear** [comment] 2020-03-28 14:25
Also, what database are you running?  Afaik dirty is append only so db.remove wouldn't work?







-----Original message-----

**Comment by FredMa01** [comment] 2020-03-28 14:35
I am using MySQL database.
To pull lastest develop must I do :
git clone --branch develop git://github.com/ether/etherpad-lite.git etherpad
instead of :
git clone --branch master git://github.com/ether/etherpad-lite.git etherpad ?

**Comment by muxator** [comment] 2020-03-28 15:35
> DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

I think this is due to #3472, and the problem was in the mysql driver in ueberdb. At the time it was hard to fix, because ueberDB was not under our direct control.

Now it is, and I am pretty confident that latest ueberDB pulls in an updated mysql library.

To get it, you'll have to use the development version if Etherpad (currently 7a999ee39859).

> To pull lastest develop must I do:
> git clone --branch develop git://github.com/ether/etherpad-lite.git etherpad

That's right (I suppose you are starting from scratchm cloning again the repo. There are "smarter" solutions, but clonig again is guaranteed to work)

**Comment by FredMa01** [comment] 2020-03-28 16:15
I haven't done the cloning because etherpad is in production ;)
A smarter solution is a git command like this : 'git pull origin develop' ?
And to come back to master 'git pull origin master' ?

npm ls mysql gives me : mysql@2.17.1
Fred

**Comment by JohnMcLear** [comment] 2020-03-28 18:07
Closing this issue because

1) Most plugins been fixed
2) DeletePads is working fine.

**Closed by JohnMcLear** 2020-03-28 18:07 UTC
Labels: Bug, async-migration

**Comment by JohnMcLear** [comment] 2020-03-28 18:13
FWIW I can replicate the deletepads bug.  It's specific to MySQL and exists on latest develop.

**Comment by FredMa01** [comment] 2020-03-30 13:26
I'm not clear enough with github to know how to do this but allowing the deletepads plugin to work with etherpad-lite 1.8 and MySQL would be really good.

**Comment by JohnMcLear** [comment] 2020-03-30 13:31
@FredMa01
  1. Go to https://github.com/ether/etherpad-lite/issues
  1. Search to see if the issue already exists, if not, 
     1. Create new issue and include as much detail as possible :)
