### ISSUE TITLE
Export from Timeslider-Version doesn't work

### ISSUE THREAD

**Issue by nesges** [ether/etherpad-lite#5714] opened 2023-05-29 13:45 UTC
**Describe the bug**
Export from a version in timeslider does run into an internal server error (`Not a changeset: null` at /opt/etherpad-lite/src/static/js/Changeset.js:51:13). Export from the main Version does work.

**To Reproduce**
1. Go to ['Sandkasten'](https://pad.pnpde.social/p/Sandkasten/timeslider#32)
2. Click on 'Diese Version exportieren' and "Textdatei"
3. See error

Or:
1. `curl https://pad.pnpde.social/p/Sandkasten/32/export/txt`
2. 
```
May 29 15:31:20 oghma run.sh[654707]: #033[31m[2023-05-29 15:31:20.340] [ERROR] console - #033[39mError: Not a changeset: null
May 29 15:31:20 oghma run.sh[654707]:     at error (/opt/etherpad-lite/src/static/js/Changeset.js:51:13)
May 29 15:31:20 oghma run.sh[654707]:     at Object.exports.unpack (/opt/etherpad-lite/src/static/js/Changeset.js:1069:44)
May 29 15:31:20 oghma run.sh[654707]:     at Object.exports.applyToText (/opt/etherpad-lite/src/static/js/Changeset.js:1111:28)
May 29 15:31:20 oghma run.sh[654707]:     at Object.exports.applyToAText (/opt/etherpad-lite/src/static/js/Changeset.js:1766:17)
May 29 15:31:20 oghma run.sh[654707]:     at Pad.getInternalRevisionAText (/opt/etherpad-lite/src/node/db/Pad.js:182:52)
May 29 15:31:20 oghma run.sh[654707]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
May 29 15:31:20 oghma run.sh[654707]:     at async getPadTXT (/opt/etherpad-lite/src/node/utils/ExportTxt.js:33:13)
May 29 15:31:20 oghma run.sh[654707]:     at async Object.exports.doExport (/opt/etherpad-lite/src/node/handler/ExportHandler.js:62:17)
May 29 15:31:20 oghma run.sh[654707]:     at async /opt/etherpad-lite/src/node/hooks/express/importexport.js:63:9
```
PS: Plugins are disabled for now, but I same point I'll have to reactivate them. The above was testet without active plugins

**Expected behavior**
Download Pad-Content as a textfile

**Screenshots**

![image](https://github.com/ether/etherpad-lite/assets/1583898/17868874-3455-43f0-878d-3501d0414bd4)

![image](https://github.com/ether/etherpad-lite/assets/1583898/e5937ecb-ba9d-41aa-a058-8fbac077cd66)

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: Ubuntu 22.04
 - Node.js version (`node --version`): v16.20.0
 - npm version (`npm --version`): 8.19.4
 - Is the server free of plugins: yes 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113.0.5672.127

**Comment by nesges** [comment] 2023-06-18 21:05
Reactivated the plugins. Let me know, if you need them deactivated to debug this issue

**Comment by JohnMcLear** [comment] 2023-06-21 11:09
We'd need steps to replicate, please provide and I can re-open.

**Comment by nesges** [comment] 2023-06-21 17:16
> We'd need steps to replicate, please provide and I can re-open.

The steps described above still apply. I just rechecked

**Comment by nesges** [comment] 2023-06-24 15:19
Someone just crashed our installation over and over again by repeatedly polling on /socket.io which led to this error:
```
un 21 13:09:08 oghma run.sh[486887]: [2023-06-21 13:09:08.123] [ERROR] console - Error: Not a changeset: null
Jun 21 13:09:08 oghma run.sh[486887]:     at error (/opt/etherpad-lite/src/static/js/Changeset.js:51:13)
Jun 21 13:09:08 oghma run.sh[486887]:     at Object.exports.unpack (/opt/etherpad-lite/src/static/js/Changeset.js:1069:44)
Jun 21 13:09:08 oghma run.sh[486887]:     at Object.exports.applyToText (/opt/etherpad-lite/src/static/js/Changeset.js:1111:28)
Jun 21 13:09:08 oghma run.sh[486887]:     at Object.exports.applyToAText (/opt/etherpad-lite/src/static/js/Changeset.js:1766:17)
Jun 21 13:09:08 oghma run.sh[486887]:     at Pad.getInternalRevisionAText (/opt/etherpad-lite/src/node/db/Pad.js:182:52)
Jun 21 13:09:08 oghma run.sh[486887]:     at runMicrotasks (<anonymous>)
Jun 21 13:09:08 oghma run.sh[486887]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jun 21 13:09:08 oghma run.sh[486887]:     at async getPadTXT (/opt/etherpad-lite/src/node/utils/ExportTxt.js:33:13)
Jun 21 13:09:08 oghma run.sh[486887]:     at async Object.exports.doExport (/opt/etherpad-lite/src/node/handler/ExportHandler.js:62:17)
Jun 21 13:09:08 oghma run.sh[486887]:     at async /opt/etherpad-lite/src/node/hooks/express/importexport.js:63:9
```

Just leaving this here, because it seems to be related to this issue. I blocked the attackers IP for now

**Comment by webzwo0i** [comment] 2023-06-24 17:06
We have several problems here:
Are you sure you're running 1.8.18? I cannot reproduce your problem on 1.8.18, but I can on latest 1.9 (or develop branch).

Steps to rperoduce:
- fetch export/etherpad of the above pad
- import it
- run curl on /32/export/txt

It does not crash the instance, but prints the above stack trace. @nesges Is this correct? Because you said it crashes your instance.

One problem is https://github.com/ether/etherpad-lite/issues/5765 (stack trace sent to the user's client)

Another problem is that ueberdb seems to fetch 10 times the revision that is requested! (e.g. when requesting /32/export/txt it get/getSubs up to 320 revisions!), https://github.com/ether/ueberDB/issues/353

**Comment by webzwo0i** [comment] 2023-06-24 18:17
I found the reason and I'm working on a solution, as there might be more call sites that expose the same bug.

**Comment by JohnMcLear** [comment] 2023-06-26 18:55
Fixed with https://github.com/ether/etherpad-lite/pull/5772

**Closed by JohnMcLear** 2023-06-26 18:55 UTC

**Comment by nesges** [comment] 2023-06-27 07:44
Just updated to 1.9.1 and it works like a charm. Thanks y'all! :-)
