### ISSUE TITLE
Setting line attribute on other author's line

### ISSUE THREAD

**Issue by g-borgulya** [ether/etherpad-lite#2921] opened 2016-02-27 15:23 UTC
If a user opens a pad containing text from another author (eg. pad created by copypad),
and a line that has already line attributes get's a new line attribute with the command _AttributeManager.setAttributeOnLine_ then etherpad disconnects, saying:

```
 Error: Can't apply USER_CHANGES, because Trying to submit changes as another author in changeset
```

Which seems to be true as the changeset's author differs from the current user's ID.

I have a guess how to fix this problem but as I'm not too deep in the etherpad source so I rather just put it here:

```
setAttributeOnLine: function(lineNum, attributeName, attributeValue){
...
if(hasMarker){
  ChangesetUtils.buildKeepRange(this.rep, builder, loc, (loc = [lineNum, 1]), [
    [attributeName, attributeValue]
  ], this.rep.apool);
}
...
```

at this point I guess the ['author', this.author] should also be inserted in the changeset data.

I'm not sure about this, please consider.

**Comment by webzwo0i** [comment] 2016-02-29 13:41
hey, thanks for reporting this.

I have difficulties reproducing your problem. I created a pad and edited from two different authors. Then I called copyPad via API, deleted my cookies, reconnect and try to edit one of the lines that where already there.

Can you elaborate on what you did to trigger this bug? (or provide an etherpad-export file that shows this bug after it is imported&copied to a new location)

thank you

**Comment by webzwo0i** [comment] 2016-02-29 13:43
I suppose you have a list in the pad because setAttributeOnLine is only called via setLineListType in ace2_inner.js but even with a list I cannot reproduce this right now

**Comment by lpagliari** [comment] 2016-03-15 17:40
@g-borgulya I get the same error message when removing a line attribute with a different user. Are you sure the error message is because of `AttributeManager.setAttributeOnLine`, and not because of `AttributeManager.removeAttributeOnLine`?

If anyone wants to reproduce the issue, try to change any of the lines of this pad to style "Normal": https://beta.etherpad.org/p/LFP_badChangeset

**Comment by lpagliari** [comment] 2016-03-15 17:46
BTW, I'll submit a PR for the issue with `AttributeManager.removeAttributeOnLine` as soon as I can...

**Comment by g-borgulya** [comment] 2016-03-15 21:42
I've been experimenting with a plugin that I wrote from scratch so it's not that easy for me to provide a step-by-step. But the basic concept is that I try to highlight lines of pads based on some data coming from a different server.
So after fetching the data from the remote server I tried to call setAttributeOnLine for the relevant lines. And at this point I experienced that in some cases it only worked for the user who wrote the original pad content because of the issue mentioned above. With the fix I proposed above it started to work correctly.

I didn't try using removeAttributeOnLine so I have no info about that.
Let me know if I can provide you with some more info.

**Comment by lpagliari** [comment] 2016-03-15 22:10
I've tried to reproduce the issue adding different line attributes with different authors, but I didn't get the error you're getting. Do you have any other plugin installed on your Etherpad instance that I could use to try to reproduce the issue?

The solution you're suggesting looks correct to me (it is the same I used to fix the issue with `removeAttributeOnLine`), I'm just puzzled why you're getting the error when using `setAttributeOnLine `...

**Comment by g-borgulya** [comment] 2016-03-19 19:37
I'm only using the plugin I wrote myself, and I can't be sure that it's 100% correct and uses every hook/method as intended. This plugin of mine is too complicated and special for simply sharing here. If I manage to find a simple to demonstrate the problem, I'm going to share that.

Although I don't understand the etherpad code deep enough, this solution seems to make sense for me as currently

1. there's no check for the author when the attribute is being changed
2. so it's taking the original author of the attribute, (THIS IS THE PROBLEM)
3. which can differ from the current author some cases,
4. which causes a bad changeset.

If we submit the change specifying the correct author then there's no problem at all.

**Comment by JohnMcLear** [comment] 2016-03-26 14:18
Please test latest develop and close this if it is fixed.

**Comment by JohnMcLear** [comment] 2016-05-04 20:51
Bump @g-borgulya

**Closed** 2018-04-03 17:15 UTC
