### ISSUE TITLE
Big nested lists are having performance issues on Firefox

### ISSUE THREAD

**Issue by simong** [ether/etherpad-lite#2297] opened 2014-11-06 09:39 UTC
We're seeing some slowness in Firefox when dealing with big nested lists [1] in the following situations:
- Deleting a character (it's very obvious when trying to delete multiple characters by hitting backspace quickly a couple of times)
- Changing the indentation of a list item

Running a Javascript profiler seems to confirm there is an issue present:
![http://cl.ly/image/0E0x2G3y0G0Q/Screen%20Shot%202014-11-05%20at%2017.45.44.png](http://cl.ly/image/0E0x2G3y0G0Q/Screen%20Shot%202014-11-05%20at%2017.45.44.png)
(Those black squares each correspond to trying to remove a character)

From some naive inspection of ace2_inner, it looks like it's iterating over all the items in list when deleting a single character. This seems a bit overkill?

[1] The length and depth of the list will obviously depend on how powerful your machine is, but on my macbook pro (2.7GHz quadcore) I can start seeing issues with about a 100 items nested to up to 4 levels deep. I am not seeing this issue in Chrome or Safari.

**Comment by simong** [comment] 2015-05-07 15:56
The chrome dev tools seem to have improved somewhat and allow for better debugging.
![](https://cldup.com/nmlSebagxj.png)

It seems like there are is a ton of DOM accessing going on which is causing the slowdown

**Comment by simong** [comment] 2015-05-07 16:01
So for anyone looking at this in the future, it seems like all this activity is going on in:
src/static/js/ace2_inner.js
 + insertDomLines in the `_.each(infoStructs, function(info)` block

**Comment by JohnMcLear** [comment] 2020-04-06 17:55
I found a reproducible case.

1. Create a pad with 50 lines all that are OL.
1. Select lines 1->50, click indent.  FF will freeze for a second

Do the same operation in Chrome, it will be slow.

Do the same operation in Edge, it will be blazing fast...    Nah just kidding, Edge is obviously the slowest :D

**Comment by JohnMcLear** [comment] 2020-04-06 18:20
So this is how it works AFAICT

Let's say I have a list with 10 items.  Originally it's

```
1.
2.
...
```

The first indentation happens on the first line, so it becomes 

```
0.1.
0.2.
```
To do that it has to go over each item then it also checks the next line to see if that's a number, so it redoes that one too..

So let's say we have 10 items, and n is number of operations it's like this..

1. n*10
2. n*9
3. n*8
4. n*7
5. n*6
...

So total ops for a list of 10 is 10+9+8+7+6+5+4+3+2+1 == 55.

And there is a note for why we do this: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L5252

I believe it CAN be optimized, it's weather it can be by me..

The thing is, it doesn't affect 99.9% of our users who might have a list with 10/20 things in, they won't see the performance decrease.  

Where it does potentially cause problems is a DoS attack where an attacker can turn everything into an OL, hit indent and lock up everyone's JS thread.  This said, that same attacker can just arbitrarily dump whatever binary noise they want into a pad rate unlimited at current anyway....   EDIT: Okay so that's not even an attack vector.  The recipient of the edit's thread isn't locked..  Which seems weird to me but I guess it's not computing the attributes it's just applying them so yea, makes sense now I typed it out loud -_-

So I think a takeaway here is:  Won't fix as a priority.

Am curious to see if I could give this task to some sort of thread to not lock up the main thread.

Defo gonna unassign myself because I'm not good at optimizations.

**Comment by JohnMcLear** [comment] 2020-05-06 11:09
Closing in favor of https://github.com/ether/etherpad-lite/issues/3504

**Closed by JohnMcLear** 2020-05-06 11:09 UTC
Labels: Bug, performance
