### ISSUE TITLE
Spaces are lost around wrapped line - Ready for Review #2 and merge

### ISSUE THREAD

**Issue by rupran** [ether/etherpad-lite#3487] opened 2018-09-26 10:20 UTC
On my hosted etherpad-lite instance, I have the issue that spaces typed at the beginning of a wrapped line are being ignored, leading to the last word of the previous line and the new word wrapping without a space between them.

I made a recording of this problem. This is on a newly created pad. Both times, I type `<space><s><e><e><s><space>`. With the default text in place, this works, but after erasing everything I typed and typing the same sequence again, the leading space gets dropped.

![screen recording 2018-09-26 at 12 08 32](https://user-images.githubusercontent.com/6428272/46073397-1318be80-c185-11e8-8266-f193f64f4f07.gif)

**Relevant system information:**
- Etherpad-Lite: from git at https://github.com/ether/etherpad-lite/commit/2a5e87cc7da748da94d1169df2a470b6406b65b9 (most recent commit in `develop`)
- Client OS: macOS 10.14 (18A391) Mojave
- Browser: Google Chome Version 69.0.3497.100 (Official Build) (64-bit)
- Host OS: CentOS 7, shared hosting
  - npm: 5.6.0
  - node: v8.11.3

**Steps to reproduce:**
Open a new or existing pad, start typing a space followed by other characters with the cursor at the beginning of a wrapped line.

**What did you expect to happen?**
The last word of the previous line stays in the previous line, the new word starts at the current cursor position.

**What actually happened?**
The line break is removed, merging the last word of the previous line and the new word without a space even though it was entered.

**Comment by JohnMcLear** [comment] 2020-03-14 19:06
Confirmed.   This is a horrible bug, probably due to pre-wrap setting.

**Comment by JohnMcLear** [comment] 2020-04-03 20:29
@rupran I was just testing this and I'm 99% sure I can't replicate this bug on Firefox, can you confirm?

**Comment by JohnMcLear** [comment] 2020-04-03 20:36
Also if so..
commenting out the below seems to fix it...
  /*
  word-wrap: break-word; /* fix for issue #1648 - firefox not wrapping long $
  */
Can anyone confirm?

**Comment by JohnMcLear** [comment] 2020-04-03 20:42
Does removing the comments around

```
   white-space: pre-wrap;
``` 
in ``iframe_editor.css``

**Comment by JohnMcLear** [comment] 2020-04-05 12:06
Great spot @seballot - yeah it's a complex problem compounded by another bug for caret positioning on wraps.

I removed the JS hack and CSS "fix" for the JS hack.

Full disclaimer: Older versions of Chrome may have a bug.  But we can make the assumption that most peoples chrome version is kept up to date so I'm not going to worry about this.  What we could do is target older chrome versions with a fix.

I think we can merge and close this and I will just have to do more test coverage for caret position and character string entry when I submit my fix for caret positioning (which is WIP and due within 48 hours).

**Comment by seballot** [comment] 2020-04-06 07:59
nice ! so we can also remove the "doesWrap" and the "noprewrap" classes (in both js and css probably) ?

**Comment by JohnMcLear** [comment] 2020-04-06 09:31
Yea, if they are cruft they can go.  Do a ``grep -rni`` for them in the code base and make sure they aren't used elsewhere.

**Comment by muxator** [comment] 2020-04-07 01:48
Merged fix. Thanks @JohnMcLear and @seballot.

**Closed** 2020-04-07 01:47 UTC
Labels: Bug, UX, Waiting on Testing, editor
