### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setStateIdle' of null

### ISSUE THREAD

**Issue by caugner** [ether/etherpad-lite#3405] opened 2018-05-28 06:27 UTC
I'm getting the following error in Chrome 66 when accessing a pad in our instance (running 1.6.6).
Meanwhile, access with Firefox 60 works without problems. Any tips?

```
An error occurred
The error was reported with the following id: 'qZF4pJdMtrdhNgDJlfp0'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: qZF4pJdMtrdhNgDJlfp0
URL: https://pad.example.com/padname
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://pad.example.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
```

It seems to stem from this code section, where `pad.collabClient` seems to be null:

```js
            socket.on("error", function(e) {
                pad.collabClient.setStateIdle(),
                pad.collabClient.setIsPendingRevision(!0)
            });
```

When pausing with a breakpoint, the error `e` is undefined.

According to the call stack, the error occurred in this call:

```js
            io.connect(n, {
                path: exports.baseURL + "socket.io",
                resource: a,
                reconnectionAttempts: 5,
                reconnection: !0,
                reconnectionDelay: 1e3,
                reconnectionDelayMax: 5e3
            })
```

P.S.: It's actually suprising that `pad.collabClient` is [already used in the `handshake()`](https://github.com/ether/etherpad-lite/blob/7b6a4aba3024f7713eab7294fd3473630053ba9d/src/static/js/pad.js#L183-L225), while it is [only initialized in `_afterHandshake()`](https://github.com/ether/etherpad-lite/blob/7b6a4aba3024f7713eab7294fd3473630053ba9d/src/static/js/pad.js#L476-L516).

P.P.S.: Troubleshooting information as follows:

```
Etherpad version

Version number: 1.6.6

Git sha: 7e69a82
Installed plugins

ep_etherpad-lite

Installed parts

ep_etherpad-lite/swagger
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express

Installed hooks
Server side hooks

expressCreateServer
    ep_etherpad-lite/node/hooks/express/swagger:expressCreateServer from ep_etherpad-lite/swagger
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer from ep_etherpad-lite/adminsettings
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminplugins:expressCreateServer from ep_etherpad-lite/adminplugins
expressCreateServer
    ep_etherpad-lite/node/hooks/express/admin:expressCreateServer from ep_etherpad-lite/admin
expressCreateServer
    ep_etherpad-lite/node/hooks/express/tests:expressCreateServer from ep_etherpad-lite/tests
expressCreateServer
    ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer from ep_etherpad-lite/socketio
expressCreateServer
    ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer from ep_etherpad-lite/errorhandling
expressCreateServer
    ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer from ep_etherpad-lite/importexport
expressCreateServer
    ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer from ep_etherpad-lite/apicalls
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer from ep_etherpad-lite/padreadonly
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer from ep_etherpad-lite/padurlsanitize
expressCreateServer
    ep_etherpad-lite/node/hooks/express/specialpages:expressCreateServer from ep_etherpad-lite/specialpages
expressCreateServer
    ep_etherpad-lite/node/hooks/i18n:expressCreateServer from ep_etherpad-lite/i18n
expressCreateServer
    ep_etherpad-lite/node/hooks/express/static:expressCreateServer from ep_etherpad-lite/static
socketio
    ep_etherpad-lite/node/hooks/express/adminsettings:socketio from ep_etherpad-lite/adminsettings
socketio
    ep_etherpad-lite/node/hooks/express/adminplugins:socketio from ep_etherpad-lite/adminplugins
expressConfigure
    ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure from ep_etherpad-lite/webaccess
createServer
    ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express
restartServer
    ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express

Client side hooks
```

**Comment by fralix** [comment] 2018-06-20 20:39
Related?
``TypeError: pad.collabClient is null in https://pad.fralix.ovh/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'``

**Comment by muxator** [comment] 2018-08-14 21:05
> P.S.: It's actually suprising that pad.collabClient is already used in the handshake(), while it is only initialized in _afterHandshake().

Indeed it is, @caugner.
I am not being able to trigger the bug, but the hairy initialization is a potential problem on its own. Fixing that could probably give us a clue about this issue, or solve it altogether.

@anugu-chegg, since you worked closely on this file for [#3318](https://github.com/ether/etherpad-lite/pull/3318/files#diff-eeb5b9a97d3e8bdc960c1edab4afa376), do you have some hints?

**Comment by fralix** [comment] 2018-08-14 22:08
Hey, I can no longer reproduce the issue with a proper proxy setup:

https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy 
https://github.com/ether/etherpad-lite/issues/2318#issuecomment-63548542 

So i guess the issue is really down to the socket connection and reading all the guides may help? :joy:

**Comment by muxator** [comment] 2018-08-14 22:37
Good news, @fralix.
Good documentation is precious.

I leave the issue open, since I continue being curious about the "phantom" initialization uncovered by @caugner.

I am starting to think about how to improve the codebase [without rewriting it](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i) (more tests, linters, static analyzers, maybe even gradually migrating to TypeScript...), and this sort of issues interest me a lot.

**Comment by joluc** [comment] 2019-03-20 17:40
Hi there,
thanks for creating etherpad. I am using it in a project for Fridays For Future Germany.
This bug also occurred in our installation, version `1.7.5`:

`Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://domain.removed.also.the.path/static/js/pad.js?callback=require.define at line 3'`

We have this plugins installed:
```
ep_adminpads
ep_etherpad-lite
ep_headings2
ep_font_color
ep_footer
```

Just wanted to report it!
Let me know if I can provide more information to fix this issue.

**Comment by xshadow** [comment] 2019-12-12 10:42
I can confirm that this error is also present in v1.8.0.

```
Dec 12 10:59:51 etherpad nodejs[28467]: #033[33m[2019-12-12 10:59:51.645] [WARN] client - #033[39mUncaught TypeError: Cannot read property 'setStateIdle' of null -- { errorId: 'ZFFGAJRhNPLZkgcdXRxQ',
Dec 12 10:59:51 etherpad nodejs[28467]:    'Uncaught TypeError: Cannot read property \'setStateIdle\' of null',
```

**Comment by vijaygodhasara** [comment] 2020-03-28 09:54
I am using etherpad_lite version 1.6.0 version. we have also observed this issue that
App 19183 output: [33m[2020-03-26 09:29:22.650] [WARN] client - [39mUncaught TypeError: Cannot read property 'setStateIdle' of null -- { errorId: '3tl0hHxTQ9rwZ0ojNXoI',
App 19183 output:   msg:
App 19183 output:    'Uncaught TypeError: Cannot read property \'setStateIdle\' of null',
App 19183 output:   url:
App 19183 output:    'https://etherpad.vnc.biz/etherpad/p/g.INJVOHVXSaiTwtQM$0c6efa006f3911ea8c106f96aa173764',
App 19183 output:   linenumber: 3,
App 19183 output:   userAgent:
App 19183 output:    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.87 Chrome/80.0.3987.87 Safari/537.36' }

Anyone can find out the solution for this issue ?

any only know that issue related to socket connection but not find out the exact root cause for this issue why we getting socket on error ?

**Comment by JohnMcLear** [comment] 2020-03-31 17:24
Please don't use Etherpad 1.6.  Please update.

**Comment by JohnMcLear** [comment] 2020-04-01 12:18
@xshadow Please provide some information such as:
* Is your Etherpad on windows/linux
* Exact Git Rev
* Is your Etherpad running behind a reverse proxy?  If so, what?
* Are you running any plugins?

**Comment by JohnMcLear** [comment] 2020-04-01 12:19
FWIW I am not seeing this bug at all across any of our instances so I think it's a configuration issue or something that isn't related to Core.

**Comment by fnetX** [comment] 2020-04-01 13:48
Please look at https://github.com/ether/etherpad-lite/issues/3405#issuecomment-413032184 - After a successful proxy setup this issue disappeared for me. I saw it again when there was an unstable network connection, so it's probably down to some issues with something not correctly accessible, but mainly a setup / network issue. 

I think this bug can be closed when current reporters don't reply and if someone experiences it again, they should provide more details about the configuration and check if it's a problem with their network connection ... Also, it's very helpful to open the browser debug console and check for network connections. Especially some wrongly setup CSPs can prevent resources from loading. I just had this with another project.

**Comment by JohnMcLear** [comment] 2020-04-01 13:53
Closing, will re-open if someone experiences moving forward.

**Comment by fnetX** [comment] 2020-04-01 13:53
If someone experiences problems while setting up an instance (when there is no sensitive user data) it might be interesting to have a look at the system and start debugging from there. I guess I could afford the time to check if it's a general issue with the system configuration, but I'm no NodeJS / etherpad developer, so I won't be able to continue debugging if it appears to be indeed an etherpad bug.

**Comment by xshadow** [comment] 2020-04-01 16:46
@JohnMcLear After a review of the Proxy settings I can confirm that [fix mentioned in the comments above](https://github.com/ether/etherpad-lite/issues/2318#issuecomment-63548542) did the trick.

**Comment by lvarnava** [comment] 2020-06-23 09:42
This error is reproduced on different instances of the etherpads in the android and chrome.
Tested on my own server and on https://etherpad.wikimedia.org, https://video.etherpad.com.

> An error occurred
> Please press and hold Ctrl and press F5 to reload this page
> If the problem persists please send this error message to your webmaster:
> 
> ErrorId: XDmLq2ENraoB3lM4ESfu
> URL: https://etherpad.wikimedia.org/p/gxz0C7Rncg-J80ra7DQw
> UserAgent: Mozilla/5.0 (Linux; Android 10; Mi A2 Lite) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36
> Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://etherpad.wikimedia.org/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=f2b033c9 at line 3
> 

### Steps to reproduce
1. in chrome browser open a new pad
2. write something
3. then click on "home" in the android
4. then through the "last applications" close everything
5. and run chrome browser again
6. he will start to open your last pad and give this error

**Comment by JohnMcLear** [comment] 2020-06-23 12:51
> then through the "last applications" close everything
I don't see any "last applications" on my screen..  Where should I be looking?

**Comment by JohnMcLear** [comment] 2020-06-23 12:54
Confirmed error!  Well done for replicating.   You get a cookie good sir! :)

**Comment by JohnMcLear** [comment] 2020-06-23 12:56
Cannot replicate locally on latest develop.  So this is fun :)

**Comment by JohnMcLear** [comment] 2020-06-23 13:15
It appears it's fixed in latest develop already..

I pulled latest onto https://video.etherpad.com

Can you still replicate?

**Comment by lvarnava** [comment] 2020-06-23 14:50
Hi @JohnMcLear! Congratulations, the error cannot be reproduced on https://video.etherpad.com.
Thank you for your work!

**Comment by webzwo0i** [comment] 2020-06-23 14:51
It's still there. I can replicate after looking at the code, but I am not sure how this is connected to closing&reopening the tab in android. In pad.js' handshake function, callbacks for socket events are registered that use collabClient. However, collabClient is null until it is set in _afterHandshake right after CLIENT_VARS are received.
So to replicate in firefox/chromium on a desktop:
Load a pad with developer mode open and as soon as you see XHR-Polling to eio cut off network. Be sure that you did not receive the CLIENT_VARS. Then wait a few seconds for the reconnecting phase to start.

**Comment by JohnMcLear** [comment] 2020-06-23 16:16
So the next question is why did updating and restarting video.etherpad.com fix??!

**Comment by webzwo0i** [comment] 2020-06-25 12:27
A bisect showed 128f3e15ebf89f69d97dce34c8d5b8c238e952d2 as the fix-commit. That kind of makes sense.

**Comment by JohnMcLear** [comment] 2020-06-25 12:47
Next level pro developer fixes bugs before they manifest....

**Comment by webzwo0i** [comment] 2020-06-25 13:06
I think there was some issue in jquery or the way we use it, that was easily triggerable and is now resolved with 128f3e15ebf89f69d97dce34c8d5b8c238e952d2
The bug when a reconnect happens (e.g. because of client's bad network) before CLIENT_VARS is received, is still there.
On my instance I see above stacktrace ~1 time a day. Not sure if there is a third way to trigger it or if every occurence on my instance is due to bad network.

**Comment by cdruet** [comment] 2020-10-19 10:06
> @vijaygodhasara Please don't use Etherpad 1.6. Please update and let us know if it persists.

I'm using 1.8.6 and I still got the error!

**Comment by JohnMcLear** [comment] 2020-10-19 11:05
@cdruet can you provide any details?  Did you test without plugins?

**Comment by mrtopf** [comment] 2020-10-19 13:31
@JohnMcLear I have the same problem with 1.8.6 (master branch) 

Here is an example: https://mrtopf.de/test.html

loading this pad: https://yopad.eu/p/textframe

Installed plugins are comments_page and headings2. 

I hopefully have time later to test it on fresh install without plugins (as I don't necessarily want to disable them on production)

**Comment by cdruet** [comment] 2020-10-19 13:44
@JohnMcLear I'm also using comments_page. On top of that auth_session.

I can test later today without comments_page but I'm auth_session to reach the pads.

Sent with Unibox

**Comment by rhansen** [comment] 2020-10-19 17:51
@cdruet and @mrtopf: Can you try the latest commit on the develop branch and set the [`cookie.sameSite` setting](https://github.com/ether/etherpad-lite/blob/105eb2651fd10a17258cbb7c4dea1972b46b510d/settings.json.template#L340-L351) to `None`? There have been some cookie changes since v1.8.6 that might be relevant.

**Comment by JohnMcLear** [comment] 2020-10-24 15:56
@rhansen can this be closed now?

**Closed** 2020-10-25 00:21 UTC
Labels: Bug, Needs confirmation

**Comment by mrtopf** [comment] 2020-10-28 09:43
@rhansen sorry, was a bit busy and setting up a test server took a bit. But I tested `develop` and this seems to work. So I am waiting for the next release then. Thanks!

**Comment by ptandler** [comment] 2020-11-10 15:11
I got this error with 1.8.5 & the current master version (based on 1.8.6 = commit 2c8769a6fd9fa4ed36ed6e32ba0826037795fb37)

when updating to develop, the first tests seems to be fine.

when is the next release expected?


Setting: include etherpad via iframe in a server running on localhost.

Stack trace (from the master version, 1.8.6++ as mentioned above), in case this is still relevant:

  | (anonymous) | @ | pad.js?callback=requ…fine&v=564a4939:227
-- | -- | -- | --
  | r.emit | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.emitAll | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | setTimeout (async) |   |  
  | r.reconnect | @ | index.js:83
  | r.onclose | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.onClose | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | setTimeout (async) |   |  
  | r.onHeartbeat | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | setTimeout (async) |   |  
  | r.setPing | @ | index.js:83
  | r.onHandshake | @ | index.js:83
  | r.onPacket | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | r.onPacket | @ | index.js:83
  | n | @ | index.js:83
  | e.decodePayload | @ | index.js:83
  | r.onData | @ | index.js:83
  | (anonymous) | @ | index.js:83
  | r.emit | @ | index.js:83
  | i.onData | @ | index.js:83
  | i.onLoad | @ | index.js:83
  | hasXDR.e.onreadystatechange | @ | index.js:83
  | XMLHttpRequest.send (async) |   |  
  | i.create | @ | index.js:83
  | i | @ | index.js:83
  | o.request | @ | index.js:83
  | o.doPoll | @ | index.js:83
  | r.poll | @ | index.js:83
  | r.doOpen | @ | index.js:83
  | r.open | @ | index.js:83
  | r.open | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | r.open.r.connect | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | r | @ | index.js:83
  | handshake | @ | pad.js?callback=requ…fine&v=564a4939:207
  | (anonymous) | @ | pad.js?callback=requ…fine&v=564a4939:484
  | mightThrow | @ | ace2_common.js?callb…ine&v=564a4939:3910
  | process | @ | ace2_common.js?callb…ine&v=564a4939:3978
  | setTimeout (async) |   |  
  | (anonymous) | @ | ace2_common.js?callb…ine&v=564a4939:4016
  | fire | @ | ace2_common.js?callb…ine&v=564a4939:3645
  | add | @ | ace2_common.js?callb…ine&v=564a4939:3704
  | (anonymous) | @ | ace2_common.js?callb…ine&v=564a4939:4036
  | Deferred | @ | ace2_common.js?callb…ine&v=564a4939:4120
  | then | @ | ace2_common.js?callb…ine&v=564a4939:4021
  | jQuery.fn.ready | @ | ace2_common.js?callb…ine&v=564a4939:4198
  | init | @ | pad.js?callback=requ…fine&v=564a4939:480
  | init | @ | pad.js?callback=requ…fine&v=564a4939:960
  | (anonymous) | @ | test1?lang=de:725
  | setTimeout (async) |   |  
  | callback | @ | ace2_common.js?callb…ne&v=564a4939:12053
  | (anonymous) | @ | ace2_common.js?callb…ne&v=564a4939:12060
  | fire | @ | ace2_common.js?callb…ine&v=564a4939:3645
  | fireWith | @ | ace2_common.js?callb…ine&v=564a4939:3775
  | done | @ | ace2_common.js?callb…ine&v=564a4939:9466
  | (anonymous) | @ | ace2_common.js?callb…ine&v=564a4939:9708
  | load (async) |   |  
  | send | @ | ace2_common.js?callb…ine&v=564a4939:9727
  | ajax | @ | ace2_common.js?callb…ine&v=564a4939:9367
  | jQuery.<computed> | @ | ace2_common.js?callb…ine&v=564a4939:9516
  | getJSON | @ | ace2_common.js?callb…ine&v=564a4939:9497
  | exports.update | @ | ace2_common.js?callb…ne&v=564a4939:12055
  | (anonymous) | @ | test1?lang=de:717
  | (anonymous) | @ | test1?lang=de:735

**Comment by rhansen** [comment] 2020-11-11 17:23
> when is the next release expected?

Soon. Hopefully this week.
