### ISSUE TITLE
Complete crash of Etherpad caused by "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Porkepix** [ether/etherpad-lite#3430] opened 2018-07-26 11:18 UTC
As an association, we're running an etherpad-lite instance.
For now a couple of weeks, and more and more regularly we're getting a complete crash of the server, with the following error:

```
[2018-07-26 10:03:42.808] [ERROR] console - RangeError: Maximum call stack size exceeded
    at exports.database.getSub (/foo/bar/pads/src/node_modules/ueberdb2/CacheAndBufferLayer.js:345:45)
    at exports.channels.doOperation [as operatorFunction] (/foo/bar/pads/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
    at exports.channels.emit (/foo/bar/pads/src/node_modules/channels/channels.js:49:11)
    at exports.database.getSub (/foo/bar/pads/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
    at Pad.getRevisionAuthor (/foo/bar/pads/src/node/db/Pad.js:143:6)
    at /foo/bar/pads/src/node/handler/PadMessageHandler.js:1200:19
    at iterate (/foo/bar/pads/src/node_modules/async/lib/async.js:149:13)
    at /foo/bar/pads/src/node_modules/async/lib/async.js:160:25
    at Object.callback (/foo/bar/pads/src/node/handler/PadMessageHandler.js:1204:17)
    at /foo/bar/pads/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:149:17
[2018-07-26 10:03:42.808] [INFO] console - graceful shutdown...
[2018-07-26 10:03:42.903] [INFO] console - db sucessfully closed.
```

I've no idea how to reproduce the issue at will. At some point I thought it was linked to https://github.com/ether/etherpad-lite/issues/3371 ; playing with the timeslider on a specific pad, I think I triggered a crash, but as the instance is used for actual work, I can't do much more on it. Tried to export the pad and import it on a test instance somewhere else, but didn't managed to reproduce it.

We're running latest stable version (1.6.6).

EDIT: Of course, if there's some ways to gather more informations on what could cause this, please let me know.

**Comment by muxator** [comment] 2018-07-28 01:46
@Porkepix, that's really unfortunate.

It's just an hypothesis, but if some bad data sneaked inside the DB (because of a bug), and that data manages to crash Etehrpad (another bug), we could solve two interesting problems.

Maybe you could clone the DB and play with it on a separate Etherpad instance. If you managed to understand where the problematic data is, you could extract & sanitize it, and then include it in the bug report.

**Comment by Porkepix** [comment] 2018-07-31 13:05
Well, I can't just clone everything, I guess some event trigger the issue, but I've not idea how could I know what the trigger is.
Is there a way to know what was going on when the crash occur?

**Comment by muxator** [comment] 2018-08-28 21:56
Hi @Porkepix, sorry for the delay.

I do not think there is an established way to get this sort of information yet.

This is something I would like to improve, because having good error reporting is important to move forward.

Please feel free to report other issues you may encounter.

**Comment by ArcticSnowman** [comment] 2018-10-25 14:22
Do you per-chance have the ep_simpletextsearch plugin?

**Comment by Porkepix** [comment] 2018-10-25 15:50
No, this plugin isn't installed. Do you think it could have been a cause?

**Comment by Porkepix** [comment] 2018-10-25 16:58
Well, I can't tell as I have no way to know for sure if a pad is particularly causing this.
But yes, our instance have a lot of pads for years, and the amount of users that goes with.

**Comment by helioloureiro** [comment] 2018-12-10 13:53
Facing the same issue.  I just wrote a perl script to parse the logs and check the number of active pads between crashes, as enters and leaves:

### REPORTING AT CRASH ###
Total pads: 11
Total enters: 365
Total leaves: 344

### REPORTING AT CRASH ###
Total pads: 76
Total enters: 696
Total leaves: 566

### REPORTING AT CRASH ###
Total pads: 102
Total enters: 930
Total leaves: 681

### REPORTING AT CRASH ###
Total pads: 121
Total enters: 1050
Total leaves: 735

So it is quite active.  My errors:

[2018-12-10 05:09:47.332] [ERROR] console - RangeError: Maximum call stack size exceeded
    at writeToEngine (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/client.js:149:17)
    at /var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/client.js:157:9
    at Encoder.encode (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/node_modules/socket.io-parser/index.js:134:5)
    at Client.packet (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/client.js:156:20)
    at Socket.packet (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/socket.js:223:15)
    at Socket.emit (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/socket.js:168:12)
    at Socket.send.Socket.write (/var/etherpad-lite-1.6.6/src/node_modules/socket.io/lib/socket.js:207:13)
    at Socket.client.send (/var/etherpad-lite-1.6.6/src/node/handler/SocketIORouter.js:76:14)
    at /var/etherpad-lite-1.6.6/src/node/handler/PadMessageHandler.js:1238:25
    at iterate (/var/etherpad-lite-1.6.6/src/node_modules/async/lib/async.js:149:13)
[2018-12-10 05:09:47.333] [INFO] console - graceful shutdown...
[2018-12-10 05:09:47.344] [INFO] console - db sucessfully closed.

So running on etherpad-lite-1.6.6, node 8.11.3 and npm 5.6.0.  And very often crash/restarts.

**Comment by Porkepix** [comment] 2019-01-16 12:09
We use very few plugins and don't use this one.
Some plugins might be mandatory depending on use case, for example MyPads one for private pads en user management :)

**Comment by decentral1se** [comment] 2019-05-20 18:46
Ah, just happened to our installation as well. Here's what I see in the journal logs:

> May 20 20:20:21 fooserver sh[4484]: [2019-05-20 20:20:21.006] [ERROR] console - RangeError: Maximum call stack size exceeded
> May 20 20:20:21 fooserver sh[4484]:     at String.replace (<anonymous>)
> May 20 20:20:21 fooserver sh[4484]:     at Object.exports.moveOpsToNewPool (/srv/etherpad-lite/src/static/js/Changeset.js:1526:21)
> May 20 20:20:21 fooserver sh[4484]:     at Object.exports.prepareForWire (/srv/etherpad-lite/src/static/js/Changeset.js:1693:23)
> May 20 20:20:21 fooserver sh[4484]:     at /srv/etherpad-lite/src/node/handler/PadMessageHandler.js:1240:37
> May 20 20:20:21 fooserver sh[4484]:     at iterate (/srv/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
> May 20 20:20:21 fooserver sh[4484]:     at /srv/etherpad-lite/src/node_modules/async/lib/async.js:160:25
> May 20 20:20:21 fooserver sh[4484]:     at /srv/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
> May 20 20:20:21 fooserver sh[4484]:     at iterate (/srv/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
> May 20 20:20:21 fooserver sh[4484]:     at /srv/etherpad-lite/src/node_modules/async/lib/async.js:160:25
> May 20 20:20:21 fooserver sh[4484]:     at /srv/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
> May 20 20:20:21 fooserver sh[4484]: [2019-05-20 20:20:21.006] [INFO] console - graceful shutdown...

On the following versions:

> $ node --version
> v9.11.2
> $ npm --version
> e5.6.0

On this commit: 9aaa02ec703453de3389929f8d806ca2ca2dde52.

No plugins AFAICT.

**Comment by t2d** [comment] 2019-09-26 07:37
Same problem here. It seems to be caused by multiple user actions, but `PadMessageHandler` is always involved.

```
$ node --version
v10.16.3
$ npm --version
6.9.0
```
Release version: 1.7.5

**Comment by 0x46616c6b** [comment] 2019-09-26 14:20
We see this in the log before the crash happens

```shell
Sep 26 13:35:51 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:51.918] [INFO] access - #033[39m[ENTER] Pad "<padname>": Client uTibl2gOCt74Vpv5ABEA with IP "ANONYMOUS" entered the pad
Sep 26 13:35:51 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:51.920] [INFO] ueberDB - #033[39mFlushed 1 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.003] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.167] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.313] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.476] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.611] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.754] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.867] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:52 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:52.943] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.030] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.118] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.301] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.414] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.524] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.622] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.716] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.791] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.865] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:53 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:53.932] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:54 etherpad nodejs[20949]: #033[32m[2019-09-26 13:35:54.002] [INFO] ueberDB - #033[39mgarbage collected 500 values
Sep 26 13:35:54 etherpad nodejs[20949]: #033[31m[2019-09-26 13:35:54.155] [ERROR] console - #033[39mRangeError: Maximum call stack size exceeded
```

Maybe this will help how many changes are happened in our setup. We have the following versions deployed

```shell
$ node --version
v10.16.3
$ npm --version
6.9.0
```

Release: 1.7.5

**Comment by Apromixately** [comment] 2019-11-08 22:11
Similar error here
```
[2019-11-08 19:19:45.363] [ERROR] console - RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at stringifyWithoutPassword (/home/simon/etherpad-lite/src/node/handler/SocketIORouter.js:165:15)
    at Socket.client.send (/home/simon/etherpad-lite/src/node/handler/SocketIORouter.js:75:54)
    at /home/simon/etherpad-lite/src/node/handler/PadMessageHandler.js:1250:25
    at iterate (/home/simon/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/simon/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/simon/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
    at iterate (/home/simon/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/simon/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/simon/etherpad-lite/src/node/handler/PadMessageHandler.js:1251:13
```
I've not set up logging to a file and set the level to debug. Anything else I could do to get more information?

**Comment by xshadow** [comment] 2019-11-10 13:02
There is now a bug bounty for this issue:  https://www.bountysource.com/issues/61363365-complete-crash-of-etherpad-caused-by-rangeerror-maximum-call-stack-size-exceeded

**Comment by muxator** [comment] 2019-11-14 21:35
Preliminary question: is it true that all these crashed happened on versions <= **1.7.5**?

If so, I wonder if this still happens on **1.8.0-beta.1**, since the code changed a lot compared to previous versions.

The loop seem to be triggered by repeated async calls in PadMessageHandler, that in **1.7.5** used `node_modules/async/lib/async.js`. That dependency was removed in bb80325d2cf8e653cb8fc7f8b40e0a64c6b3c071 and subsequent commits (that landed in **1.8.0-beta.1**).

Version **1.7.5**:
https://github.com/ether/etherpad-lite/blob/6a3e4c69b8e83ff98c468529bc6a0ba1698a7526/src/node/handler/PadMessageHandler.js#L1238-L1252

Version **1.8.0-beta.1**:
https://github.com/ether/etherpad-lite/blob/503b11730c4ee6fe0fff50209b5126b73268eccd/src/node/handler/PadMessageHandler.js#L1023-L1045

**Comment by Apromixately** [comment] 2019-11-17 12:52
I've only had this error once and iit was indeed on 1.7.5.

```

Etherpad version

Version number: 1.7.5

Git sha: 6a3e4c6
Installed plugins

ep_adminpads
ep_etherpad-lite

Installed parts

ep_etherpad-lite/swagger
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_adminpads/ep_adminpads

Installed hooks
Server side hooks

expressCreateServer
    ep_etherpad-lite/node/hooks/express/swagger:expressCreateServer from ep_etherpad-lite/swagger
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer from ep_etherpad-lite/adminsettings
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminplugins:expressCreateServer from ep_etherpad-lite/adminplugins
expressCreateServer
    ep_etherpad-lite/node/hooks/express/admin:expressCreateServer from ep_etherpad-lite/admin
expressCreateServer
    ep_etherpad-lite/node/hooks/express/tests:expressCreateServer from ep_etherpad-lite/tests
expressCreateServer
    ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer from ep_etherpad-lite/socketio
expressCreateServer
    ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer from ep_etherpad-lite/errorhandling
expressCreateServer
    ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer from ep_etherpad-lite/importexport
expressCreateServer
    ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer from ep_etherpad-lite/apicalls
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer from ep_etherpad-lite/padreadonly
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer from ep_etherpad-lite/padurlsanitize
expressCreateServer
    ep_etherpad-lite/node/hooks/express/specialpages:expressCreateServer from ep_etherpad-lite/specialpages
expressCreateServer
    ep_etherpad-lite/node/hooks/i18n:expressCreateServer from ep_etherpad-lite/i18n
expressCreateServer
    ep_etherpad-lite/node/hooks/express/static:expressCreateServer from ep_etherpad-lite/static
expressCreateServer
    ep_adminpads/index:registerRoute from ep_adminpads/ep_adminpads
socketio
    ep_etherpad-lite/node/hooks/express/adminsettings:socketio from ep_etherpad-lite/adminsettings
socketio
    ep_etherpad-lite/node/hooks/express/adminplugins:socketio from ep_etherpad-lite/adminplugins
socketio
    ep_adminpads/index:socketio from ep_adminpads/ep_adminpads
expressConfigure
    ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure from ep_etherpad-lite/webaccess
createServer
    ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express
restartServer
    ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express
padRemove
    ep_adminpads/index:updatePads from ep_adminpads/ep_adminpads
padCreate
    ep_adminpads/index:updatePads from ep_adminpads/ep_adminpads
eejsBlock_adminMenu
    ep_adminpads/index:eejsBlock_adminMenu from ep_adminpads/ep_adminpads

Client side hooks

documentReady
    ep_adminpads/static/js/admin/pads:documentReady from ep_adminpads/ep_adminpads


```

**Comment by muxator** [comment] 2019-11-18 20:26
@Porkepix, are you in the condition of verifying if **1.8.0-beta.1** solves your crash?

**Comment by Apromixately** [comment] 2019-11-19 08:41
@muxator I don't think there is a way to reproduce the crash. If you have any ideas I can try things.

**Comment by JohnMcLear** [comment] 2020-03-30 21:04
I think this is now solved.  If anyone experiences it again please do comment here and we will re-open.

**Closed by JohnMcLear** 2020-03-30 21:04 UTC
Labels: Bug

**Comment by Apromixately** [comment] 2020-04-14 11:06
Great to hear @JohnMcLear! Minding referencing a PR or just telling me how you fixed? Just curious. :)

**Comment by JohnMcLear** [comment] 2020-04-14 14:14
@Apromixately I can't remember and need to focus on dev, sorry!
