### ISSUE TITLE
Cannot move cursor down on some long lines

### ISSUE THREAD

**Issue by MarkTraceur** [ether/etherpad-lite#2083] opened 2014-02-06 21:50 UTC
https://etherpad.wikimedia.org/p/cursortest has a line starting "    - continued releasing its beta evaluation" that is very long (two wrapped lines on even wider screens). Pressing the down arrow key from the earlier parts of that line, at least on Chromium, will do absolutely nothing. Moving it to near the end of the wrapped line will work as expected, but the down arrow does nothing.

Reported by Tilman Bayer from the WMF :)

**Comment by JohnMcLear** [comment] 2015-01-18 23:43
I can't replicate on Chrome 39 Version 39.0.2171.99 (64-bit) under Ubuntu

Pressing down key works fine.  It behaves completely as expected ;\  I suggest you get this in front of other peoples eyes so you can provide steps to replicate.

**Comment by JohnMcLear** [comment] 2020-03-26 21:20
Closing due to lack of reproducibility.

**Closed by JohnMcLear** 2020-03-26 21:20 UTC
Labels: Bug, Needs confirmation, editor
