### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by Netmage-76** [ether/etherpad-lite#2825] opened 2015-11-01 19:32 UTC
Hello,

after I installed etherpad lite on freebsd 10.2 I tried to install a couple of plugins.
When I tried to install the plugins via webinterface by clicking "Install" I received the following error message"

An error occured while installing ep_adminpads
EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json'

When I use "npm install ep_author_neat" from CLI I see:

npm install ep_author_neat
ep_author_neat@0.0.31 node_modules/ep_author_neat

and the etherpad-lite log shows:

[2015-11-01 10:21:10.412] [WARN] console - { [Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/root/.npm/ep_adminpads/0.0.9/package/package.json' }
Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json'
    at Error (native)
[2015-11-01 10:21:10.413] [INFO] console - Restarting express server

I already tried to set /root/.npm/ to 777 without success. The error message is still the same whether I use the command in /root/.npm/ or /usr/local/www/etherpad (the directory I installed etherpad-lite)
In general I wonder why why the json packets are located at the root directory, because etherpad should run at the created user "etherpad"

I would be really happy for every hint.

BR

**Comment by webzwo0i** [comment] 2015-11-01 21:54
Hi, I cannot reproduce your problem with FreeNAS (FreeBSD 9.3-RELEASE-p29). Will try to find a 10.2. Can you provide exact steps? What I did:
pkg install node npm git
# node -v                                                                   
v0.12.7                                                                         
# npm -v                                                                        
2.14.7
adduser //to create user epl
su epl
git clone git://github.com/ether/etherpad-lite
edit settings.json
./bin/installDeps.sh
node src/node/server.js

Version number: 1.5.7
Git sha: ba1f9c2
Installed plugins: ep_adminpads,ep_author_neat, ep_etherpad-lite

**Comment by Netmage-76** [comment] 2015-11-02 20:10
Hi, 

what I did was:

-- Compile and download
portmaster www/node www/npm
portmaster devel/git-lite
mkdir /usr/local/www/
cd /usr/local/www/
git clone git://github.com/ether/etherpad-lite.git

-- Create etherpad-lite user
pw adduser etherpad -d /nonexistent -s /usr/sbin/nologin -c "etherpad user"

-- Rename Dir and change rights
mv etherpad-lite etherpad
cd etherpad
chown -R etherpad:etherpad *
chown -R etherpad:etherpad .*
--- Configure settings.json

-- Check system with root rights, afterward with etherpad user
bin/run.sh --root
chown -R etherpad:etherpad *
su -m etherpad -c "bin/run.sh"


----
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json ep_etherpad-lite@1.5.7 No license field.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-10-31 10:59:08.294] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-10-31 10:59:10.268] [INFO] console - Installed plugins:
[2015-10-31 10:59:10.275] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-10-31 10:59:10.277] [INFO] console - Your Etherpad version is 1.5.7 (ba1f9c2)
[2015-10-31 10:59:10.536] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-10-31 10:59:10.537] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
----

--- Create a start script
cd /usr/local/etc/rc.d/
vim etherpad
/// Create start script
chmod +x /usr/local/etc/rc.d/etherpad
mkdir /var/run/etherpad; chown etherpad /var/run/etherpad
echo etherpad_enable=YES >> /etc/rc.conf

--- Installation and configure Mysql
portmaster databases/mysql56-server databases/mysql56-client
...
--- Configure settings.json

--- Install and configure apache 
portmaster www/apache24




node -v
v4.2.1

Tried to install plugin:
npm install ep_author_neat

---
[2015-11-01 10:21:10.412] [WARN] console - { [Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json']
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/root/.npm/ep_adminpads/0.0.9/package/package.json' }
Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json'
at Error (native)
[2015-11-01 10:21:10.413] [INFO] console - Restarting express server
---

I hope this helps

BR

**Comment by webzwo0i** [comment] 2015-11-03 02:51
Great, thank you!
You create an user that can't login - good! When you execute bin/run.sh in an environment that you inherit from root (via -m to make it work for users without login shell) npm picks default directories that belong to root and are not writeable for the user.
I would recommend that you change npm's defaults in /usr/local/etc/npmrc:
```cache = "/tmp/npm" ```
should be enough

**Comment by webzwo0i** [comment] 2015-11-03 02:59
Not 100% sure why this cache-directory is needed, because npm also uses temporary files during installation...
Note that this change affects any user on the system that executes npm as long as there's no user-specific .npmrc. If it's a etherpad-only jail you should be fine

**Comment by Netmage-76** [comment] 2015-11-03 20:48
Hello,

thank you very much for your feedback.

While I was trying your suggested procedure I received different error messages, therefore I used git in order to clone etherpad-lite from github again.

In order to avoid that files are still created in the root directory I didn't use the --root option.

But this is the error I received.

su -m etherpad -c /usr/local/www/etherpad/bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
mkdir: node_modules: Permission denied
cd: node_modules: No such file or directory
ln: ep_etherpad-lite: Permission denied
cd: ep_etherpad-lite: No such file or directory
npm ERR! install Couldn't read dependencies
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "warn"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/www/etherpad/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/usr/local/www/etherpad/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "warn"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path npm-debug.log.d85b62c8dabd5b24e4227125351cd446
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.d85b62c8dabd5b24e4227125351cd446'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.d85b62c8dabd5b24e4227125351cd446']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.d85b62c8dabd5b24e4227125351cd446' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/www/etherpad/npm-debug.log


Unfortunately there is no npm-debug.log available, therefore I would like to ask you where etherpad-lite tries to create the "node_modules:" directory. If I would use the --root option the directory would be created in the root directory.

**Comment by webzwo0i** [comment] 2015-11-03 21:37
before executing su -m etherpad -c /usr/local/www/etherpad/bin/run.sh try to cd into /usr/local/www/etherpad
if this does not work try su -m etherpad -c ./bin/run.sh or su -m etherpad -c ./bin/installDeps.sh
I don't currently have access to the machine I tested this yesterday, but if it does not succeed I will try to reactivate it.

I am not 100% sure but accessing package.json at the wrong path (its inside src/) sounds like you need to be inside etherpad's main directory. If it could not write  /usr/local/www/etherpad/npm-debug.log I would suspect you forgot to change the owner of /usr/local/www/etherpad to etherpad:etherpad this time.
node_modules are downloaded to src/node_modules and src is also symlinked to node_modules/ep-etherpad_lite. I think this has something to do with dependency resolving and the server side.

**Comment by Netmage-76** [comment] 2015-11-04 20:43
Hello,

thank you very much for your help.

You are right I forgot to change the user rights after I fetched the files from github. Now I am able to use the "npm install" command in order to install the files via cli.

Unfortunely I am not able to fetch the available module from the admin interface.
I receive the following error message:

*** etherpad.log ***
[2015-11-04 21:38:36.748] [ERROR] console - { [Error: connect ETIMEDOUT 104.130.77.39:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.130.77.39',
  port: 443 }
Error: connect ETIMEDOUT 104.130.77.39:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[2015-11-04 21:38:36.797] [WARN] console - { [Error: connect ETIMEDOUT 104.130.77.39:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.130.77.39',
  port: 443 }
Error: connect ETIMEDOUT 104.130.77.39:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

I thought the issue could be caused by an rights problem for the etherpad user but when I use the su -m etherpad -c telnet x.z.s.d 80" command I am able to connect to an website without any problems.

**Comment by Netmage-76** [comment] 2015-11-04 20:47
In addition to my last comment I tried to connect to the ip mentioned in the error log, but I was not able to connect to the IP.

su -m etherpad -c "telnet 104.130.77.39 443"
Trying 104.130.77.39...

However the same issue exists from my home pc and if I telnet from the server via root user

**Comment by Gared** [comment] 2015-11-04 23:11
The server you're trying to connect is one of our etherpad servers which provides a list of all plugins available for etherpad. I don't know why, but those servers were shut down by our hoster. We're trying to fix this ASAP.

**Comment by Gared** [comment] 2015-11-08 10:32
@Netmage-76 It's working again

**Closed** 2015-12-07 13:51 UTC
