### ISSUE TITLE
Improve pad load time take huge first time before caching enable

### ISSUE THREAD

**Issue by vijaygodhasara** [ether/etherpad-lite#4438] opened 2020-10-26 15:24 UTC
* * *
name: Feature request
about: Suggest an idea for this project
title: 'Improve pad load time first time before caching'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
current when first-time load etherpad-lite pad it will take huge time. as around to 20s for load pad as we have integrated into iframe, as we already set max-age and minify as true but that will not enough for it. is there any specific way to bundle css/js content. ?

The only thing is - I don't see how we can improve that even more. gzip is active; etherpad-lite does not bundle it (minify is set to true - but seems not to work)

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**

**Plugin?**
Might this feature be better suited to being a plugin?  Usually, features that can be plugins, should be.

**Comment by joassouza** [comment] 2020-10-26 15:41
It's not clear if you have some plugins or just Etherpad by itself. Anyways, you can try it
https://github.com/storytouch/ep_webpack

If you're using Etherpad 1.8.6, please try this branch
https://github.com/storytouch/ep_webpack/tree/fix/fix-etherpad-version-1.8.6

**Comment by JohnMcLear** [comment] 2020-10-26 15:51
@vijaygodhasara nothing wrong with Etherpad here, yes, first time you access a pad on an instance it will minify the files and serve them but that's by design.  Subsequent loads of all/any pads after that will be very fast.

CSS/JS is already minified and served as optimally as possible without additional constraints...

**Comment by JohnMcLear** [comment] 2020-10-26 15:52
I'm gonna close this because I think it's just a misunderstanding by OP.  If you want to

**Comment by vijaygodhasara** [comment] 2020-10-27 04:52
Checked with minify set as true but it will not minify the content at the client side. please check the screenshot here. 

![etherpad_lite_minify](https://user-images.githubusercontent.com/11735224/97258343-41729780-183e-11eb-9d3a-c11d88c8a4a9.png)
![etherpad_minify_js](https://user-images.githubusercontent.com/11735224/97258351-433c5b00-183e-11eb-85d5-fd6e83c27ba2.png)

**Comment by webzwo0i** [comment] 2020-10-27 07:28
https://github.com/ether/etherpad-lite/pull/4285
This should enable minification, but last time I experienced some other problems with caching_middleware, that's why I did not finish it up.

**Comment by vijaygodhasara** [comment] 2020-10-27 07:34
checking into code and found like it will not minify JS file due to the wrong condition in minify.js

(contentType == 'text/javascript')

actually, contentType received in case of javascript would be "application/javascript".

if single URL access of javascript and CSS file case found compress but when access new pad that case it will compress but not get compress content on client-side.

after doing minify as true that case it will take more time of pad load as compare to minify as false. because every time it will minify each request case it was not an ideal

**Closed** 2021-03-03 14:11 UTC
Labels: Feature Request, wontfix
