### ISSUE TITLE
Cannot read property 'colorId' of null

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3719] opened 2020-03-16 14:29 UTC
```
Mar 16 09:27:17 run.sh[1746]: [2020-03-16 09:27:17.291] [ERROR] console - (node:1746) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
Mar 16 09:27:17 run.sh[1746]: at /home/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37
Mar 16 09:27:17 run.sh[1746]: at runMicrotasks (<anonymous>)
Mar 16 09:27:17 run.sh[1746]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Mar 16 09:27:17 run.sh[1746]: at async Promise.all (index 0)
Mar 16 09:27:17 run.sh[1746]: at async handleClientReady (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:1171:5)
Mar 16 09:27:17 run.sh[1746]: [2020-03-16 09:27:17.291] [ERROR] console - (node:1746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 76)
Mar 16 09:27:19 run.sh[1746]: [2020-03-16 09:27:19.034] [WARN] message - Dropped message, USERINFO_UPDATE Session not ready.[object Object]
```
https://github.com/ether/etherpad-lite/blob/develop/src/node/handler/PadMessageHandler.js#L1199

**Comment by muxator** [comment] 2020-03-20 20:58
This is a duplicate of #3612. Referring to that one, which is earlier.

**Closed by muxator** 2020-03-20 20:58 UTC
Labels: Minor Bug
