### ISSUE TITLE
does the `PAD_OPTIONS_SHOW_CHAT` option still have an effect?

### ISSUE THREAD

**Issue by Loki-Afro** [ether/etherpad-lite#5311] opened 2021-11-30 12:17 UTC
**Describe the bug**
`PAD_OPTIONS_SHOW_CHAT` is set to false, but chat is visible.

**To Reproduce**
Steps to reproduce the behaviour:
1.
```
docker run --rm -p9001:9001 -e PAD_OPTIONS_SHOW_CHAT=false docker.io/etherpad/etherpad:1.8.16
```
2. http://localhost:9001
3. create pad
4. verify chat is not there <---- but it is there

**Expected behavior**
Chat should not be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/4738445/144045839-feae2c59-2e04-4d24-bb16-d97a4583bf8f.png)

**Server (please complete the following information):**
 - Etherpad version: 1.8.16
but earlier versions, 1.8.14 seem to be affected as well

**Comment by rhansen** [comment] 2021-12-01 04:41
Duplicate of #4927

**Closed by rhansen** 2021-12-01 04:41 UTC
