### ISSUE TITLE
error npm "wd@1.6.1 install"

### ISSUE THREAD

**Issue by Paulpatou** [ether/etherpad-lite#3417] opened 2018-07-05 09:00 UTC
Hi,

When I run sudo bin/run.sh I get an error that appears:
= = >

```
 wd@1.6.1 install /home/etherpad/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts

/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/etherpad/etherpad-lite/src/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/home/etherpad/etherpad-lite/src/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/etherpad/etherpad-lite/src/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.6.1 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Do you have any idea what's going on?
Thanks

**Comment by Paulpatou** [comment] 2018-07-09 06:47
I finally found the problem, I had first followed the tutorial that asked to install Nodejs9 that was not working.
Then I tested Nodejs6 which solved my problem

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

**Comment by muxator** [comment] 2018-07-14 19:54
Thanks for the report, @Paulpatou.

Since I was curious to see if Etherpad was really broken with NodeJS 9, I have tested an installation of Etherpad **1.6.6** on NodeJS **9.9.0** and npm **5.6.0**.

I can confirm it works.

Nodejs was installed from the official linux downloads:

```bash
cd /opt
wget https://nodejs.org/download/release/v9.9.0/node-v9.9.0-linux-x64.tar.xz
tar xf node-v9.9.0-linux-x64.tar.xz
ln -s /opt/node-v9.9.0-linux-x64/bin/node /home/etherpad/.local/bin/node
ln -s /opt/node-v9.9.0-linux-x64/bin/npm /home/etherpad/.local/bin/npm
ln -s /opt/node-v9.9.0-linux-x64/bin/npx /home/etherpad/.local/bin/npx

```

Is it possible that your issue was not due to version 9 of NodeJS, but to how it was installed on your machine? This could confirm my findings.

Thanks.

**Comment by Paulpatou** [comment] 2018-07-16 08:56
@muxator 
Thank you for taking the time 
I can't find the following folders to create the symbolic links!
/.local/bin/node
/.local/bin/npm
/.local/bin/npx

I only have that :
/home/etherpad/etherpad-lite/
./
../
APIKEY.txt
bin/
CHANGELOG.md
CONTRIBUTING.md
doc/
.git/
.gitignore
LICENSE
Makefile
node_modules/
package-lock.json
README.md
SESSIONKEY.txt
settings.json
settings.json.template
src/
start.bat
tests/
.travis.yml
var/

In the documentation I had not seen that it was necessary to make symbolic links!

**Comment by muxator** [comment] 2018-07-16 09:49
@Paulpatou, you are right: the use of symbolic links in `~/.local/bin` is just a trick I personally use for using various nodejs versions side by side. It has nothing to do with official Etherpad documentation. Sorry for not being clear.

Let me explain what I do, maybe it can be useful for development purposes:

Since nodejs is _just_ a runtime, a possible way of installing it under linux consists in nothing more than simply extracting the official linux binaries from https://nodejs.org/it/download/ and creating symlinks from the binaries in `<nodedirectory>/bin` (there are just three: `node`, `npm`, `npx`) to a folder that is already in the path (for example: `/usr/local/bin` if you want to make it available globally, or `/home/user/.local/bin` if you want to confine it to just a single user).

Again: this is just a trick I have been using for ages whenever I need to have different runtimes installed on the same system. By the way, it works _exactly the same_ for Java (just unpack & create some symlinks) and, albeit with more difficulties, Python (you'll have to `configure --prefix=<somewhere> ; make ; make install` in that case).

**Comment by Paulpatou** [comment] 2018-07-19 07:12
I finally solved my problem by running the command :
`sudo -E bin/run.sh`
To keep my user's environment variable and it works fine.
Thanks for your help

**Comment by muxator** [comment] 2018-07-19 22:47
You're welcome.
Beware of running with `sudo`, anyway! If possible try to run as a normal user.

Closing this.

**Closed by muxator** 2018-07-19 22:47 UTC

**Comment by LingaTigeen** [comment] 2018-12-14 12:55
I'm having the similar error in etherpad `1.7.0` with node `V10.14.2`. Any idea?

**Comment by JohnMcLear** [comment] 2020-03-11 16:19
For me on a VM the issue existed when I do 

```
sudo apt-get install nodejs
``

Then install the latest nodejs repository sources and redo the same command.

I think to fix the best thing to do is ``apt-get remove nodejs`` prior to installing the nodejs repository sources..  But that's just a theory.
