### ISSUE TITLE
how to set toolbar plugin order

### ISSUE THREAD

**Issue by vercha** [ether/etherpad-lite#3212] opened 2017-07-04 07:01 UTC
as titled, I imported many toolbar plugins: ep_color, ep_align, ep_highlight, ep_font; I want them arranged in a fixed order. but I don't know how to make it.
Thanks for any advice!

**Comment by lpagliari** [comment] 2017-07-04 10:31
The issue is on the plugins code, not on Etherpad core. My suggestion is to
bind those functions with the plugin name as prefix (e.g.
"ace_ep_pluginname_doInsertColors") to avoid name collision.

Could you submit a pull request to those plugins with that change, please?

**Comment by vercha** [comment] 2017-07-04 10:50
yeah, that issue fixed. 
the present issue is :  etherpd arrange toolbar plugin after loading toolbar menu. I want to change the button order. Now,I can use plugin "pre/post" to define toolbar plugin buttons' order.   But fail to let plugin button display in the middle of menubar.
DO you have any possible advice?
Thanks!

Id like to make a pull request if It helps. And thanks for etherpadteam!

**Comment by lpagliari** [comment] 2017-07-04 13:23
You can manipulate the DOM nodes on the header, for example. On [this example](https://github.com/storytouch/ep_sync_status/blob/master/static/js/index.js) the plugin moves its toolbar items to the right of all toolbar buttons. You could do something like this and move toolbar items around. There's a hook `postToolbarInit` you could use to make sure all items were created.

**Comment by lpagliari** [comment] 2017-07-04 13:23
I'm closing this now, but let me know if my suggestion does not fit your needs and I'll re-open it.

**Closed by lpagliari** 2017-07-04 13:23 UTC
