### ISSUE TITLE
Test authorship_of_editions.js complains

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3435] opened 2018-07-28 01:19 UTC
#3420 fixed an UI bug and introduced a test to verify it.

Problem is, I have difficulties running successfully the test in my environment.

| Component | Version |
|-------|-------|
|Etherpad | 58c315476954 (1.6.6+)|
| Browser | Firefox **61** & Chromium **67** |
| Node | **6.9.0** (should not matter) |
| Url for replicating | http://localhost:9001/tests/frontend/?grep=authorship_of_editions.js |

This screencast shows an example of execution.
What puzzles me is that there are two authors in the initial screen, and after reload the modifications ("x", "y", "z" at position 2,2) are not from another author.

![test-bug](https://user-images.githubusercontent.com/4067621/43351500-368b1b5c-9213-11e8-8348-2e9a234b7f2a.gif)

Supposing I have understood correctly the test case, when driven manually Etherpad behaves well:  authorship colors are maintained. This seems a problem in the test code, if at all.

@lpagliari, what is wrong with me?

**Comment by lpagliari** [comment] 2018-08-09 10:01
sorry, @muxator, I didn't have time to take a look on this. Will do so and let you know.

**Comment by muxator** [comment] 2018-08-09 10:04
No problem @lpagliari, thank you!

**Comment by muxator** [comment] 2018-08-16 23:55
Hi, Luiza.

Since this was not a blocker and **1.7** was due, I released it. Hopefully we will make it for the next point release. :)

**Comment by lpagliari** [comment] 2018-09-01 21:00
@muxator I can confirm the test does not work on Firefox on Mac too -- although it passes on Chrome and on all browsers on our Travis CI (not sure why...).

Anyway, I'm working on a fix right now, will submit a PR soon.

**Comment by lpagliari** [comment] 2018-09-01 21:15
Some details about the issue: the test on `authorship_of_editions.js` tried to make changes with 2 different authors, and then checked if each change was assigned to the correct user. The author switch was made by reloading the pad -- which on Chrome was enough to set a different author.

The error happened on Firefox because the even after reloading the pad the author id was not reset. Weirdly the tests on this browser passed on Travis CI.

The fix was to force the cookie expiration, which in turn would force a new author id to be set.

**Closed** 2018-09-02 11:10 UTC
Labels: tests
