### ISSUE TITLE
Improve accessibility for blind people and other users of screen readers

### ISSUE THREAD

**Issue by lizzard** [ether/etherpad-lite#1803] opened 2013-06-10 21:20 UTC
Might there be some ways to usefully improve Etherpad Lite's accessibility? I know that people who browse with a screen reader can't use it. Etherpad is so useful that I hate to turn away from it as a collaboration tool.  Is this something you have discussed already in issues or in a forum? I looked, but didn't find anything. If I can help gather suggestions I'm happy to do that.

**Comment by JohnMcLear** [comment] 2015-01-03 13:58
Help us help you: https://www.bountysource.com/issues/1371778-improve-accessibility-for-blind-people-and-other-users-of-screen-readers

**Comment by JohnMcLear** [comment] 2015-03-24 17:24
Hey guys, I have been tasked with working on this so if anyone can jump in and help please say! :)

**Comment by sathomas** [comment] 2015-03-24 17:33
Hi John. I'm definitely interested in working on this. I'm swamped at work for the next week or so, but might have some time to help after that. I have no knowledge of the Etherpad code base, but, as a user, I do have some ideas on how to improve its accessibility.

One suggestion I'd make is to first worry about the single user case (saving the live collaboration case for the second phase.) Even though one of Etherpad's major features is collaboration, I suspect there are plenty of folks that use it, at least some of the time, alone. There are also some relatively "low hanging fruit" for the single user case. If you like, I can try to put together a quick list now or a more reasoned and thoughtful list next week.

**Comment by sathomas** [comment] 2015-03-24 18:09
Some initial thoughts:

* [CKEditor](http://ckeditor.com/demo#a11y) is really strong on accessibility and, in general, probably serves as a great model.
* Probably the biggest accessibility problem with Etherpad is that it traps the keyboard user in the main textarea. Once a user navigates to the textarea, there is no way (using the keyboard) to navigate out. A first step here would be to define a special key combination (I like `Esc`, but other online editors seem to have settled on `Alt-F10`) that shifts the focus from the main textarea to the first toolbar button. From there, the user should be able to `Tab` to other toolbar buttons (but see below).
* Whatever the key combination(s) that support this behavior, there needs to be a way to tell the keyboard user that they exist. Perhaps a pop-up that's "visible" to screen readers, though that does introduce it's own i18n issues.
* A related issue for those sites that embed Etherpad documents in iframes is how to let a keyboard user "escape" from the iframe and get back to the main page. That will probably require some kind of plugin that enable `postMessage` communication between the Etherpad iframe and the main page. Since Etherpad seems to use a lot of nested iframes, this might not be as trivial as it first appears.

* Probably the number two issue is that the toolbar itself isn't currently navigable via the keyboard. I realize this is strictly a plugin issue and not a core Etherpad issue, but, of course, users don't care about that distinction. The simplest way to improve this would be to use `<button>` elements instead of `<span>` elements for the toolbar buttons.
* There are also some ARIA attributes that could be added to the toolbar to make it more accessible.

Those are probably the low hanging fruit. Beyond that, there are a couple of broader areas that hinder accessibility:

1. When rendered on the page, the document is just a simple textarea without any structure. For a couple of paragraphs, that's no big deal. For something more substantial, though, it's really challenging for a visually impaired user to "navigate" the document without benefits of structures such as headings. I don't know that it's possible to address this, but perhaps there's a way.
2. Live collaboration. This one's a real challenge. Google has obviously spent a lot of effort on making this work for Google Docs, and even they haven't been all that successful. A possible approach would be to take a look at what Google has done and see if anything is easily replicable.

**Comment by JohnMcLear** [comment] 2015-03-25 12:44
All duly noted and added to my pad.

I have a branch with the support in now: https://github.com/ether/etherpad-lite/tree/editbar-accessibility

My notes and to do list is at: http://john.primarypad.com/ogf-24-03-15

**Comment by JohnMcLear** [comment] 2015-03-27 11:07
Okay guys I did what I could this week.

Accessibility enabled version of Etherpad at http://beta.etherpad.org
Docs @ ow.ly/KSaJX

What have we missed?  Please have a play and let me know!

cc @sathomas @marcozehe @MrSchism @dbolter @lizzard

**Comment by pvagner** [comment] 2015-03-30 09:26
Heh guys I think it's amazing. I have created an example pad with my comments. Once it disappears I can restore it later from a backup. I need to test timeline, revisions and other features...
https://beta.etherpad.org/p/pvagner%27s_test

**Comment by JohnMcLear** [comment] 2015-03-30 19:34
@pvagner Excellent thank you so much for this!

**Comment by JohnMcLear** [comment] 2015-03-31 13:48
@pvagner et al, this is ready for further testing.

Accessibility enabled version of Etherpad at http://beta.etherpad.org
Docs @ https://github.com/ether/etherpad-lite/wiki/Accessibility
Notes from @pvagner  https://beta.etherpad.org/p/pvagner%27s_test
Todo list and completion list: https://github.com/ether/etherpad-lite/issues/2566

**Comment by pvagner** [comment] 2015-04-06 16:49
Hello,
Sorry for my late reply.
I apologise but I fail to make use of time slider accessibility. I don't know how to make it work so I can see multiple revisions of the same pad. Do I need to explicitly save some revisions or does it allow me to navigate all the revisions as I am editing a pad?
My testing pad at beta.etherpad.org is now gone because of possible upgrades. I do have 1 MB backup file. And I can't import it either to beta.etherpad.org nor to my own install of etherpad.
Also admin UI is working like a webpage I haven't found nothing breaking usability so far although I have only tested a few plugins up to now. My confusion with time slider is my biggest issue at this point. Otherwise I like it all.

**Comment by JohnMcLear** [comment] 2015-04-07 12:41
@pvagner thanks, Timeslider should just be able to play back the pad...  Visit

https://beta.etherpad.org/p/foo/timeslider#0

and try to use that page..  Does that work for you?

**Comment by pvagner** [comment] 2015-04-08 19:20
Thank you for the explanation and a test pad. I have finally got the idea hopefully.
I can move back / forward a revision by pressing left / right arrow key however nothing changes when I focus the buttons and press the enter key. Also as I am moving with arrow keys I am getting no feetback that something has changed on linux with Firefox 37 and orca. I will test on Windows later.
Do you remember my comments on sliders from that testing pad. Have you looked for some keyboard usable sliders just to try comparing how these are working please?
Also I am a bit curious have you received some more comments from other disabled people via other means or am I just the lucky one speculating a lot here?

**Comment by JohnMcLear** [comment] 2015-04-10 09:18
Hrm, well yeah regarding the timeslider experience, it's tricky because I wouldn't know what content to read to a screen reader..  I guess we could have an aria content section on the pad contents in the timeslider and make it read that contents on each forward/backwards but that's going to be a horrible UX for a screen reader?

I did look at other slider options, they don't really "fit" into what we're doing, our slider has to be designed in such a way that we will be able to overlay contents onto it in the future (a feature I want to work on) and as such we need to stick with our current solution..  It would however be useful to have an aria notification on slider move that notifies the user of their new location in the pad IE the date/time and the revision.  I will add these bits to do my todo list :)

I have received some comments but until it's merged into a release branch they are only dripping in slowly!

**Comment by JohnMcLear** [comment] 2015-04-10 09:34
This is now merged into Develop and will be released into master shortly :) Enjoy folks!  Donations welcome!  http://etherpad.org

**Closed by JohnMcLear** 2015-04-10 09:34 UTC
Labels: Feature Request, UX

**Comment by ndarilek** [comment] 2015-06-26 16:10
Should this be available on the Sandstorm demo?

I'm blind and just tried this. The edit area is nicely accessible, but the toolbar is a bunch of unlabeled buttons/links. Arrowing through just says "button button button link clickable clickable clickable"...

Nice work so far!

**Comment by ndarilek** [comment] 2015-06-26 16:15
Should this be available on the Sandstorm demo?

I'm blind and just tried this. The edit area is nicely accessible, but the toolbar is a bunch of unlabeled buttons/links. Arrowing through just says "button button button link clickable clickable clickable"...

Nice work so far!

Edit: Ah, I see the issue. Toolbar buttons read when tabbed through, but not when arrowed past. It might be wise to use aria-label rather than the title attribute for those, as that should address both use cases.

See this thread on the Discourse forum for more details:

https://meta.discourse.org/t/accessibility-software-and-discourse/13711/21

**Comment by JohnMcLear** [comment] 2015-06-26 17:38
Good question, I'd check with the sandstorm guys! @kentonv

On 26 Jun 2015 17:10, Nolan Darilek <notifications@github.com> wrote:

Should this be available on the Sandstorm demo?

I'm blind and just tried this. The edit area is nicely accessible, but the toolbar is a bunch of unlabeled buttons/links. Arrowing through just says "button button button link clickable clickable clickable"...

Nice work so far!

**Comment by ndarilek** [comment] 2015-06-26 17:44
Check out my edit below. Looks like all the controls use `title` rather
than `aria-label`. They work fine if I tab between them, but not so well
if I arrow through the controls outside of the edit field. Should be a
pretty simple fix.

Thanks!

**Comment by kentonv** [comment] 2015-06-26 18:17
I think that Etherpad in Sandstorm should be the same accessibility-wise as Etherpad outside of Sandstorm.

Of course, Sandstorm itself introduces an additional top bar with some more buttons, and we haven't had a chance to think about accessibility yet (in fact, the UI is still pretty bad even for those who can see).

**Comment by JohnMcLear** [comment] 2015-06-26 18:18
Hrm do you have the same experience on beta.etherpad.org ?

On 26 Jun 2015 19:17, Kenton Varda <notifications@github.com> wrote:

I think that Etherpad in Sandstorm should be the same accessibility-wise as Etherpad outside of Sandstorm.

Of course, Sandstorm itself introduces an additional top bar with some more buttons, and we haven't had a chance to think about accessibility yet (in fact, the UI is still pretty bad even for those who can see).

**Comment by ndarilek** [comment] 2015-06-26 18:21
Sorry, the reference to Sandstorm was a bit of a red herring. I'd tried
it in Sandstorm and had assumed that maybe the version Sandstorm shipped
might be lagging behind the released version, but it looks pretty
up-to-date. The issue isn't Sandstorm, it's just the use of the title
attribute rather than aria-label. Sandstorm itself is already pretty
accessible, but that's tangential to this issue. :)

**Comment by ndarilek** [comment] 2015-06-26 18:29
Yes, because it still uses the same code. I.e.:

    <button class=" buttonicon
buttonicon-insertunorderedlist" data-l10n-id="pad.toolbar.ul.title" title="Unordered
List (Ctrl+Shift+L)"></button>

What you need is:

    <button class=" buttonicon
buttonicon-insertunorderedlist" data-l10n-id="pad.toolbar.ul.title"
aria-label="Unordered List (Ctrl+Shift+L)"></button>

Or possibly both the title and aria-label attributes. Please see the
Discourse thread. In short, screen readers don't reliably present the
title attribute because it's been abused for years. In the case of my
use (NVDA, Windows 8.1) I get two different presentations of the same
control. The first, when I tab between the buttons, is correct. The
`title` attribute is spoken as it should be.

The second is a bit non-standard. I can arrow through the controls as if
the webpage was a document. This is often a faster way for me to scan a
page. When you tab around, you're focused just on that particular
element. By contrast, when I arrow, I can get a larger glimpse of how
the page is laid out independent of keyboard focusability/order. In this
instance, I just hear "Button Button Button Button..." which is less
than ideal. :)

The way to fix this is to use aria-label instead of, or in addition to,
the title attribute. Any situation where this isn't the case will still
exhibit this behavior. It isn't a huge deal, but it would certainly be
very helpful.

Thanks.

**Comment by JohnMcLear** [comment] 2015-06-26 19:27
Very useful I will do this tonight and update beta.etherpad.org for you to review :) thanks man!

On 26 Jun 2015 19:30, Nolan Darilek <notifications@github.com> wrote:
Yes, because it still uses the same code. I.e.:

<button class=" buttonicon
buttonicon-insertunorderedlist" data-l10n-id="pad.toolbar.ul.title" title="Unordered
List (Ctrl+Shift+L)"></button>

What you need is:

<button class=" buttonicon
buttonicon-insertunorderedlist" data-l10n-id="pad.toolbar.ul.title"
aria-label="Unordered List (Ctrl+Shift+L)"></button>

Or possibly both the title and aria-label attributes. Please see the
Discourse thread. In short, screen readers don't reliably present the
title attribute because it's been abused for years. In the case of my
use (NVDA, Windows 8.1) I get two different presentations of the same
control. The first, when I tab between the buttons, is correct. The
`title` attribute is spoken as it should be.

The second is a bit non-standard. I can arrow through the controls as if
the webpage was a document. This is often a faster way for me to scan a
page. When you tab around, you're focused just on that particular
element. By contrast, when I arrow, I can get a larger glimpse of how
the page is laid out independent of keyboard focusability/order. In this
instance, I just hear "Button Button Button Button..." which is less
than ideal. :)

The way to fix this is to use aria-label instead of, or in addition to,
the title attribute. Any situation where this isn't the case will still
exhibit this behavior. It isn't a huge deal, but it would certainly be
very helpful.

Thanks.

**Comment by JohnMcLear** [comment] 2015-06-26 21:05
having some issues with this will try finish over weekend
________________________________

**Comment by JohnMcLear** [comment] 2015-06-28 16:15
Resolved https://github.com/ether/etherpad-lite/pull/2711
