### ISSUE TITLE
disappearing spaces in Chrome

### ISSUE THREAD

**Issue by PhKi** [ether/etherpad-lite#3377] opened 2018-04-12 14:40 UTC
As you navigate the text with the arrow keys, some spaces get lost.
It happens everytime, but only in Chrome.
If the cursor is right in front of a space and you hit rightarrow then leftarrow and then rightarrow again, the space gets lost.

![etherpad_bug](https://user-images.githubusercontent.com/16797300/38684085-314dea9a-3e6f-11e8-8fb1-b19a96a563aa.gif)

I have a clean installation of version 1.6.5
But i get the same error on version 1.6.2

In Firefox, Internet Explorer, Edge and Safari it works like expected.
I've tested it on 4 different machines and on every one of them Chrome has this issue.

So i looked into the html code and noticed that somehow in chrome the spaces get sortet to the end.

![etherpad_bug_html](https://user-images.githubusercontent.com/16797300/38684264-9703733c-3e6f-11e8-90c4-c13b5615c6a5.gif)

In firefox for example, everything is in order.

![etherpad_working_firefox](https://user-images.githubusercontent.com/16797300/38684292-a4ed2b00-3e6f-11e8-91ab-f96828ad4ad9.gif)

**Comment by muxator** [comment] 2018-04-15 13:48
I was not able to reproduce this in Chromium/Linux. Maybe this is really Chrome specific?

**Comment by skupfer** [comment] 2018-04-23 10:35
Chrome 65.* on Mac OS,
Chrome 65.* on Windows 10,
Chrome 66.* on Windows 7
confirmed using https://beta.etherpad.org/

Chrome 58.* on Windows 7,
Safari * on Mac OS,
cannot confirm

Looks like an issue with latest Chrome not etherpad itself

**Comment by muxator** [comment] 2018-06-28 23:29
Chrome is now at 67.

@skupfer, I have no Chrome or Chromium installed: would it be easy for you to do a quick check?
If the problem is gone, then we could ditch it as a browser bug (sadly, the reverse is not true :) )

**Comment by skupfer** [comment] 2018-07-12 17:14
Would have been faster to install it or use a portable version ...

**Bug disappeared with Chrome v67** (non updated etherpad, dunno which git rev I am at and too lazy to look for that)

**Comment by muxator** [comment] 2018-07-12 19:12
Thanks @skupfer.

Closing this, since it appears to have been a browser bug (never observer by me in Chromium/Linux, btw).

**Closed by muxator** 2018-07-12 19:12 UTC
Labels: Bug, Needs confirmation

**Comment by homeworkprod** [comment] 2018-09-16 22:11
> Would have been faster to install it or use a portable version ...
> 
> **Bug disappeared with Chrome v67** / or maybe earlier (non updated etherpad, dunno which git rev I am at and too lazy to look for that)

I have recently observed this on `Chromium68.0.3440.75 (Developer Build) built on Debian 9.5, running on Debian 9.5 (64-Bit)`, though.

**Comment by homeworkprod** [comment] 2018-09-16 22:15
And, since I just updated Chromium: I can reproduce this on https://beta.etherpad.org/ with version `69.0.3497.81` as well.
