### ISSUE TITLE
Copy/paste bug

### ISSUE THREAD

**Issue by lofrequency** [ether/etherpad-lite#2742] opened 2015-08-04 05:06 UTC
I'm working on a script, so when I go to copy and paste what I've written already, it all counts as a single line and scrollbars don't appear. Also, I cannot change the text style of anything that this happens to. Sometimes I can get it to treat the pasted text normally if I create a bunch of lines by repeatedly hitting enter, and paste the text into that, but that doesn't always work.

**Comment by niedzielski** [comment] 2015-08-14 16:22
I have the same problem. When I copy and paste a body of text, I lose all newlines and formatting of any kind.

**Comment by bjonnh** [comment] 2015-09-15 19:17
same here

**Comment by bujatt** [comment] 2015-11-26 16:48
same here

**Comment by Mayccoll** [comment] 2016-01-04 22:02
same here. version 1.5.7

**Comment by JohnMcLear** [comment] 2016-05-04 21:07
what browser are you all using?

**Comment by pabelenda** [comment] 2016-09-01 09:09
Same here.

Copying from:
Firefox 48.0
Chrome 53.0.2785.89
Chromium 52.0.2743.116
Evolution 3.12.9
Gedit 3.14.0

Pasting to all the browsers above fails.

Copying from icedove 45.2.0, works just nice.

**Comment by pabelenda** [comment] 2016-09-06 08:06
This is a quite serious issue, tbh.
It could be duplicated, though. See #2625

**Comment by pabelenda** [comment] 2016-10-03 09:47
Do you need me to do any further testing on this? I am willing to see this fixed on my etherpad deployment :-)

**Comment by Wikinaut** [comment] 2016-10-26 08:28
Same here. Firefox ESR 45.4.0 (Debian 8). What could I try, or how can I help to fix it ?

**Comment by johamha** [comment] 2017-01-12 11:24
Same here.  
Google Chrome Linux Version 55.0.2883.75 
with Firefox 50.1.0 it's working.

**Comment by psaavedra** [comment] 2017-02-02 06:36
I can still reproduce it in Epiphany 3.22, but it seems to be gone from FF 50 or Chromium 55.

**Comment by psaavedra** [comment] 2017-02-02 09:44
Looks like the problem in Safari and epiphany is originated by the workaround introduced in #1766. I just reverted this one and the copy&paste works well now in Epiphany:

``` diff
--- ./etherpad-lite/node_modules/ep_etherpad-lite/static/css/iframe_editor.css.orig	2017-02-02 10:21:45.201005469 +0100
+++ ./etherpad-lite/node_modules/ep_etherpad-lite/static/css/iframe_editor.css	2017-02-02 10:23:02.612889597 +0100
@@ -120,8 +120,6 @@
 }
 
- body.doesWrap:not(.noprewrap) > div{
-  /* Related to #1766 */
-  white-space: pre-wrap;
- }
 
 #innerdocbody {
```

**Comment by danzek** [comment] 2017-10-19 15:12
Same problem here in Firefox 56.0.1 on Windows -- makes Gist worthless.

**Comment by amodig** [comment] 2017-11-01 18:49
Same problem with Firefox 56.0 on Fedora. But Chrome 62.0 works fine!

**Comment by Pharap** [comment] 2017-11-10 05:56
Same problem, Firefox 56.0.2 64-bit Windows 8.1.

It's an issue with both `\n` and `\r\n`.

**Comment by rohieb** [comment] 2020-06-09 12:51
On etherpad 1.8.3, apparently there seems to be a difference between pasting with middle mouse button, which squashes all lines into one, and pasting with Ctrl-V, which does the right thing.

**Comment by JohnMcLear** [comment] 2020-06-09 15:52
@rohieb afaik it's fixed in ``develop``

**Closed by JohnMcLear** 2020-06-09 15:52 UTC
Labels: Needs confirmation

**Comment by alignwaivers** [comment] 2020-09-13 08:31
ctl-shift-v solved this problem for me in firefox 79 on Ubuntu 18
