### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5207] opened 2021-09-29 15:45 UTC
**Describe the bug**
require-kernel.js?v=c1d5264e:281 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
![Screen Shot 2021-09-29 at 22 44 19](https://user-images.githubusercontent.com/1982011/135303168-869e754f-5970-4975-a49d-3262ffaece0c.png)

might be related to to require-kernel.js
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
![Screen Shot 2021-09-29 at 22 45 57](https://user-images.githubusercontent.com/1982011/135303629-b2c9a072-c379-487b-8275-14e39dca57cf.png)

**Comment by rhansen** [comment] 2021-09-30 05:23
Duplicate of #4820.

**Closed by rhansen** 2021-09-30 05:23 UTC
