### ISSUE TITLE
Semver.js:Invalid version Error on accesing the admin panel

### ISSUE THREAD

**Issue by Billaboong** [ether/etherpad-lite#3228] opened 2017-07-26 13:09 UTC
Hi,
My etherpad lite was working fine but when I installed plugins I got the following error attached.
![etherpad-lite-error](https://user-images.githubusercontent.com/4427236/28622298-b8a77094-721c-11e7-8510-9b4598726f54.png)

#npm -v
5.3.0
#gulp -v
CLI version 1.2.2
Local version 3.9.1
#node -v
v8.2.1

**Comment by lpagliari** [comment] 2017-07-26 13:17
Duplicate of #2837

**Closed by lpagliari** 2017-07-26 13:17 UTC

**Comment by Billaboong** [comment] 2017-07-27 05:00
@lpagliari How was the above issue resolved?

**Comment by lpagliari** [comment] 2017-07-27 12:47
It was not resolved, it is still opened. It's just that this issue is exactly the same as #2837, so we don't need 2 of them opened

**Comment by Billaboong** [comment] 2017-07-28 05:42
okay thanks alot...
