### ISSUE TITLE
arbitrary scrolled to top on mobile devices

### ISSUE THREAD

**Issue by shuyanglin** [ether/etherpad-lite#3181] opened 2017-05-04 01:44 UTC
when opening an etherpad instance on a mobile device (iPhone 4s, iPhone SE), user's portview would be brought to top in every few seconds

**Comment by lpagliari** [comment] 2017-05-04 14:36
@shuyanglin there are [some](https://github.com/ether/etherpad-lite/issues/2224) [issues](https://github.com/ether/etherpad-lite/pull/2743) already for this behaviour. This last one especially should had fixed that, but maybe it didn't.

Could you tell us which Etherpad version you're running, please?

**Comment by shuyanglin** [comment] 2017-05-04 14:47
1.6.1 
Last Updated was Mar 8

**Comment by lpagliari** [comment] 2017-05-04 15:28
Hum, I've tested with an iPhone 5s accessing https://beta.etherpad.org/ and did not have the same issue.

Do you have any plugins installed? If so, which ones?
Were you on read-only mode? Writing? Doing any action on pad, or just reading its content?

**Comment by shuyanglin** [comment] 2017-05-04 16:34
just accessed on beta.etherpad.org with iPhone SE and it works fine as well.
but most of the time I use etherpad on sandstorm, not sure if that's the reason?

**Comment by mark19891107** [comment] 2017-05-04 16:35
I've tried https://beta.etherpad.org/ on my iPhone, it's working fine for me

We run etherpad on sandstorm, use iPhone try to edit document and got the issue
I try to use demo on etherpad website (demo as sandstorm app too), has same problem
https://oasis.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60

Maybe the problem is related to sandstorm wrapping?

**Comment by lpagliari** [comment] 2017-05-04 17:19
@kentonv do you know if Sandstorm code is merged to the PR that fixed this issue (#2743)?

**Comment by mark19891107** [comment] 2017-05-04 17:35
It looks like it's merged the PR of issue?
https://github.com/kentonv/etherpad-lite/commit/0677501d0bb2bf552f739599af3cd3f99682bfdd

**Comment by kentonv** [comment] 2017-05-07 05:09
Yeah, Sandstorm Etherpad has everything from the Etherpad 1.6.1 release.

It's possible that Sandstorm is introducing its own mobile viewing bugs by forcing Etherpad into an iframe. iOS Safari is notoriously weird in its handling of iframes. Unfortunately I don't have an iPhone to test on...

**Comment by lpagliari** [comment] 2017-05-07 20:08
@kentonv if you have a Mac, you can simulate on XCode.

**Comment by lpagliari** [comment] 2017-05-07 20:10
@shuyanglin @mark19891107 I'm closing this issue here, as Etherpad does not have the mentioned behaviour. Please open an issue on Sandstorm repo and mention this issue here, so we can follow up what had already been discussed on this thread.

**Closed by lpagliari** 2017-05-07 20:10 UTC

**Comment by shuyanglin** [comment] 2017-05-08 00:48
Sure! Will do that. Thank you very much!
