### ISSUE TITLE
Clear Authorship Colors

### ISSUE THREAD

**Issue by aboettger-tuhh** [ether/etherpad-lite#5144] opened 2021-08-06 07:11 UTC
**Describe the bug**
After activating the function via the menu bar, an error message appears. The colored markers are not deleted.

It is not a principle malfunction, random tests have shown that it works with other pads.

**To Reproduce**
1. Go to a "special" pad
2. Click on `Clear Authorship Colors`
3. Confirm action

**Expected behavior**
Function as intended.

**Server (please complete the following information):**
 - Etherpad version: 1.8
 - OS: Ubuntu 20.04
 - Node.js version (`node --version`): v12.22.4
 - npm version (`npm --version`): 6.14.14

**Additional context**

Error message in browser
```
An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:
RangeError: selection starts before line start
at https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function at line 49
ErrorId: ZMBiwxLX3IEYMPWKzrje
Uncaught exception
URL: https://pads.rz.tuhh.de/p/[...]
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
```

Exception
```
[2021-08-06 07:02:23.271] [WARN] client - RangeError: selection starts before line start -- {  errorId: 'ZMBiwxLX3IEYMPWKzrje',
  type: 'Uncaught exception',
  msg: 'RangeError: selection starts before line start',  url: 'https://pads.rz.tuhh.de/p/[...]',
  source: 'https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function',  linenumber: 49,  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0',
  stack: '_findRowRange@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:49:1663\n' +
    'setAttributesOnRange@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:49:1122\n' +
    'De@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:5:15414\n' +    'n/<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:7221\n' +    'registerAceCommand/</<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:2777\n' +    'r@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:5:5786\n' +
    'r@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:5:5842\n' +
    'J@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:5:4025\n' +    'Ace2Inner/e.ace_callWithAce@https://pads.rz.tuhh.de/static/js/require-kernel.js?v=0e8c39c0 line 10 > Function:5:5867\n' +
    'Ace2Editor/this[t]<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:49:1426\n' +
    'r@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:49:985\n' +    'a/<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:49:1011\n' +
    'registerAceCommand/<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:2760\n' +
    'triggerCommand@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:2864\n' +
    'init/</<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:1829\n' +    'ep_etherpad-lite/static/js/pad_editbar.js/ToolbarItem.prototype.bind/<@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=0e8c39c0:37:919\n' +
    'dispatch@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=0e8c39c0:38:37590\n' +
    'add/v.handle@https://pads.rz.tuhh.de/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=0e8c39c0:38:35620\n'
}
```

**Comment by rhansen** [comment] 2021-08-06 08:31
Duplicate of #5128

**Closed** 2021-08-06 08:31 UTC
