### ISSUE TITLE
eejs is using blocking API :: Wont fix as it doesn't actually effect performance noticably.

### ISSUE THREAD

**Issue by fourplusone** [ether/etherpad-lite#642] opened 2012-04-16 17:35 UTC
readFileSync blocks the event loop until the file is read so it should not be used on every request: https://github.com/Pita/etherpad-lite/blob/7cf4510bf545927edead70931befb7d62ca5863c/src/node/eejs/index.js#L104 
//cc @redhog

**Comment by JohnMcLear** [comment] 2015-04-11 16:50
We're still yet to hit this issue as being a performance bottle neck despite lots of load testing.  With that in mind we're not too concerned about the current eejs implementation..  If anyone wants to share an opinion please go for it :)

**Comment by devoidfury** [comment] 2015-04-11 19:26
How much third-party code depends on ejs? It may be better to switch to a different engine that handles async well, unless it'll break a lot of code.

Alternatively, we could just cache the templates in memory and only read them from disk once.

**Comment by devoidfury** [comment] 2015-04-11 19:39
Actually, I see a quick performance win in eejs with caching the templates; let me take a stab at that and I'll get back to you.

**Comment by muxator** [comment] 2019-05-02 00:15
This is still true as of today:

https://github.com/ether/etherpad-lite/blob/c9664804f10a84a86b27b8f77135b5d8f37f40ef/src/node/eejs/index.js#L117

Just for info, as part of #3540, @raybellis already migrated a big part of the codebase to async/await. That work will be part of **1.8**. Sadly, eejs is stuck in the past.

**Comment by JohnMcLear** [comment] 2020-03-28 22:07
Afaik w/ the recent minification / caching efforts we're in a pretty good place.  I'm not sure we will get much gains from this change?

**Comment by muxator** [comment] 2020-03-28 23:04
Only testing could tell us.

I would leave this open, because the issue is different than minification/caching and is a good PITA to increase the desire to modernize the code base.

**Closed** 2020-06-04 23:18 UTC
Labels: Bug, wontfix
