### ISSUE TITLE
Authorship of bullet points changes when a second author edits them

### ISSUE THREAD

**Issue by timapril** [ether/etherpad-lite#3354] opened 2018-03-27 15:34 UTC
This has been recreated in both in our internal version of etherpad and on beta.etherpad.org (https://beta.etherpad.org/p/tapril_test).

When one author adds content to a bulleted list of items, the authorship correctly indicates the author. Once a second author modifies the bullet point, the authorship of the full bullet point changes to the second author and when using the hover author plugin, the author name shows as "[ojbect object]".

I do not recall this being an issue on 1.5.1 or before but I have not had a chance to go and do a binary search on the versions to figure out where the bug was introduced.

**Comment by JohnMcLear** [comment] 2018-04-03 12:48
I'm pretty sure this is a duplicate no?

**Comment by SayeedAmitabTimo** [comment] 2018-05-04 09:33
We have the same Issue but even with "classic" lines: When adding to another author's line, the ownership colour of the whole line, upto the editing point changes. So when adding at the end of line e.g. the whole line changes to the new authors colour. 

Only plugin we use is mypads.

I would love to see this fixed soon, as for our usecases its essential.

**Comment by benlind** [comment] 2018-06-06 20:56
@lpagliari, this is frustrating many of my colleagues. Do you have any updates?

**Comment by lpagliari** [comment] 2018-06-08 13:13
sorry, guys, I didn't have time to focus on Etherpad lately. I'll try to take a look on the next few days

**Comment by lpagliari** [comment] 2018-06-11 12:01
I could reproduce the first issue (line author is fully changed), but not the second one (_author name shows as "[ojbect object]"_). I'm still investigating the causes...

**Comment by dgoldfein** [comment] 2018-06-25 14:23
Hi @lpagliari,  Have you had a chance to look at the line author issue?  We could really use a fix for this even if you haven't had a chance to look at the second issue.

**Comment by lpagliari** [comment] 2018-07-02 09:56
@dgoldfein yes, I've been investigating the issue for the past couple of weekends. I still don't have a fix for it, but at least I found the commit that broke the behaviour. I'm looking on how to fix that now.

**Closed** 2018-07-09 20:44 UTC
Labels: Black hole bug, Bug

**Comment by lpagliari** [comment] 2018-07-09 20:46
Ok, after a (long) while, I was able to find a way to handle all the scenarios, and this issue is finally fixed.

**Comment by dgoldfein** [comment] 2018-07-10 15:41
@lpagliari, Thanks for fixing this!  We tested the dev code in our test environment and the fixes worked.  Can't wait for the next official release!

**Comment by dgoldfein** [comment] 2018-07-23 17:54
@lpagliari Any change of getting this rolled into an official release?  Who should I contact about that?

**Comment by lpagliari** [comment] 2018-07-23 22:56
I guess @muxator might help us here... Any plans for a new release, @muxator?

**Comment by muxator** [comment] 2018-07-23 23:33
My main concern is #3268: it fixes a bug, but breaks plugins.
If this change had a clear test case (see #3425) we could accept the breakage, provided we bump version number to **1.7** ([milestone](https://github.com/ether/etherpad-lite/milestone/10)) and have a clear communication plan.

If I had to cut a release right now, I would:
- revert #3268
- take a decision on minimum node version (#3424)
- release **1.6.7**
