### ISSUE TITLE
Don't wrap URLs

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5001] opened 2021-04-12 01:57 UTC
Lines can wrap in the middle of a link, which will break them

**Comment by OscarSmiley** [comment] 2021-07-21 18:31
Hey I can try taking a look at this

**Comment by JohnMcLear** [comment] 2021-09-09 12:45
@OscarSmiley Any progress?

**Comment by ayam04** [comment] 2023-07-08 23:21
hey i want to solve this issue, can u assign it to me?

**Comment by SamTV12345** [comment] 2023-07-09 08:20
@ayam04 Sure here you go.

**Comment by JohnMcLear** [comment] 2023-07-09 10:04
STR

Copy/paste below into a pad.  The Link will be broken.
```
https://etherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasurletherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasda/)[etherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasda](https://etherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasurletherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasetherpadsuperlongasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdas.com
```

**Comment by KSSaiTeja** [comment] 2023-08-16 18:59
hello @JohnMcLear, I want to work for this, can you please assign me this to me and also tell me clearly what should i fix

**Comment by SamTV12345** [comment] 2023-08-16 19:21
We have the problem that if you paste John's example into a pad that it starts to wrap over the lines. A fix could be that it won't be broken into pieces and displayed on a single line. 

Feel free to submit a pull request. As you can see we didn't get any update so the issue is still present and presumably nobody is working on this.

**Comment by KSSaiTeja** [comment] 2023-08-17 18:06
@JohnMcLear thanks for assigning this issue to me. i will work upon this, @SamTV12345 can i start work on this and make a PR

**Comment by JohnMcLear** [comment] 2023-08-17 18:29
@KSSaiTeja no need to ask, just go for it.

**Comment by KSSaiTeja** [comment] 2023-08-17 19:12
could you please tell me how can i fix this issue and which file i should look upon!, i know this question looks like. a dumb question, but please try to understand i am new to this opensoure, i am unable to see which file i should work on.. please help me that

**Comment by KSSaiTeja** [comment] 2023-08-18 19:41
i can't figure out the issue, i will work on another issues, please assign this to another person who're interested

**Comment by KSSaiTeja** [comment] 2023-08-25 20:05
i have gone through so many tasks.. now i understood how can i fix this issue.. can you please assign it to me..?

**Comment by SamTV12345** [comment] 2023-08-25 20:16
Sure.

**Comment by KSSaiTeja** [comment] 2023-08-26 20:45
ok i will work on this issue

**Comment by KSSaiTeja** [comment] 2023-08-27 16:07
i gone through so much time on code, finally fixed the issue.. please consider and merge my PR

**Comment by JohnMcLear** [comment] 2023-08-27 17:25
What if non URL content is on the line with it?

``white-space: nowrap;`` caused some issues w/ browsers a few years back but it might be fixed upstream now :)

Can you please include test coverage?  It might be tricky but should be possible.

**Comment by KSSaiTeja** [comment] 2023-08-27 17:28
it doesn't effect when i enter a non non URL content is on the line with the URL..

By the way could you please tell me how can i include a test coverage for this..

**Comment by SamTV12345** [comment] 2023-08-29 15:58
You need to insert a very long link in a pad. Check if it overflows and if it overflows check the boundaries so that the overflowing content=displayed content

**Comment by KSSaiTeja** [comment] 2023-08-29 17:24
sorry.. not get your point.. could you please explain me more cleary way

**Comment by SamTV12345** [comment] 2023-08-30 20:39
It was wrapping before so the content box is different. Now it is a single line of text. So that should be possible to test via JavaScript.

**Comment by JohnMcLear** [comment] 2023-08-31 10:46
Look at other tests in that folder, copy those.

https://github.com/ether/etherpad-lite/wiki/Getting-started-writing-tests-for-Etherpad-Lite  <-- this is the guide for backend and some info on frontend.

to access frontend tests visit ``/tests/frontend``  for example https://etherpad.wikimedia.org/tests/frontend/

**Comment by JohnMcLear** [comment] 2023-08-31 10:46
@SamTV12345 https://blog.etherpad.org/2013/11/11/getting-started-contributing/ this might also be useful for you, it's 10 years old but probably still has some useful info.

**Comment by SamTV12345** [comment] 2023-09-04 16:58
Thanks. Didn't know there is also a blog for Etherpad 😃 .

**Closed** 2024-02-11 10:22 UTC
Labels: Bug, Easy to solve, editor, good first issue

**Comment by raybellis** [comment] 2024-10-05 15:57
We've recently upgraded to Etherpad 2.x and (some of) our users don't like this behaviour.

Would it be possible to add horizontal scrollbars and a "there's more text to the right" marker if such lines are present?
