### ISSUE TITLE
Alt+c shortcut in conflict with Polish keyboard

### ISSUE THREAD

**Issue by Halibutt** [ether/etherpad-lite#2917] opened 2016-02-25 02:24 UTC
Hi there. The chat feature is great. However, because of it there is a problem that makes Etherpad pretty unusable for many of us from outside of the Latin-1 encoding world. The problem is that Etherpad apparently doesn't differentiate between Alt and Right Alt keys. 

The earlier is up for grabbing, but the latter is reserved in many languages (Polish and Latvian, among others) for typing local diacritics. I guess Belgians can live without the © sign (that's what Alt+c does in Belgium), but Poles cannot write Polish without ć, it's one of frequently used letters. Same for Latvian č. Yet, when writing, all of a sudden the chat is turned on and hijacks the focus. 

A common solution is to reserve only the left Alt for the shortcuts - or switch to standard Ctrl+ or Shift+Ctrl+ for keyboard shortcuts.

**Comment by lpagliari** [comment] 2016-02-25 12:28
Looks like a duplicate of #2884. Let us know if it is not.

**Closed by lpagliari** 2016-02-25 12:28 UTC

**Comment by Halibutt** [comment] 2016-02-25 15:09
Yeah, kind of. Replied in the other thread.
