### ISSUE TITLE
Import a PDF file not working

### ISSUE THREAD

**Issue by quydang** [ether/etherpad-lite#2864] opened 2015-12-24 08:08 UTC
Importing a text file breaks abiwords capability to import PDF files until service restart.

STR.
1. Create pad
2. Import Text file
3. Attempt to import PDF file

Import will fail.  This is probably caused by reasons modification to the import logic

**Comment by JohnMcLear** [comment] 2015-12-24 12:32
What are the steps to replicate here?

**Comment by quydang** [comment] 2015-12-25 02:48
Hi @JohnMcLear :First, I created new pad on https://beta.etherpad.org/ . I edited content of pad, export current pad to HTML, text, etherpad, PDF,DOC file.
Then, I import PDF file, it work. But, after importing text file, I can not import PDF file again.
In my local etherpad, I have same error. I can restart service etherpad for import PDF file again. But, after import text file, the error occur.
I just test and replicate the error. I don't know where root cause is. Please take a look.
Thanks

**Comment by JohnMcLear** [comment] 2016-01-19 13:09
Unable to replicate this locally..  beta.etherpad.org does seem to have an issue w/ importing pdf, prolly caused by abiword service..

**Comment by JohnMcLear** [comment] 2016-01-19 13:12
Okay so TLDR;

Importing a text file breaks abiwords capability to import until service restart.

**Comment by vnc-rainer-schuth** [comment] 2016-01-19 15:12
I am also having this bug.
Related to #2782

**Comment by jainendra** [comment] 2017-07-27 07:27
Does anyone have a fix for this or any follow up?

**Comment by jainendra** [comment] 2017-07-28 06:29
@JohnMcLear @quydang Any fix or info

**Comment by JohnMcLear** [comment] 2020-03-30 20:00
I'm unable to replicate this bug on latest develop.  Plase re-open if it still exists for you.

**Closed by JohnMcLear** 2020-03-30 20:00 UTC
Labels: Bug, Export/Import
