### ISSUE TITLE
HTML export: headings are duplicated

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2981] opened 2016-05-14 18:37 UTC
When I format headlines my  HTML export is quite interesting, because the headlines are actually repeated three times.
```html
<h1 style="font-size: 2.0em;line-height: 120%;">HEADLINE</h1>
<h1>HERADLINE</h1>
```
BTW: The two look the same although the second misses some CSS...

This happens with every headline level...

**Comment by webzwo0i** [comment] 2016-05-14 18:43
problem with getLineHTMLForExport ?

**Comment by webzwo0i** [comment] 2016-05-14 18:45
Can you try disabling plugins?

duplicate https://github.com/ether/etherpad-lite/issues/2486

**Comment by rugk** [comment] 2016-05-14 18:53
> Can you try disabling plugins?

I have no idea where to start. What plugins could interfere here? (Plugins which change text formatting?)

**Comment by webzwo0i** [comment] 2016-05-14 19:02
one of these? 
ep_align
ep_authorship_export
ep_colors
ep_context
ep_custom_styles
ep_export_authors
ep_export_documents_images
ep_font_color
ep_foot_note
ep_headings2
ep_headings
ep_horizontal_line
ep_html_export_using_client_filters
ep_import_documents_images
ep_line_height
ep_margin
ep_markdown
ep_mediawiki
ep_page_ruler
ep_page_view
ep_sizes
ep_superscript
ep_tables2

**Comment by rugk** [comment] 2016-05-14 19:27
Can I somehow disable a plugin without uninstalling it?

(I already tried to move the dir in `node_modules` somewhere else, but if I do so Etherpad crashes...)

**Comment by lpagliari** [comment] 2016-05-15 15:48
All values returned by the plugins on `getLineHTMLForExport` are concatenated. You might have a plugin that adds the `<h1>` and another that adds `<h1 style="font-size: 2.0em;line-height: 120%;">`.

Regarding disabling the plugins, you can move folders form `node_modules` to somewhere else, just make sure you restart Etherpad after doing that. The reason, I guess, is because Etherpad loads plugins data when it starts, so if you simply remove a plugin folder somewhere else Etherpad would still be expecting the folder to be on `node_modules`.

**Comment by lpagliari** [comment] 2016-05-15 15:52
As this is a duplicate of #2486 and John had a candidate to fix the issue, I'm closing this one.

**Closed by lpagliari** 2016-05-15 15:52 UTC
