### ISSUE TITLE
Keyboard Shortcuts and languages

### ISSUE THREAD

**Issue by kamilmowinski** [ether/etherpad-lite#2884] opened 2016-01-14 06:58 UTC
Hi,
i have a problem with shortcuts. When i set english language on my system i can not type "ć" (ALT + C) becouse it shortcut activate chat window. But when my language is polish everythink is ok. 

Its possible to disable this shortcut or can you show me when in code i can turn off it?

Regards,
Kamil Mówiński

**Comment by JohnMcLear** [comment] 2016-01-19 12:56
https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3729

**Comment by bhldev** [comment] 2016-02-13 15:25
Please see #2891 for workaround, disable shortcut in settings.json

Please give [bounty](https://www.bountysource.com/issues/30676386-iceweasel-switching-tabs-with-pgup-down-moves-the-cursor-in-the-pad) for UI/plugin development "enable/disable shortcut keys", UI will look like this  
![image](https://cloud.githubusercontent.com/assets/4929336/13028377/5944fe28-d23b-11e5-936b-3d1783dfeb6c.png)

**Comment by Halibutt** [comment] 2016-02-25 15:09
In the closed thread referenced above I explained why this issue is important. The fix mentioned in this thread is not really usable for your average user, who has no access to server settings. 

Also, this issue is not really a duplicate since my system language is set to Polish, yet the chat hijacks the keyboard when I hit Right Alt + c anyway. I wonder if changing the shortcut to Left Alt + c is that complicated... Any ideas how to do that?

**Comment by lpagliari** [comment] 2016-02-25 15:26
@Halibutt as @JohnMcLear mentioned [above](https://github.com/ether/etherpad-lite/issues/2884#issuecomment-172845087), you need to change ace2_inner.js. You might check the event `location`(https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location). Hope this helps.

**Comment by Halibutt** [comment] 2016-02-26 09:14
@lpagliari , thanks a lot for your comment above, but it seems I'm way dumber than I thought and I have no idea what you suggest. I'm an end user, not a programmer. 

From what I understand, the workaround might be cool for someone who hosts an instance of etherpad and has access to all the files (and could change ace2_inner.js, wherever it is). I'm but a guy who used to use Etherpad quite frequently, and now cannot. Because it doesn't work as expected, because of a conflict that most likely is easy to fix for some code ninja (say, fix it for ALL people out there instead for me only), but for an end user like me is pure magic.

**Comment by lpagliari** [comment] 2016-02-26 10:11
LOL. Sorry, @Halibutt, I thought you were a programmer. The ideas I've mentioned were for a developer to fix the bug and submit the fix for it, so other people could use the same solution. I'll try to work on it and submit the fix myself.

**Comment by Halibutt** [comment] 2016-02-27 02:17
Cool, thanks a lot. :)

**Comment by lpagliari** [comment] 2016-03-02 14:44
ok, I've tried to use event `location`, but it does not differentiate left and right Alt when pressed with another key. I'll try other alternatives (if I find any), but if I cannot find a way to differentiate the two Alt keys I would suggest to have an option on settings that could enable/disable the shortcut. At least in this case the regular user would be able to avoid the issue...

Does anyone have another suggestion for me to try?

I won't be able to take a look on this right now, will see if I can work on it next week.

**Comment by Halibutt** [comment] 2016-03-08 10:15
Holding my thumbs :)

**Comment by lpagliari** [comment] 2017-05-11 18:26
@kamilmowinski @Halibutt #2891 was merged, so now it is possible to disable some shortcuts on the `settings.json` of Etherpad instance.

It is still not possible for an end-user to configure her/his personal preferences, nor distinguishing between regular `Alt` and `Alt Gr` keys, as @Halibutt suggested.

I hope it helps you.

**Comment by JohnMcLear** [comment] 2020-03-26 23:59
Key for AltGraph is now a thing: https://stackoverflow.com/questions/8562528/is-there-a-way-to-detect-which-side-the-alt-key-was-pressed-on-right-or-left

Can't believe we haven't fixed this yet ⭕️

**Comment by muxator** [comment] 2020-03-27 01:16
@kamilmowinski, @halibutt (for #2917), I am trying to test @JohnMcLear's patch in #3764, which should fix this problem, but I am missing something 

**Is it possible that this problem is no longer relevant**?

@Halibutt [in this comment](https://github.com/ether/etherpad-lite/issues/2884#issuecomment-188827979) wrote:
> the chat hijacks the keyboard when I hit Right Alt + c

My keyboard is not Polish, but has the `AltGr`(the right Alt) key (`AltGr` + `c` types `¢`, `Alt` + `c` does not type anything).

In a recent Etherpad (let's say **1.8.0+**) I am able to type `¢` pressing `AltGr` + `c`, without opening the chat window. Pressing `left alt` + `c`, instead, opens the chat window as expected.

If someone confirms that this problem no longer exists, we can close this issue.

**Comment by JohnMcLear** [comment] 2020-07-11 22:50
I'm gonna go ahead and close as no one can reproduce the bug.

**Closed by JohnMcLear** 2020-07-11 22:50 UTC
Labels: Bug, Easy to solve, Waiting on Testing, editor
