### ISSUE TITLE
Spanish accents work with unusual keystrokes in linux

### ISSUE THREAD

**Issue by bruo** [ether/etherpad-lite#2580] opened 2015-04-06 14:31 UTC
Hi,

I've been having an issue with etherpad and spanish accents, commonly to make the á symbol you write ´ then a. In etherpad (tested in beta, pad.riseup.net and my own install) this doesn't work, to make á i have to press ´, keep it pressed and then a.

This behavoir doesn't happen in osx, and it seems it's a linux or gnome related issue as i tested several browsers and it keeps happening.

If there is anything to help to debug this, let me know. I haven't tried to install another desktop environment because i would want to avoid that, but i can do it if there is no other choice.

Thanks for you work!

**Comment by JohnMcLear** [comment] 2015-04-06 16:46
Which OS? 
Can you provide a virtual machine that shows this behavior?
Which keyboard layout?

Yes it's probably an OS issue, you can see if you can replicate here: http://html5demos.com/contenteditable

Cheers

J

**Comment by bruo** [comment] 2015-04-08 13:38
Hi again,

It took me sometime as i was really busy with irl stuff.

So, first the data. Im using Debian testing, my main browser is iceweasel/firefox 37.0.1, which seems to be the problematic one. So, i setted up a VM of debian testing and i was unable to reproduce the problem with the iceweseal package it had (31.6.0esr-1)... then i upgraded to latest version and there it was! then checked if it was an iceweasel issue and tested latest firefox which had the same problem.

I'm not able to reproduce this with chrome.

I have no issues with http://html5demos.com/contenteditable in my local environment or the VM in firefox or chrome.

I use a latinoamerican spanish layout (latam)

If there is another thing to track this error (or even to know if i have to bug mozilla) let me know!

thanks

**Comment by JohnMcLear** [comment] 2015-04-10 09:28
Can you send me a VM which I can use to replicate this issue?

**Comment by JohnMcLear** [comment] 2015-04-28 22:07
Gonna guess this is a duplicate of the other deadkeys issue so will close.

**Closed by JohnMcLear** 2015-04-28 22:07 UTC
Labels: Needs confirmation
