### ISSUE TITLE
Importing unordered lists with a 'space' between the UL and LI adds an extra list entry - AWAITING REVIEW / MERGE

### ISSUE THREAD

**Issue by tombriles** [ether/etherpad-lite#3620] opened 2019-07-02 17:57 UTC
Here is a very simple example:

`<html><body><ul> <li>FOO</li></ul></body></html>`

There will be two bullets when this is imported.

**Comment by muxator** [comment] 2020-03-19 02:03
Reopening, because #3622 had to be reverted because introduced a regression (#3728).

**Comment by JohnMcLear** [comment] 2020-03-26 16:34
Input of:
```
<html><body><ul> <li>FOO</li></ul></body></html>
```

Turns into:
```
<!doctype html><html><body><ul class="bullet"><li>&nbsp;</li><li>FOO</ul></body></html>
```

Expected clean output would be:
```
<!doctype html><html><body><ul class="bullet"><li>FOO</li></ul></body></html>
```

- [ ] Understand the addition of the blank additional li.
- [ ] Understand the lack of closed </li>

**Comment by JohnMcLear** [comment] 2020-03-26 16:42
Well, even 
```
var html = '<html><body><ul><li>FOO</li></ul></body></html>';
```
Fails to properly import.  It misses the closing ``</li>``

**Comment by JohnMcLear** [comment] 2020-03-26 19:49
Turns out the trailing </li> is optional, I mean, I hate that but whatever.

**Comment by JohnMcLear** [comment] 2020-03-26 20:30
This problem occurs in OL too..  It's hard to explain but I will try...

Essentially the list _begins_, then you have content(in this case `` ``).  You have three choices.  
1) Exit out of the list
2) Assume it's a line item.  
3) Assume it's none list content within a list, Etherpad doesn't understand that concept.

To replicate this, open a pad with contents:
```
foo
bar
late
```

Make this a numbered list, select the line "bar", press Shift Tab.

Note that "late" is now 1), it should be 2)

Google Docs gets this right(ish[shift tab isn't supported]) but they support the concept of a non list item within a list.

So the TLDR here is that contentcollector needs to support non list items within lists. 

This is a rewrite of list handling logic in contentcollector, it's a big job.  contentcollector has been touched historically and maybe we did have this working at some point, I can maybe look into that but I don't think the rewrite of contentcollector list logic is doable with my day-to-day life as it is.

**Comment by JohnMcLear** [comment] 2020-03-26 21:16
Aha, I knew this felt familiar..  Here I talked about it back in 2014.. https://github.com/ether/etherpad-lite/issues/2194

**Comment by JohnMcLear** [comment] 2020-04-06 19:30
I made a start on this today.  Essentially I'm going to say that if there is an indented LI between ULs or OLs then that makes a list persist.  It should be a fine UX.

**Comment by JohnMcLear** [comment] 2020-04-10 11:46
So as no one had input in this I'm going to go with option 3 which is create logic for Etherpad to understand that lists can have non list items..  So Etherpad will support
```
1. foo
bar.
2. late
```

```
1. foo
    <!-- this is indented so list is retained -->    
2. late
```


```
1. foo
<!-- there is no content here at all so the list numbering starts again --->
1. late
```

```
1. foo
2. bar
<!-- there is no content here at all so the list numbering starts again --->
1. late
```


```
1. foo
    1.1. bar
    <!-- this is indented so list is retained -->    
    1.2 late
2. derp
```

```
1. foo
    1.1. bar
<!-- no content here so list is destroyed -->
    1.1 late
2. derp
```

Important: Double enter should always leave a list.  To do this I would need logic to see if the line prior to the previous line is a list, if it is then I will need to see if hte prior line has no contents (it cna be intended) and if all these conditions are met we will need to de-indent the previous line (not possible). and then remove line type on this one..  Saying this out loud we could just say if previous line was indented and contents is empty then deintend current line (don't add a new line), this means catch enter key, and doing a de-indent instead of a new line.

**Comment by JohnMcLear** [comment] 2020-04-10 11:51
Weirdly I noticed Google Docs and Microsoft Office handle this differently

Gdocs
![image](https://user-images.githubusercontent.com/220864/78988697-98768080-7b29-11ea-9535-72b6ec24b354.png)

Office:
![image](https://user-images.githubusercontent.com/220864/78988718-a3c9ac00-7b29-11ea-9911-e32996b7c80c.png)

LibreOffice Writer appears to be on crack.
![image](https://user-images.githubusercontent.com/220864/78988802-d378b400-7b29-11ea-9d4c-1587b1cb16f5.png)

But the take away seems to be everyone but Word drops line numbering between breaks.  Probably due how how the documents are iterated over with XML being a tree and JSON probably being optimized for line by line?  IDK, but either way I prefer GDocs over the other two.

**Comment by JohnMcLear** [comment] 2020-07-16 09:53
I'm now happy with our list handling in Etherpad so this can be closed.  The current behavior(at time of writing this comment) and test coverage is the expected UX.

**Closed by JohnMcLear** 2020-07-16 09:53 UTC
Labels: Bug, Export/Import, Waiting on Testing, editor
